# Generated by Django 3.2.15 on 2022-11-17 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0005_adapt_models_for_new_admin'),
        ('forms', '0003_migrate_permits_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeEntityForAdminSite',
            fields=[
            ],
            options={
                'verbose_name': '1.1 Entité administrative (commune, organisation)',
                'verbose_name_plural': '1.1 Entités administratives (commune, organisation)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.administrativeentity',),
        ),
        migrations.AlterModelOptions(
            name='field',
            options={'verbose_name': '1.3 Champ', 'verbose_name_plural': '1.3 Champs'},
        ),
        migrations.AlterModelOptions(
            name='form',
            options={'ordering': ('order',), 'verbose_name': '1.4 Formulaire', 'verbose_name_plural': '1.4 Formulaires'},
        ),
        migrations.AlterModelOptions(
            name='formcategory',
            options={'verbose_name': '1.2 Catégorie', 'verbose_name_plural': '1.2 Catégories'},
        ),
        migrations.AlterModelOptions(
            name='formfield',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='forms.field', verbose_name='Champ'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Position dans le formulaire'),
        ),
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(7, 'Architecte/Ingénieur'), (6, 'Association'), (0, 'Autres'), (8, 'Direction des travaux'), (3, 'Entreprise'), (4, "Maître d'ouvrage"), (2, 'Propriétaire'), (1, "Requérant (si différent de l'auteur de la demande)"), (5, 'Sécurité')], default=0, verbose_name='type de contact')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='obligatoire')),
                ('form_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_types', to='forms.formcategory', verbose_name='type de demande')),
                ('integrator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Groupe des administrateurs')),
            ],
            options={
                'verbose_name': '1.5 Contact',
                'verbose_name_plural': '1.5 Contacts',
                'unique_together': {('type', 'form_category')},
            },
        ),
        migrations.CreateModel(
            name='ContactTypeForAdminSite',
            fields=[
            ],
            options={
                'verbose_name': '1.5 Contact',
                'verbose_name_plural': '1.5 Contacts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('forms.contacttype',),
        ),
    ]
