# Generated by Django 4.1 on 2022-12-01 23:49

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models

import geocity.apps.forms.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forms", "0005_initial_form_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nom des paramètres"),
                ),
                (
                    "prices_label",
                    models.CharField(
                        default="Tarifs",
                        help_text="Texte affiché à l'utilisateur comme en-têtes des prix (p. ex.: 'Tarifs')",
                        max_length=255,
                        verbose_name="Label pour les tarifs",
                    ),
                ),
                (
                    "internal_account",
                    models.CharField(
                        help_text="Compte interne de comptabilité utilisé pour les paiements",
                        max_length=255,
                        verbose_name="Compte interne",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètres de paiement",
                "verbose_name_plural": "Paramètres de paiement",
            },
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255, verbose_name="Texte")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Montant"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default=geocity.apps.forms.models.default_currency,
                        max_length=20,
                        verbose_name="Devise",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarif",
                "verbose_name_plural": "Tarifs",
            },
        ),
        migrations.AddField(
            model_name="form",
            name="requires_online_payment",
            field=models.BooleanField(
                default=False, verbose_name="Soumis au paiement en ligne"
            ),
        ),
        migrations.CreateModel(
            name="HistoricalPrice",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("text", models.CharField(max_length=255, verbose_name="Texte")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Montant"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default=geocity.apps.forms.models.default_currency,
                        max_length=20,
                        verbose_name="Devise",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Tarif",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="FormPrice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="forms.form"
                    ),
                ),
                (
                    "price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="forms.price"
                    ),
                ),
            ],
            options={
                "unique_together": {("price", "form")},
            },
        ),
        migrations.AddField(
            model_name="form",
            name="payment_settings",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="forms.paymentsettings",
                verbose_name="Paramètres de paiement",
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="prices",
            field=models.ManyToManyField(
                related_name="forms",
                through="forms.FormPrice",
                to="forms.price",
                verbose_name="tarifs",
            ),
        ),
    ]
