# Generated by Django 3.2.15 on 2022-11-09 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0005_admin_models_names"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="formfield",
            options={"ordering": ["order"]},
        ),
    ]
