# Generated by Django 4.1 on 2022-11-29 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0005_initial_form_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="administrativeentityforadminsite",
            options={
                "verbose_name": "1.1 Entité administrative",
                "verbose_name_plural": "1.1 Entités administratives",
            },
        ),
    ]
