# Generated by Django 4.1 on 2022-12-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0006_paymentsettings_price_form_requires_online_payment_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="formprice",
            options={"ordering": ("order",)},
        ),
        migrations.AddField(
            model_name="formprice",
            name="order",
            field=models.PositiveSmallIntegerField(
                db_index=True, default=0, verbose_name="Position dans les tarifs"
            ),
        ),
    ]
