# Generated by Django 4.1 on 2022-12-05 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_rename_admin_entities_shorter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='has_geom_intersection_enabled',
        ),
    ]
