# Generated by Django 4.1 on 2022-12-07 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0007_remove_geom_layer"),
        ("forms", "0008_paymentsettings_api_key_and_more"),
    ]

    operations = []
