# Generated by Django 4.1 on 2022-12-08 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0009_merge_20221207_0953"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="requires_online_payment",
            field=models.BooleanField(
                default=False,
                help_text="Pensez à configurer les <strong>tarifs</strong> associés à ce formulaire avant d'activer le paiement en ligne",
                verbose_name="Soumis au paiement en ligne",
            ),
        ),
        migrations.AlterField(
            model_name="formprice",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="forms.form",
                verbose_name="Formulaire",
            ),
        ),
        migrations.AlterField(
            model_name="formprice",
            name="price",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="forms.price",
                verbose_name="Tarif",
            ),
        ),
    ]
