# Generated by Django 4.1.4 on 2022-12-15 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0012_alter_historicalprice_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="formprice",
            options={"ordering": ("order", "price")},
        ),
    ]
