# Generated by Django 4.1.4 on 2023-01-19 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0008_alter_field_integrator_alter_form_integrator_and_more"),
        ("forms", "0014_alter_paymentsettings_payment_confirmation_report_and_more"),
    ]

    operations = []
