# Generated by Django 4.1.4 on 2023-02-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0016_alter_historicalprice_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="message_for_notified_services",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Message transmis aux services notifiés",
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="max_submissions",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Nombre maximum de demandes"
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="max_submissions_message",
            field=models.CharField(
                blank=True,
                default="Ce formulaire est désactivé car le nombre maximal de soumissions a été atteint.",
                max_length=300,
                null=True,
                verbose_name="Message lorsque le nombre maximal est atteint",
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="is_public",
            field=models.BooleanField(default=False, verbose_name="Formulaire public"),
        ),
    ]
