# Generated by Django 4.1.7 on 2023-03-07 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0017_field_message_for_notified_services_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="field",
            name="field_choices_not_empty_for_lists",
        ),
        migrations.RenameField(
            model_name="field",
            old_name="choices",
            new_name="_choices",
        ),
        migrations.RenameField(
            model_name="field",
            old_name="help_text",
            new_name="_help_text",
        ),
        migrations.RenameField(
            model_name="field",
            old_name="name",
            new_name="_name",
        ),
        migrations.RenameField(
            model_name="field",
            old_name="placeholder",
            new_name="_placeholder",
        ),
    ]
