# Generated by Django 4.1.7 on 2023-03-10 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0017_field_message_for_notified_services_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalprice",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Un montant de 0 peut être utilisé pour avoir un tarif gratuit",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Montant",
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Un montant de 0 peut être utilisé pour avoir un tarif gratuit",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Montant",
            ),
        ),
    ]
