# Generated by Django 4.1.7 on 2023-03-10 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("forms", "0017_field_message_for_notified_services_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MapWidgetConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Nom de la configuration"
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        verbose_name="Configuration du Widget cartographique"
                    ),
                ),
                (
                    "integrator",
                    models.ForeignKey(
                        limit_choices_to={
                            "permit_department__is_integrator_admin": True
                        },
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="auth.group",
                        verbose_name="Groupe des administrateurs",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="form",
            name="map_widget_configuration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="forms.mapwidgetconfiguration",
                verbose_name="Configuration de la carte avancée",
            ),
        ),
    ]
