# Generated by Django 4.1.7 on 2023-03-07 15:35

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0018_rename_untranslated_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="nom")),
                (
                    "placeholder",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="exemple de donnée à saisir",
                    ),
                ),
                (
                    "help_text",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="information complémentaire",
                    ),
                ),
                (
                    "choices",
                    models.TextField(
                        blank=True,
                        help_text="Entrez un choix par ligne",
                        verbose_name="valeurs à choix",
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="forms.Field",
                    ),
                ),
            ],
            options={
                "verbose_name": "1.3 Traduction de Champ",
                "db_table": "forms_field_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
