# Generated by Django 4.1.7 on 2023-03-10 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0018_add_fields_for_new_map_widget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="map_widget_configuration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="map_widget_configuration_form",
                to="forms.mapwidgetconfiguration",
                verbose_name="Configuration de la carte avancée",
            ),
        ),
    ]
