# Generated by Django 4.2.1 on 2023-05-24 08:46

import django.db.models.deletion
import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("forms", "0019_alter_form_administrative_entities"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="geo_widget_option",
            field=models.IntegerField(
                choices=[(1, "Générique"), (2, "Avancée")],
                default=1,
                verbose_name="Choix de l'interface de saisie cartographique",
            ),
        ),
        migrations.CreateModel(
            name="MapWidgetConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Nom de la configuration"
                    ),
                ),
                ("configuration", django_jsonform.models.fields.JSONField()),
                (
                    "integrator",
                    models.ForeignKey(
                        limit_choices_to={
                            "permit_department__is_integrator_admin": True
                        },
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="auth.group",
                        verbose_name="Groupe des administrateurs",
                    ),
                ),
            ],
            options={
                "verbose_name": "1.8 Module cartographique avancé",
                "verbose_name_plural": "1.8 Modules cartographiques avancés",
            },
        ),
        migrations.AddField(
            model_name="form",
            name="map_widget_configuration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="map_widget_configuration_form",
                to="forms.mapwidgetconfiguration",
                verbose_name="Configuration de la carte avancée",
            ),
        ),
    ]
