# Generated by Django 4.2.1 on 2023-06-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0020_map_widget_configuration"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="api_name",
            field=models.CharField(
                blank=True,
                help_text="Se génère automatiquement lorsque celui-ci est vide.",
                max_length=255,
                verbose_name="Nom dans l'API",
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="api_name",
            field=models.CharField(
                blank=True,
                help_text="Se génère automatiquement lorsque celui-ci est vide.",
                max_length=255,
                verbose_name="Nom dans l'API",
            ),
        ),
    ]
