# Generated by Django 4.1.7 on 2023-03-08 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0020_add_untranslated_values_of_form_as_defaults"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fieldtranslation",
            options={
                "default_permissions": (),
                "managed": True,
                "verbose_name": "1.3 Champ Translation",
            },
        ),
        # migrations.AddConstraint(
        #     model_name='field',
        #     constraint=models.CheckConstraint(
        #         check=models.Q(('input_type__in', ['list_single', 'list_multiple']),
        #                        ('translations__choices', ''), _negated=True),
        #         name='field_choices_not_empty_for_lists'),
        # ),
        migrations.RemoveField(
            model_name="field",
            name="_choices",
        ),
        migrations.RemoveField(
            model_name="field",
            name="_help_text",
        ),
        migrations.RemoveField(
            model_name="field",
            name="_name",
        ),
        migrations.RemoveField(
            model_name="field",
            name="_placeholder",
        ),
    ]
