# Generated by Django 4.2.1 on 2023-06-26 11:57
from django.db import migrations


class Migration(migrations.Migration):
    def input_type_title_update(apps, schema_editor):
        Field = apps.get_model("forms", "Field")

        for field in Field.objects.all().filter(input_type="title"):
            field.input_type = "title_output"
            field.save(update_fields=["input_type"])

    dependencies = [
        (
            "forms",
            "0021_alter_field_input_type",
        ),
    ]

    operations = [
        migrations.RunPython(input_type_title_update),
    ]
