# Generated by Django 4.2.1 on 2023-07-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0022_datamigration_form_and_field_api_name_and_input_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='allowed_file_types',
            field=models.CharField(blank=True, help_text='Ex: "pdf, jpg, png"', max_length=255, verbose_name='Permet de restreindre plus finement les extensions autorisées'),
        ),
        migrations.AddField(
            model_name='field',
            name='max_file_upload_size',
            field=models.PositiveBigIntegerField(help_text='Ex: "10485760"', null=True, verbose_name='Permet de restreindre plus finement la taille (en bytes) maximum des fichiers'),
        ),
    ]
