# Generated by Django 4.2.1 on 2023-07-26 12:57

import re
import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0022_datamigration_form_and_field_api_name_and_input_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="quick_access_slug",
            field=models.TextField(
                blank=True,
                default=uuid.uuid4,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-a-zA-Z0-9_]+\\Z"),
                        "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.",
                        "invalid",
                    )
                ],
                verbose_name="URL courte",
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forms",
                to="forms.formcategory",
                verbose_name="catégorie",
            ),
        ),
        migrations.DeleteModel(
            name="ContactTypeForAdminSite",
        ),
        migrations.AddField(
            model_name="field",
            name="allowed_file_types",
            field=models.CharField(
                blank=True,
                help_text='Ex: "pdf, jpg, png"',
                max_length=255,
                verbose_name="Restreindre plus finement les extensions autorisées",
            ),
        ),
    ]
