# Generated by Django 4.2.1 on 2023-07-26 12:57

import re
import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0022_datamigration_form_and_field_api_name_and_input_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="quick_access_slug",
            field=models.TextField(
                blank=True,
                default=uuid.uuid4,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-a-zA-Z0-9_]+\\Z"),
                        "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.",
                        "invalid",
                    )
                ],
                verbose_name="URL courte",
            ),
        ),
    ]
