# Generated by Django 4.2.1 on 2023-08-02 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0022_datamigration_form_and_field_api_name_and_input_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forms",
                to="forms.formcategory",
                verbose_name="catégorie",
            ),
        ),
        migrations.DeleteModel(
            name="ContactTypeForAdminSite",
        ),
    ]
