# Generated by Django 4.2.1 on 2023-08-03 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0023_alter_form_category_and_delete_contacttypeforadminsite"),
        ("submissions", "0022_contactform_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactFormForAdminSite",
            fields=[],
            options={
                "verbose_name": "1.5 Contact",
                "verbose_name_plural": "1.5 Contacts",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("submissions.contactform",),
        ),
        migrations.CreateModel(
            name="ContactTypeForAdminSite",
            fields=[],
            options={
                "verbose_name": "1.9 Type de contact",
                "verbose_name_plural": "1.9 Types de contacts",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("submissions.contacttype",),
        ),
    ]
