# Generated by Django 4.2.1 on 2023-08-03 06:12
import re
import uuid

import django.core.validators
from django.db import migrations, models


def generate_uuids(apps, schema_editor):
    Form = apps.get_model("forms", "Form")
    for row in Form.objects.all():
        row.quick_access_slug = uuid.uuid4()
        row.save(update_fields=["quick_access_slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0023_form_slug_and_category_field_file_types"),
        ("submissions", "0022_contactform_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactFormForAdminSite",
            fields=[],
            options={
                "verbose_name": "1.5 Contact",
                "verbose_name_plural": "1.5 Contacts",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("submissions.contactform",),
        ),
        migrations.CreateModel(
            name="ContactTypeForAdminSite",
            fields=[],
            options={
                "verbose_name": "1.9 Type de contact",
                "verbose_name_plural": "1.9 Types de contacts",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("submissions.contacttype",),
        ),
        migrations.AlterField(
            model_name="form",
            name="quick_access_slug",
            field=models.TextField(
                blank=True,
                default=uuid.uuid4,
                help_text="Permettant d'accéder directement au formulaire par l'url: https://geocity.ch/?form=demande-macaron",
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-a-zA-Z0-9_]+\\Z"),
                        "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.",
                        "invalid",
                    )
                ],
                verbose_name="URL courte",
            ),
        ),
    ]
