# Generated by Django 4.2.1 on 2023-08-03 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0023_alter_form_category"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContactTypeForAdminSite",
        ),
    ]
