# Generated by Django 4.2.1 on 2023-07-26 13:07

import uuid

from django.db import migrations


def generate_uuids(apps, schema_editor):
    Form = apps.get_model("forms", "Form")
    for row in Form.objects.all():
        row.quick_access_slug = uuid.uuid4()
        row.save(update_fields=["quick_access_slug"])


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0023_add_form_quick_access_slug"),
    ]

    operations = [
        migrations.RunPython(generate_uuids, reverse_code=migrations.RunPython.noop)
    ]
