# Generated by Django 4.2.4 on 2023-09-12 06:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0024_form_slug_and_contactformforadminsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='map_widget_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map_widget_configuration_field', to='forms.mapwidgetconfiguration', verbose_name='Configuration de la carte avancée'),
        ),
        migrations.AlterField(
            model_name='field',
            name='input_type',
            field=models.CharField(choices=[('address', 'Adresse'), ('checkbox', 'Case à cocher'), ('list_multiple', 'Choix multiple'), ('list_single', 'Choix simple'), ('date', 'Date'), ('file', 'Fichier'), ('file_download', 'Fichier (à télécharger)'), ('number', 'Nombre'), ('text', 'Texte'), ('regex', 'Texte (regex)'), ('geom', 'Géométrie (points)'), ('datetime_range', 'Plage temporelle'), ('text_output', 'Texte à afficher'), ('title_output', 'Titre à afficher')], max_length=30, verbose_name='type de caractéristique'),
        ),
        migrations.AlterField(
            model_name='form',
            name='quick_access_slug',
            field=models.UUIDField(blank=True, default=uuid.uuid4, help_text="Permettant d'accéder directement au formulaire par l'url: https://geocity.ch/?form=URL_COURTE<br>\n            Pour une demande anonyme https://geocity.ch/submissions/anonymous/?form=URL_COURTE", unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')], verbose_name='URL courte'),
        ),
    ]
