# Generated by Django 4.2.4 on 2023-10-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0025_alter_form_quick_access_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="max_submissions_bypass_authorized",
            field=models.BooleanField(
                default=False,
                verbose_name="Autoriser les utilisateurs avec permission à soumettre des demandes même si le nombre maximal est atteint",
            ),
        ),
    ]
