# Generated by Django 4.2.1 on 2023-08-07 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0023_alter_contacttype_options_and_more"),
        ("forms", "0025_contactformforadminsite"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactTypeForAdminSite",
            fields=[],
            options={
                "verbose_name": "1.9 Type de contact",
                "verbose_name_plural": "1.9 Types de contacts",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("submissions.contacttype",),
        ),
    ]
