# Generated by Django 4.2.4 on 2023-10-05 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0026_form_max_submissions_bypass_authorized"),
    ]

    operations = [
        migrations.RenameField(
            model_name="form",
            old_name="max_submissions_bypass_authorized",
            new_name="max_submissions_bypass_enabled",
        ),
    ]
