# Generated by Django 4.2.4 on 2023-10-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0026_alter_form_quick_access_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="max_submissions_bypass_enabled",
            field=models.BooleanField(
                default=False,
                verbose_name="Autoriser le secrétariat à soumettre des demandes même si le nombre maximal est atteint",
            ),
        ),
    ]
