# Generated by Django 4.2.4 on 2023-10-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0026_alter_form_quick_access_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="api_light",
            field=models.BooleanField(
                default=False,
                help_text="Lorsque cette case est cochée, ce champ est affichée dans la version light de l'api (/rest/RESSOURCE).<br>\n            Afin de ne pas afficher trop d'informations, le champ est masqué pour améliorer la rapidité de l'API.<br>\n            Pour afficher la version normale de l'api, il faut se rendre sur une seule ressource (/rest/RESSOURCE/:ID).",
                verbose_name="Visible dans l'API light",
            ),
        ),
        migrations.AddField(
            model_name="field",
            name="used_as_api_filter",
            field=models.BooleanField(
                default=False,
                help_text="Lorsque cette case est cochée, ce champ peut-être utilisé pour filtrer.<br>\n            Actuellement ne fonctionne que pour les champs à choix simple ou multiples.",
                verbose_name="Filtre pour API",
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="agenda_visible",
            field=models.BooleanField(
                default=False,
                help_text="Lorsque cette case est cochée, le formulaire est lister dans l'api /rest/agenda/",
                verbose_name="Visible dans l'agenda",
            ),
        ),
    ]
