# Generated by Django 4.2.8 on 2024-01-05 14:45

from django.db import migrations, models


def fill_content(apps, schema_editor):
    Field = apps.get_model("forms", "Field")

    for field in Field.objects.all():
        field.content = field.name
        field.save(update_fields=["content"])


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0027_remove_field_is_public_when_permitrequest_is_public_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="disable_validation_by_validators",
            field=models.BooleanField(
                default=False, verbose_name="Désactiver la validation par les services"
            ),
        ),
        migrations.AddField(
            model_name="field",
            name="content",
            field=models.TextField(
                blank=True,
                help_text="Contenu visible lors de la saisie du formulaire",
                verbose_name="contenu",
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="name",
            field=models.CharField(
                help_text="Nom visible que dans l'interface d'administration",
                max_length=255,
                verbose_name="nom",
            ),
        ),
        # Data migration to fill content
        migrations.RunPython(fill_content, reverse_code=migrations.RunPython.noop),
        # Remove the blank=True after data migration
        migrations.AlterField(
            model_name="field",
            name="content",
            field=models.TextField(
                help_text="Contenu visible lors de la saisie du formulaire",
                verbose_name="contenu",
            ),
        ),
    ]
