# Generated by Django 4.2.8 on 2024-01-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0027_remove_field_is_public_when_permitrequest_is_public_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="disable_validation_by_validators",
            field=models.BooleanField(
                default=False, verbose_name="Désactiver la validation par les services"
            ),
        ),
    ]
