# Generated by Django 4.2.4 on 2023-12-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0027_remove_field_is_public_when_permitrequest_is_public_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="agenda_visible",
            field=models.BooleanField(
                default=False,
                help_text="Lorsque cette case est cochée, les données de ce formulaire sont accessibles dans l'API <b>/rest/agenda/ si la demande est rendue publique par le pilote</b><br>\n            Le pilote peut alors contrôler la publication dans l'agenda dans l'onglet traitement",
                verbose_name="Visible dans l'agenda",
            ),
        ),
    ]
