# Generated by Django 4.2.4 on 2023-10-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0027_field_api_light_field_used_as_api_filter_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="field",
            name="is_public_when_permitrequest_is_public",
        ),
        migrations.AddField(
            model_name="field",
            name="public_info",
            field=models.BooleanField(
                default=False,
                help_text="Lorsque cette case est cochée, ce champ ainsi que l'information est affichée si la demande est publique.<br>\n            Actuellement utilisé pour l'application geocalendrier et agenda",
                verbose_name="Information publique",
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="agenda_visible",
            field=models.BooleanField(
                default=False,
                help_text="Lorsque cette case est cochée, les données de ce formulaire sont accessibles dans l'API <b>/rest/agenda/</b>",
                verbose_name="Visible dans l'agenda",
            ),
        ),
    ]
