# Generated by Django 4.2.4 on 2023-09-13 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0028_field_content_field_style_alter_field_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="map_widget_configuration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="map_widget_configuration_field",
                to="forms.mapwidgetconfiguration",
                verbose_name="Configuration de la carte avancée",
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="input_type",
            field=models.CharField(
                choices=[
                    ("address", "Adresse"),
                    ("checkbox", "Case à cocher"),
                    ("list_multiple", "Choix multiple"),
                    ("list_single", "Choix simple"),
                    ("date", "Date"),
                    ("file", "Fichier"),
                    ("file_download", "Fichier (à télécharger)"),
                    ("number", "Nombre"),
                    ("text", "Texte"),
                    ("regex", "Texte (regex)"),
                    ("geom", "Géométrie (points)"),
                    ("text_output", "Texte à afficher"),
                    ("title_output", "Titre à afficher"),
                ],
                max_length=30,
                verbose_name="type de caractéristique",
            ),
        ),
    ]
