# Generated by Django 4.2.9 on 2024-01-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0029_geom_field_input_type_for_form"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="default_validation_text",
            field=models.TextField(
                blank=True, verbose_name="Texte de validation par défaut"
            ),
        ),
    ]
