# Generated by Django 4.2.9 on 2024-01-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0031_alter_field_input_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="maximum_date",
            field=models.DateField(
                blank=True,
                help_text="Format: YYYY-MM-JJ",
                null=True,
                verbose_name="Date maximale",
            ),
        ),
        migrations.AddField(
            model_name="field",
            name="minimum_date",
            field=models.DateField(
                blank=True,
                help_text="Format: YYYY-MM-JJ",
                null=True,
                verbose_name="Date minimale",
            ),
        ),
    ]
