# Generated by Django 4.2.9 on 2024-01-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    def use_new_validation_document_fields(apps, schema_editor):
        Form = apps.get_model("forms", "Form")

        for row in Form.objects.filter(requires_validation_document=False):
            row.validation_document = False
            row.save(update_fields=["validation_document"])

    dependencies = [
        ("forms", "0031_alter_field_input_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="validation_document",
            field=models.BooleanField(
                default=True, verbose_name="Document de validation"
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="validation_document_required_for",
            field=models.IntegerField(
                choices=[(1, "Approbation"), (2, "Refus"), (3, "Approbation et refus")],
                default=1,
                verbose_name="Document de validation obligatoire pour",
            ),
        ),
        migrations.RunPython(use_new_validation_document_fields),
        migrations.RemoveField(
            model_name="form",
            name="requires_validation_document",
        ),
    ]
