# Generated by Django 4.2.9 on 2024-01-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0032_field_maximum_date_field_minimum_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="fees_module_enabled",
            field=models.BooleanField(
                default=False,
                verbose_name="Activer le module de gestion des émoluments",
            ),
        ),
    ]
