# Generated by Django 4.2.9 on 2024-01-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0032_field_maximum_date_field_minimum_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="geo_step_help_text",
            field=models.CharField(
                blank=True,
                help_text="Permet d'être plus explicite sur ce qui est attendu de la personne qui remplit le formulaire.",
                max_length=255,
                verbose_name="Texte facultatif d'aide",
            ),
        ),
    ]
