# Generated by Django 2.1.2 on 2018-11-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitrequest',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='zipcode',
            field=models.PositiveIntegerField(null=True, verbose_name='zipcode'),
        ),
        migrations.AlterField(
            model_name='permitrequest',
            name='address',
            field=models.CharField(max_length=100, null=True, verbose_name='address'),
        ),
    ]
