# Generated by Django 2.1.2 on 2018-12-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpf', '0002_auto_20181130_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128, verbose_name='mail_type')),
                ('recipients', models.CharField(max_length=1024, verbose_name='recipients')),
                ('subject', models.CharField(max_length=128, verbose_name='subject')),
                ('body', models.TextField(verbose_name='body')),
            ],
            options={
                'verbose_name': 'mail',
            },
        ),
    ]
