# Generated by Django 2.1.2 on 2018-12-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpf', '0003_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='type',
            field=models.CharField(max_length=128, unique=True, verbose_name='mail_type'),
        ),
    ]
