# Generated by Django 2.1.2 on 2018-12-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpf', '0004_auto_20181203_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitrequest',
            name='date_request_created',
            field=models.DateField(null=True, verbose_name='date_request_created'),
        ),
    ]
