# Generated by Django 2.1.2 on 2018-12-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpf', '0005_permitrequest_date_request_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permitrequest',
            name='date_effective_end',
            field=models.DateField(blank=True, null=True, verbose_name='date_effective_end'),
        ),
    ]
