# Generated by Django 2.1.2 on 2018-12-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpf', '0007_auto_20181204_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validation',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
    ]
