# Generated by Django 2.1.2 on 2018-12-04 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpf', '0008_auto_20181204_1031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permitrequest',
            options={'permissions': (('change_amount', 'Can change amount'), ('change_paid', 'Can change paid'), ('change_geom', 'Can change geom'), ('change_validated', 'Can change validated'), ('change_sent', 'Can change sent'), ('change_ended', 'Can change ended'), ('change_date_effective_end', 'Can change date_effective_end'), ('change_has_existing_archeology', 'Can change has_existing_archeology')), 'verbose_name': 'permitrequest'},
        ),
    ]
