# Generated by Django 2.1.2 on 2018-12-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpf', '0009_auto_20181204_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='vat_number',
            field=models.CharField(max_length=100, null=True, verbose_name='vat_number'),
        ),
    ]
