# Generated by Django 2.1.2 on 2018-12-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpf', '0010_actor_vat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='vat_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='vat_number'),
        ),
    ]
