# Generated by Django 2.1.2 on 2018-12-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpf', '0011_auto_20181206_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='vat_number',
            field=models.CharField(max_length=100, null=True, verbose_name='vat_number'),
        ),
    ]
