# Generated by Django 2.1.2 on 2018-12-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpf', '0012_auto_20181206_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitrequest',
            name='date_last_printed',
            field=models.DateField(blank=True, null=True, verbose_name='date_last_printed'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='report_filename',
            field=models.CharField(max_length=254, null=True, verbose_name='report_filename'),
        ),
    ]
