# Generated by Django 2.1.2 on 2018-12-13 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpf', '0013_auto_20181207_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='phone_fixed',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Seuls les chiffres et les espaces sont autorisés', regex='^(\\s*[0-9]+\\s*)+$')], verbose_name='phone_fixed'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='phone_mobile',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Seuls les chiffres et les espaces sont autorisés', regex='^(\\s*[0-9]+\\s*)+$')], verbose_name='phone_mobile'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='vat_number',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.RegexValidator(message="Le code d'entreprise doit être de type CHE-123.456.789 et vous pouvez le trouver sur                 le registe fédéral des entreprises                 https://www.uid.admin.ch/search.aspx", regex='([CHE-])+\\d{3}[.]+\\d{3}[.]+\\d{3}')], verbose_name='vat_number'),
        ),
    ]
