# Generated by Django 2.1.2 on 2019-02-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpf', '0014_auto_20181213_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permitrequest',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=2, verbose_name='length'),
        ),
        migrations.AlterField(
            model_name='permitrequest',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=2, verbose_name='with'),
        ),
    ]
