# Generated by Django 2.1.2 on 2019-02-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpf', '0015_auto_20190205_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permitrequest',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='length'),
        ),
        migrations.AlterField(
            model_name='permitrequest',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='with'),
        ),
    ]
