# Generated by Django 2.1.2 on 2019-02-06 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpf', '0016_auto_20190205_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='email_content',
        ),
    ]
