# Generated by Django 2.2 on 2019-05-15 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpf', '0019_auto_20190515_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitrequest',
            name='archeology_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gpf.ArcheoStatus', verbose_name='archeostatus'),
        ),
        migrations.AlterField(
            model_name='permitrequest',
            name='has_archeology',
            field=models.BooleanField(default=False, verbose_name='has_archeology'),
        ),
    ]
