# Generated by Django 2.2.6 on 2019-11-13 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpf', '0021_auto_20191024_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permitrequest',
            options={'ordering': ['-id'], 'permissions': (('change_amount', 'Can change amount'), ('change_paid', 'Can change paid'), ('change_geom', 'Can change geom'), ('change_validated', 'Can change validated'), ('change_sent', 'Can change sent'), ('change_ended', 'Can change ended'), ('change_date_effective_end', 'Can change date_effective_end'), ('change_archeotype', 'Can change archeotype'), ('date_start', 'Can change date_start')), 'verbose_name': 'permitrequest'},
        ),
    ]
