# Generated by Django 2.2.6 on 2019-11-14 13:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpf', '0022_auto_20191113_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='description')),
                ('ofs_id', models.PositiveIntegerField(verbose_name='ofs_id')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=2056, verbose_name='geom')),
            ],
            options={
                'verbose_name': 'administrative_entity',
            },
        ),
        migrations.CreateModel(
            name='ValidationCommentSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_sample', models.TextField(blank=True, null=True, verbose_name='comment_sample')),
            ],
            options={
                'verbose_name': 'validation_comment_sample',
            },
        ),
    ]
