# Generated by Django 2.2.6 on 2019-11-14 13:45

from django.db import migrations

def create_adminitrative_entity(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    AdministrativeEntity = apps.get_model('gpf', 'AdministrativeEntity')

    if len(AdministrativeEntity.objects.all()) == 0:
        print('creating default adminsitrative entity...')
        instance = AdministrativeEntity()
        instance.name = 'Demo Administrative Entity'
        instance.ofs_id = '1234'
        instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gpf', '0023_administrativeentity_validationcommentsample'),
    ]

    operations = [
        migrations.RunPython(create_adminitrative_entity),
    ]
