# Generated by Django 2.2.6 on 2019-11-14 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpf', '0024_auto_create_sample_administrative_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='administrative_entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_administrative_entity', to='gpf.AdministrativeEntity', verbose_name='administrative_entity'),
        ),
        migrations.AddField(
            model_name='mail',
            name='administrative_entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mail_administrative_entity', to='gpf.AdministrativeEntity', verbose_name='administrative_entity'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='administrative_entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permitrequest_administrative_entity', to='gpf.AdministrativeEntity', verbose_name='administrative_entity'),
        ),
        migrations.AddField(
            model_name='validationcommentsample',
            name='administrative_entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validationcommentsample_administrative_entity', to='gpf.AdministrativeEntity', verbose_name='administrative_entity'),
        ),
    ]
