# Generated by Django 2.2.6 on 2019-11-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpf', '0025_auto_20191114_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativeentity',
            name='name',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
    ]
