# Generated by Django 2.2.6 on 2019-11-14 14:22

from django.db import migrations

def set_administrative_entity(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    AdministrativeEntity = apps.get_model('gpf', 'AdministrativeEntity')
    admin_instance = AdministrativeEntity.objects.all().first()

    Mail = apps.get_model('gpf', 'Mail')
    ValidationCommentSample = apps.get_model('gpf', 'ValidationCommentSample')
    PermitRequest = apps.get_model('gpf', 'PermitRequest')
    Department = apps.get_model('gpf', 'Department')

    for mail in Mail.objects.all():
        mail.administrative_entity = admin_instance
        mail.save()

    for validcomment in ValidationCommentSample.objects.all():
        validcomment.administrative_entity = admin_instance
        validcomment.save()

    for permit in PermitRequest.objects.all():
        print('ici')
        print(admin_instance)
        permit.administrative_entity = admin_instance
        permit.save()

    for department in Department.objects.all():
        department.administrative_entity = admin_instance
        department.save()

class Migration(migrations.Migration):

    dependencies = [
        ('gpf', '0026_auto_20191114_1422'),
    ]

    operations = [
        migrations.RunPython(set_administrative_entity),
    ]
