# Generated by Django 2.2.6 on 2019-11-15 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpf', '0028_auto_20191115_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validationcommentsample',
            name='administrative_entity',
        ),
        migrations.AddField(
            model_name='validationcommentsample',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gpf.Department'),
        ),
    ]
