# Generated by Django 2.2.6 on 2020-05-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpf', '0030_administrative_entity_department_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_default_validator',
            field=models.BooleanField(default=False, verbose_name='sélectionné par défaut pour les validations'),
        ),
    ]
