# Generated by Django 2.2.6 on 2020-05-19 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpf', '0031_default_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativeentity',
            name='image_signature_1',
            field=models.FileField(blank=True, upload_to='administrative_entity_customization/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])], verbose_name='Scan signature gauche'),
        ),
        migrations.AddField(
            model_name='administrativeentity',
            name='image_signature_2',
            field=models.FileField(blank=True, upload_to='administrative_entity_customization/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])], verbose_name='Scan signature droite'),
        ),
        migrations.AddField(
            model_name='administrativeentity',
            name='legal_document',
            field=models.FileField(blank=True, upload_to='administrative_entity_customization/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Directive'),
        ),
        migrations.AddField(
            model_name='administrativeentity',
            name='link',
            field=models.URLField(blank=True, verbose_name='Lien'),
        ),
        migrations.AddField(
            model_name='administrativeentity',
            name='logo_main',
            field=models.FileField(blank=True, upload_to='administrative_entity_customization/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])], verbose_name='Logo principal'),
        ),
        migrations.AddField(
            model_name='administrativeentity',
            name='logo_secondary',
            field=models.FileField(blank=True, upload_to='administrative_entity_customization/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])], verbose_name='Logo secondaire'),
        ),
        migrations.AddField(
            model_name='administrativeentity',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Seuls les chiffres et les espaces sont autorisés', regex='^(\\s*[0-9]+\\s*)+$')], verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='administrativeentity',
            name='title_signature_1',
            field=models.CharField(blank=True, max_length=128, verbose_name='Signature Gauche'),
        ),
        migrations.AddField(
            model_name='administrativeentity',
            name='title_signature_2',
            field=models.CharField(blank=True, max_length=128, verbose_name='Signature Droite'),
        ),
    ]
