# Generated by Django 2.2.6 on 2020-06-05 08:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpf', '0032_auto_20200519_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='address',
            field=models.CharField(default='Inconnu', max_length=100, verbose_name='address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actor',
            name='city',
            field=models.CharField(default='Inconnu', max_length=100, verbose_name='city'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actor',
            name='company_name',
            field=models.CharField(blank=True, default='Inconnu', max_length=100, verbose_name='company_name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actor',
            name='email',
            field=models.EmailField(default='Inconnu@inconnu.inconnu', max_length=254, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actor',
            name='firstname',
            field=models.CharField(default='Inconnu', max_length=100, verbose_name='firstname'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(default='Inconnu', max_length=100, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actor',
            name='phone_fixed',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Seuls les chiffres et les espaces sont autorisés', regex='^(\\s*[0-9]+\\s*)+$')], verbose_name='Téléphone principal'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='phone_mobile',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Seuls les chiffres et les espaces sont autorisés', regex='^(\\s*[0-9]+\\s*)+$')], verbose_name='Téléphone secondaire'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='vat_number',
            field=models.CharField(blank=True, default='CHE-123.123.123', max_length=100, validators=[django.core.validators.RegexValidator(message="Le code d'entreprise doit être de type CHE-123.456.789 et vous pouvez le trouver sur                 le registe fédéral des entreprises                 https://www.uid.admin.ch/search.aspx", regex='([CHE-])+\\d{3}[.]+\\d{3}[.]+\\d{3}')], verbose_name='vat_number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actor',
            name='zipcode',
            field=models.PositiveIntegerField(default=1234, verbose_name='zipcode'),
            preserve_default=False,
        ),
    ]
