# Generated by Django 3.2.15 on 2022-11-16 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_migrate_permits_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="administrativeentity",
            options={
                "permissions": [
                    ("see_private_requests", "Voir les demandes restreintes")
                ]
            },
        ),
    ]
