# Generated by Django 4.1 on 2022-11-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("accounts", "0004_adapt_models_for_new_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administrativeentity",
            name="sites",
            field=models.ManyToManyField(
                related_name="+", to="sites.site", verbose_name="Détails du Site"
            ),
        ),
    ]
