# Generated by Django 4.1 on 2022-12-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_administrativeentity_sites"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permitdepartment",
            name="mandatory_2fa",
            field=models.BooleanField(
                default=True,
                help_text="Cocher si les membres doivent obligatoirement utiliser la double authentification",
                verbose_name="2FA obligatoire",
            ),
        ),
    ]
