# Generated by Django 4.1 on 2022-12-12 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_administrativeentity_is_single_form_permits"),
        ("accounts", "0006_alter_historicaluserprofile_options_and_more"),
    ]

    operations = []
