# Generated by Django 4.1.4 on 2022-12-22 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("accounts", "0006_alter_historicaluserprofile_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administrativeentity",
            name="integrator",
            field=models.ForeignKey(
                limit_choices_to={"permit_department__is_integrator_admin": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="auth.group",
                verbose_name="Groupe des administrateurs",
            ),
        ),
        migrations.AlterField(
            model_name="siteprofile",
            name="integrator",
            field=models.ForeignKey(
                default=None,
                limit_choices_to={"permit_department__is_integrator_admin": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="site_profiles",
                to="auth.group",
                verbose_name="Intégrateur",
            ),
        ),
    ]
