# Generated by Django 4.1 on 2022-12-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_merge_20221212_1053"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicaluserprofile",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical 3.2 Consultation de l'auteur",
            },
        ),
        migrations.AlterField(
            model_name="historicaluserprofile",
            name="history_date",
            field=models.DateTimeField(),
        ),
    ]
