# Generated by Django 4.1.4 on 2023-01-19 09:59

import django.db.models.deletion
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension
from django.db import migrations, models

from geocity import settings


def create_web_site(apps, schema_editor):

    Site = apps.get_model("sites", "Site")

    Site.objects.update_or_create(domain="web", name="web (internal calls)")


def update_site_data(apps, schema_editor):
    """
    Create default Site
    Fill SiteProfile data of Site
    Add default site to each PermitAdministrativeEntity
    """
    Site = apps.get_model("sites", "Site")
    SiteProfile = apps.get_model("accounts", "SiteProfile")
    PermitAdministrativeEntity = apps.get_model("accounts", "AdministrativeEntity")

    if not Site.objects.filter(domain=settings.DEFAULT_SITE).exists():
        Site.objects.get_or_create(domain=settings.DEFAULT_SITE, name="default site")

    default_site = Site.objects.get(domain=settings.DEFAULT_SITE)

    for entity in PermitAdministrativeEntity.objects.all():
        entity.sites.add(default_site)

    for site_obj in Site.objects.all():
        SiteProfile.objects.get_or_create(
            site=site_obj,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("accounts", "0007_merge_20221212_1053"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administrativeentity",
            name="integrator",
            field=models.ForeignKey(
                limit_choices_to={"permit_department__is_integrator_admin": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="auth.group",
                verbose_name="Groupe des administrateurs",
            ),
        ),
        migrations.AlterField(
            model_name="siteprofile",
            name="integrator",
            field=models.ForeignKey(
                default=None,
                limit_choices_to={"permit_department__is_integrator_admin": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="site_profiles",
                to="auth.group",
                verbose_name="Intégrateur",
            ),
        ),
        migrations.RunPython(update_site_data),
        migrations.RunPython(create_web_site),
        TrigramExtension(),
        UnaccentExtension(),
    ]
