# Generated by Django 4.1.4 on 2023-01-10 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_merge_20221212_1053"),
        ("accounts", "0008_alter_administrativeentity_integrator_and_more"),
    ]

    operations = []
