# Generated by Django 4.1.7 on 2023-02-21 12:13

import django.core.validators
from django.db import migrations, models
import geocity.apps.accounts.fields
import geocity.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_siteprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativeentity',
            name='additional_information',
            field=models.TextField(blank=True, verbose_name='autre information'),
        ),
        migrations.AddField(
            model_name='administrativeentity',
            name='directive',
            field=geocity.apps.accounts.fields.AdministrativeEntityFileField(blank=True, storage=geocity.fields.PrivateFileSystemStorage(), upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='directive'),
        ),
        migrations.AddField(
            model_name='administrativeentity',
            name='directive_description',
            field=models.CharField(blank=True, max_length=200, verbose_name='description de la directive'),
        ),
    ]
