# Generated by Django 4.1.4 on 2023-01-18 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_post_update_after_permits_app_deletion"),
        ("accounts", "0009_merge_20230110_0919"),
    ]

    operations = []
