# Generated by Django 4.1.4 on 2023-01-26 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_enabled_advanced_site_customization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='custom_template',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.templatecustomization', verbose_name='Personalisation du site'),
        ),
    ]
