# Generated by Django 4.1.7 on 2023-02-22 06:27

import django.core.validators
from django.db import migrations, models
import geocity.apps.accounts.fields
import geocity.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_legal_infos_at_entity_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativeentity',
            name='signature_sheet',
            field=geocity.apps.accounts.fields.AdministrativeEntityFileField(blank=True, storage=geocity.fields.PrivateFileSystemStorage(), upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Volet de transmission'),
        ),
        migrations.AddField(
            model_name='administrativeentity',
            name='signature_sheet_description',
            field=models.TextField(blank=True, verbose_name='Texte explicatif relatif au volet de transmission'),
        ),
    ]
