# Generated by Django 4.1.7 on 2023-04-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("accounts", "0011_add_signature_sheet_to_administrative_entity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administrativeentity",
            name="sites",
            field=models.ManyToManyField(
                related_name="administrative_entity",
                to="sites.site",
                verbose_name="Détails du Site",
            ),
        ),
    ]
