# Generated by Django 4.1.7 on 2023-03-10 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0018_add_fields_for_new_map_widget"),
        ("accounts", "0011_add_signature_sheet_to_administrative_entity"),
    ]

    operations = [
        migrations.AddField(
            model_name="administrativeentity",
            name="map_widget_configuration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="forms.mapwidgetconfiguration",
                verbose_name="Configuration de la carte avancée",
            ),
        ),
    ]
