# Generated by Django 4.1.7 on 2023-05-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_administrativeentity_sites"),
    ]

    operations = [
        migrations.AddField(
            model_name="permitdepartment",
            name="generic_email",
            field=models.CharField(
                blank=True,
                help_text="Email générique pour tous les membres du groupe",
                max_length=254,
                verbose_name="Email générique",
            ),
        ),
        migrations.AddField(
            model_name="permitdepartment",
            name="uses_generic_email",
            field=models.BooleanField(
                default=False,
                help_text="Cocher si une adresse email générique doit être utilisée au lieu de l'adresse personnelle",
                verbose_name="Ne notifier qu'une adresse email générique",
            ),
        ),
    ]
