# Generated by Django 4.1.7 on 2023-05-03 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0019_map_widget_configuration'),
        ('accounts', '0012_alter_administrativeentity_sites'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativeentity',
            name='map_widget_configuration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map_widget_configuration_administrative_entity', to='forms.mapwidgetconfiguration', verbose_name='Configuration de la carte avancée'),
        ),
    ]
