# Generated by Django 4.2 on 2023-05-17 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0020_map_widget_configuration"),
        ("accounts", "0013_permitdepartment_generic_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="administrativeentity",
            name="map_widget_configuration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="map_widget_configuration_administrative_entity",
                to="forms.mapwidgetconfiguration",
                verbose_name="Configuration de la carte avancée",
            ),
        ),
    ]
