# Generated by Django 4.2.4 on 2023-08-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_permitdepartment_generic_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administrativeentity",
            name="is_single_form_submissions",
            field=models.BooleanField(
                default=True,
                help_text="Nécessaire pour l'utilisation du système de paiement en ligne",
                verbose_name="Autoriser uniquement un objet par demande",
            ),
        ),
    ]
