# Generated by Django 4.2.4 on 2023-08-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_alter_administrativeentity_is_single_form_submissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permitdepartment",
            name="shortname",
            field=models.CharField(
                blank=True,
                help_text="Nom affiché par défaut dans les différentes étapes du formulaire, ne s'affiche pas dans l'admin (max. 100 caractères)",
                max_length=100,
                verbose_name="nom court",
            ),
        ),
    ]
