# Generated by Django 4.2.4 on 2023-10-02 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0014_alter_administrativeentity_is_single_form_submissions_and_permitdepartment_shortname",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="administrativeentity",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Seuls les chiffres et les espaces sont autorisés.",
                        regex="^((\\+|00)\\d{1,3}\\s?)?(\\d{2})\\s?(\\d{3})\\s?(\\d{2})\\s?(\\d{2})$",
                    )
                ],
                verbose_name="Téléphone",
            ),
        ),
        migrations.AlterField(
            model_name="historicaluserprofile",
            name="phone_first",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Seuls les chiffres et les espaces sont autorisés.",
                        regex="^((\\+|00)\\d{1,3}\\s?)?(\\d{2})\\s?(\\d{3})\\s?(\\d{2})\\s?(\\d{2})$",
                    )
                ],
                verbose_name="Téléphone principal",
            ),
        ),
        migrations.AlterField(
            model_name="historicaluserprofile",
            name="phone_second",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Seuls les chiffres et les espaces sont autorisés.",
                        regex="^((\\+|00)\\d{1,3}\\s?)?(\\d{2})\\s?(\\d{3})\\s?(\\d{2})\\s?(\\d{2})$",
                    )
                ],
                verbose_name="Téléphone secondaire",
            ),
        ),
        migrations.AlterField(
            model_name="historicaluserprofile",
            name="zipcode",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(99999),
                ],
                verbose_name="NPA",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_first",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Seuls les chiffres et les espaces sont autorisés.",
                        regex="^((\\+|00)\\d{1,3}\\s?)?(\\d{2})\\s?(\\d{3})\\s?(\\d{2})\\s?(\\d{2})$",
                    )
                ],
                verbose_name="Téléphone principal",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_second",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Seuls les chiffres et les espaces sont autorisés.",
                        regex="^((\\+|00)\\d{1,3}\\s?)?(\\d{2})\\s?(\\d{3})\\s?(\\d{2})\\s?(\\d{2})$",
                    )
                ],
                verbose_name="Téléphone secondaire",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="zipcode",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(99999),
                ],
                verbose_name="NPA",
            ),
        ),
    ]
