# Generated by Django 4.2.4 on 2023-11-16 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        (
            "accounts",
            "0014_alter_administrativeentity_is_single_form_submissions_and_permitdepartment_shortname",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteprofile",
            name="integrator",
            field=models.ForeignKey(
                default=None,
                limit_choices_to={"permit_department__is_integrator_admin": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="site_profiles",
                to="auth.group",
                verbose_name="Groupe des administrateurs",
            ),
        ),
    ]
