# Generated by Django 4.2.9 on 2024-01-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_alter_siteprofile_integrator"),
    ]

    operations = [
        migrations.AddField(
            model_name="administrativeentity",
            name="services_fees_hourly_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Tarif horaire des prestations de l'entité administrative",
                max_digits=12,
                verbose_name="Tarif horaire",
            ),
        ),
    ]
