# Generated by Django 4.2.9 on 2024-02-13 10:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_alter_siteprofile_integrator"),
    ]

    operations = [
        migrations.AddField(
            model_name="administrativeentity",
            name="reply_to_email",
            field=models.CharField(
                blank=True,
                help_text="Permet de définir une adresse email de réponse autre que celle de l'expéditeur des notifications",
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Le format de l'adresse email n'est pas valable.",
                        regex="^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,63}$",
                    )
                ],
                verbose_name="Adresse email de réponse",
            ),
        ),
    ]
