# Generated by Django 2.2.6 on 2020-01-07 08:39

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermitRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Brouillon'), (1, 'Envoyée'), (2, 'Validée')], default=0, verbose_name='état')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='date de création')),
                ('validated_at', models.DateTimeField(null=True, verbose_name='date de validation')),
            ],
            options={
                'verbose_name': 'demande de permis',
                'verbose_name_plural': 'demandes de permis',
            },
        ),
        migrations.CreateModel(
            name='WorksObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'objet des travaux',
                'verbose_name_plural': 'objets des travaux',
            },
        ),
        migrations.CreateModel(
            name='WorksObjectProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('input_type', models.CharField(choices=[('text', 'Texte'), ('checkbox', 'Case à cocher'), ('number', 'Nombre'), ('file', 'Fichier')], max_length=30, verbose_name='type de caractéristique')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='obligatoire')),
            ],
            options={
                'verbose_name': 'caractéristique',
                'verbose_name_plural': 'caractéristiques',
            },
        ),
        migrations.CreateModel(
            name='WorksObjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('works_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permits.WorksObject')),
            ],
        ),
        migrations.CreateModel(
            name='WorksType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'type de travaux',
                'verbose_name_plural': 'types de travaux',
            },
        ),
        migrations.CreateModel(
            name='WorksObjectTypeChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permits.PermitRequest')),
                ('works_object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permits.WorksObjectType')),
            ],
        ),
        migrations.AddField(
            model_name='worksobjecttype',
            name='works_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permits.WorksType'),
        ),
        migrations.CreateModel(
            name='WorksObjectPropertyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', django.contrib.postgres.fields.jsonb.JSONField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='permits.WorksObjectProperty', verbose_name='caractéristique')),
                ('works_object_type_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='permits.WorksObjectTypeChoice', verbose_name='objet des travaux')),
            ],
        ),
        migrations.AddField(
            model_name='worksobjectproperty',
            name='works_objects_types',
            field=models.ManyToManyField(to='permits.WorksObjectType', verbose_name='objets des travaux'),
        ),
        migrations.AddField(
            model_name='worksobject',
            name='works_types',
            field=models.ManyToManyField(through='permits.WorksObjectType', to='permits.WorksType', verbose_name='types de travaux'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='works_objects_types',
            field=models.ManyToManyField(through='permits.WorksObjectTypeChoice', to='permits.WorksObjectType'),
        ),
    ]
