# Generated by Django 2.2.6 on 2020-01-16 08:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gpf', '0029_auto_20191115_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermitRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Brouillon'), (1, 'Envoyée'), (2, 'Validée')], default=0, verbose_name='état')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de création')),
                ('validated_at', models.DateTimeField(null=True, verbose_name='date de validation')),
                ('administrative_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permit_requests', to='gpf.AdministrativeEntity', verbose_name='commune')),
            ],
            options={
                'verbose_name': 'demande de permis',
                'verbose_name_plural': 'demandes de permis',
            },
        ),
        migrations.CreateModel(
            name='WorksObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'objet des travaux',
                'verbose_name_plural': 'objets des travaux',
            },
        ),
        migrations.CreateModel(
            name='WorksObjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrative_entities', models.ManyToManyField(related_name='works_object_types', to='gpf.AdministrativeEntity', verbose_name='communes')),
                ('works_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works_object_types', to='permits.WorksObject', verbose_name='objet des travaux')),
            ],
            options={
                'verbose_name': 'objet pour types de travaux',
                'verbose_name_plural': 'objets pour types de travaux',
            },
        ),
        migrations.CreateModel(
            name='WorksType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'type de travaux',
                'verbose_name_plural': 'types de travaux',
            },
        ),
        migrations.CreateModel(
            name='WorksObjectTypeChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permits.PermitRequest')),
                ('works_object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permits.WorksObjectType')),
            ],
            options={
                'unique_together': {('permit_request', 'works_object_type')},
            },
        ),
        migrations.AddField(
            model_name='worksobjecttype',
            name='works_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works_object_types', to='permits.WorksType', verbose_name='type de travaux'),
        ),
        migrations.CreateModel(
            name='WorksObjectProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('input_type', models.CharField(choices=[('text', 'Texte'), ('checkbox', 'Case à cocher'), ('number', 'Nombre'), ('file', 'Fichier')], max_length=30, verbose_name='type de caractéristique')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='obligatoire')),
                ('works_object_types', models.ManyToManyField(related_name='properties', to='permits.WorksObjectType', verbose_name='objets des travaux')),
            ],
            options={
                'verbose_name': 'caractéristique',
                'verbose_name_plural': 'caractéristiques',
            },
        ),
        migrations.AddField(
            model_name='worksobject',
            name='works_types',
            field=models.ManyToManyField(related_name='works_objects', through='permits.WorksObjectType', to='permits.WorksType', verbose_name='types de travaux'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='works_object_types',
            field=models.ManyToManyField(related_name='permit_requests', through='permits.WorksObjectTypeChoice', to='permits.WorksObjectType'),
        ),
        migrations.AlterUniqueTogether(
            name='worksobjecttype',
            unique_together={('works_type', 'works_object')},
        ),
        migrations.CreateModel(
            name='WorksObjectPropertyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', django.contrib.postgres.fields.jsonb.JSONField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='permits.WorksObjectProperty', verbose_name='caractéristique')),
                ('works_object_type_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='permits.WorksObjectTypeChoice', verbose_name='objet des travaux')),
            ],
            options={
                'unique_together': {('property', 'works_object_type_choice')},
            },
        ),
    ]
