# Generated by Django 2.2.6 on 2020-06-09 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitrequestvalidation',
            name='validated_at',
            field=models.DateTimeField(null=True, verbose_name='Validé le'),
        ),
        migrations.AddField(
            model_name='permitrequestvalidation',
            name='validated_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
