# Generated by Django 2.2.6 on 2020-06-12 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permitauthor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='permitauthor',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='permitauthor',
            name='name',
        ),
        migrations.AlterField(
            model_name='permitauthor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
