# Generated by Django 2.2.6 on 2020-01-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worksobjecttype',
            options={'verbose_name': 'objet pour types de travaux', 'verbose_name_plural': 'objets pour types de travaux'},
        ),
        migrations.AlterField(
            model_name='worksobject',
            name='works_types',
            field=models.ManyToManyField(related_name='works_objects', through='permits.WorksObjectType', to='permits.WorksType', verbose_name='types de travaux'),
        ),
        migrations.AlterField(
            model_name='worksobjectproperty',
            name='works_objects_types',
            field=models.ManyToManyField(related_name='properties', to='permits.WorksObjectType', verbose_name='objets des travaux'),
        ),
        migrations.AlterUniqueTogether(
            name='worksobjectpropertyvalue',
            unique_together={('property', 'works_object_type_choice')},
        ),
        migrations.AlterUniqueTogether(
            name='worksobjecttype',
            unique_together={('works_type', 'works_object')},
        ),
        migrations.AlterUniqueTogether(
            name='worksobjecttypechoice',
            unique_together={('permit_request', 'works_object_type')},
        ),
    ]
