# Generated by Django 2.2.6 on 2020-06-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permitactortype',
            options={'verbose_name': 'Configuration du contact à saisir', 'verbose_name_plural': 'Configuration des contacts à saisir'},
        ),
        migrations.AlterModelOptions(
            name='permitadministrativeentity',
            options={'verbose_name': "Configuration de l'entité administrative (commune, organisation)", 'verbose_name_plural': "Configuration de l'entité administrative (commune, organisation)"},
        ),
        migrations.AlterModelOptions(
            name='permitauthor',
            options={'verbose_name': 'Auteur'},
        ),
        migrations.AlterModelOptions(
            name='permitdepartment',
            options={'verbose_name': 'Configuration du service', 'verbose_name_plural': 'Configuration des services'},
        ),
        migrations.AlterModelOptions(
            name='permitrequestactor',
            options={'verbose_name': 'Relation permis-contact', 'verbose_name_plural': 'Relations permis-contact'},
        ),
        migrations.AlterModelOptions(
            name='permitrequestgeotime',
            options={'verbose_name': 'Agenda et localsation'},
        ),
        migrations.AlterModelOptions(
            name='permitrequestvalidation',
            options={'verbose_name': 'Validation par le service', 'verbose_name_plural': 'Validations par les services'},
        ),
        migrations.AlterModelOptions(
            name='worksobject',
            options={'verbose_name': "Configuration de l'objet des travaux", 'verbose_name_plural': 'Configuration des objets des travaux'},
        ),
        migrations.AlterModelOptions(
            name='worksobjectproperty',
            options={'verbose_name': 'Configuration de la caractéristique', 'verbose_name_plural': 'Configuration des caractéristiques'},
        ),
        migrations.AlterModelOptions(
            name='worksobjecttype',
            options={'verbose_name': 'Configuration type-objet-entité administrative', 'verbose_name_plural': 'Configurations type-objet-entité administrative'},
        ),
        migrations.AlterModelOptions(
            name='workstype',
            options={'verbose_name': 'Configuration du type de travaux', 'verbose_name_plural': 'Configuration types de travaux'},
        ),
        migrations.AddField(
            model_name='permitadministrativeentity',
            name='archive_link',
            field=models.URLField(blank=True, max_length=1024, verbose_name='Archives externes'),
        ),
        migrations.AlterField(
            model_name='worksobjecttype',
            name='administrative_entities',
            field=models.ManyToManyField(related_name='works_object_types', to='permits.PermitAdministrativeEntity', verbose_name='Entités administratives'),
        ),
    ]
