# Generated by Django 2.2.13 on 2020-09-25 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermitWorkFlowStatusChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Brouillon'), (1, 'Envoyée, en attente de traitement'), (4, 'Demande de compléments'), (3, 'En traitement'), (5, 'En validation'), (2, 'Approuvée'), (6, 'Refusée'), (7, 'Annonce réceptionnée')], verbose_name='statut')),
            ],
        ),
        migrations.AlterField(
            model_name='permitrequest',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Brouillon'), (1, 'Envoyée, en attente de traitement'), (4, 'Demande de compléments'), (3, 'En traitement'), (5, 'En validation'), (2, 'Approuvée'), (6, 'Refusée'), (7, 'Annonce réceptionnée')], default=0, verbose_name='état'),
        ),
        migrations.CreateModel(
            name='PermitWorkFlowStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrative_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permits.PermitAdministrativeEntity')),
                ('status_choices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permits.PermitWorkFlowStatusChoices')),
            ],
            options={
                'verbose_name': '1.7 Configuration du statut',
                'verbose_name_plural': '1.7 Configuration des statuts',
            },
        ),
        migrations.AddField(
            model_name='permitadministrativeentity',
            name='enabled_status',
            field=models.ManyToManyField(related_name='permit_workflow_status', to='permits.PermitWorkFlowStatus', verbose_name='Statuts actifs'),
        ),
    ]
