# Generated by Django 2.2.6 on 2020-01-16 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpf', '0029_auto_20191115_0801'),
        ('permits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitrequest',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permit_requests', to='gpf.Actor', verbose_name='auteur'),
        ),
    ]
