# Generated by Django 2.2.13 on 2020-08-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstype',
            name='meta_type',
            field=models.IntegerField(choices=[(0, 'Autres'), (1, 'Chantier'), (2, 'Construction'), (3, 'Événement sportif'), (4, 'Événement culturel'), (5, 'Événement commercial'), (6, 'Dispositif de police')], default=0, verbose_name='Type générique'),
        ),
    ]
