# Generated by Django 2.2.6 on 2020-06-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0002_remove_duplicate_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitrequest',
            name='creditor_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Autres'), (2, 'Popriétaire'), (3, 'Entreprise'), (4, "Maître d'ouvrage"), (1, "Requérant si différent de l'auteur de la demande"), (5, 'Sécurité'), (6, 'Association')], default=0, verbose_name='Destinaire de la facture'),
        ),
    ]
