# Generated by Django 2.2.6 on 2020-06-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0002_auto_20200623_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permitrequest',
            name='creditor_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Autres'), (2, 'Popriétaire'), (3, 'Entreprise'), (4, "Maître d'ouvrage"), (1, "Requérant si différent de l'auteur de la demande"), (5, 'Sécurité'), (6, 'Association')], null=True, verbose_name='Destinaire de la facture'),
        ),
    ]
