# Generated by Django 2.2.6 on 2020-06-10 11:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0002_validating_user_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeomLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_name', models.CharField(blank=True, max_length=128, verbose_name='CoucheW')),
                ('description', models.CharField(blank=True, max_length=1024, verbose_name='Commentaire')),
                ('source_id', models.CharField(blank=True, max_length=128, verbose_name='Id entité')),
                ('source_subid', models.CharField(blank=True, max_length=128, verbose_name='Id entité secondaire')),
                ('external_link', models.URLField(blank=True, verbose_name='Lien externe')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=2056, verbose_name='Géométrie')),
            ],
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='archeology_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inconnu'), (1, 'Pas fouillé'), (2, 'Partiellement fouillé'), (2, 'Déjà fouillé')], default=0, verbose_name='Status archéologique'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='intersected_geometries',
            field=models.CharField(max_length=1024, null=True, verbose_name='Entités géométriques concernées'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Payé'),
        ),
    ]
