# Generated by Django 2.2.6 on 2020-01-14 10:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0002_unicity_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permitrequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de création'),
        ),
        migrations.AlterField(
            model_name='permitrequest',
            name='works_object_types',
            field=models.ManyToManyField(related_name='permit_requests', through='permits.WorksObjectTypeChoice', to='permits.WorksObjectType'),
        ),
        migrations.AlterField(
            model_name='worksobjecttype',
            name='works_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works_object_types', to='permits.WorksObject', verbose_name='objet des travaux'),
        ),
        migrations.AlterField(
            model_name='worksobjecttype',
            name='works_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works_object_types', to='permits.WorksType', verbose_name='type de travaux'),
        ),
    ]
