# Generated by Django 2.2.13 on 2020-08-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0002_workstype_meta_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitrequest',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Public'),
        ),
    ]
