# Generated by Django 2.2.13 on 2020-11-02 14:10

from django.db import migrations
from permits import models as permitmodels


def insert_workflow_status(apps, schema_editor):
    """
    Insert values in PermitWorkflowStatus model from models.PermitRequest.STATUS_CHOICES values
    """
    for status_value in permitmodels.PermitRequest.STATUS_CHOICES:
        for entity in permitmodels.PermitAdministrativeEntity.objects.all():
            permitmodels.PermitWorkflowStatus.objects.get_or_create(
                    status=status_value[0],
                    administrative_entity=entity)


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0003_permitworkflowstatus'),
    ]

    operations = [
        migrations.RunPython(insert_workflow_status),
    ]
