# Generated by Django 2.2.6 on 2020-01-29 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0003_add_actors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permitrequest',
            name='actors',
        ),
        migrations.AlterField(
            model_name='worksobjecttypechoice',
            name='permit_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='permits.PermitRequest'),
        ),
        migrations.AlterField(
            model_name='worksobjecttypechoice',
            name='works_object_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='permits.WorksObjectType'),
        ),
    ]
