# Generated by Django 2.2.6 on 2020-03-16 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpf', '0029_auto_20191115_0801'),
        ('permits', '0003_add_actors'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermitRequestActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpf.Actor')),
            ],
        ),
        migrations.RemoveField(
            model_name='permitrequest',
            name='actors',
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='actors',
            field=models.ManyToManyField(related_name='_permitrequest_actors_+', through='permits.PermitRequestActor', to='gpf.Actor'),
        ),
        migrations.AddField(
            model_name='permitrequestactor',
            name='permit_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permits.PermitRequest'),
        ),
    ]
