# Generated by Django 2.2.13 on 2020-06-29 13:28

import django.core.validators
from django.db import migrations, models
import permits.fields


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0003_auto_20200623_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permitrequest',
            options={'permissions': [('amend_permit_request', 'Traiter les demandes de permis'), ('validate_permit_request', 'Valider les demandes de permis'), ('classify_permit_request', 'Classer les demandes de permis')], 'verbose_name': 'demande de permis', 'verbose_name_plural': 'demandes de permis'},
        ),
        migrations.AlterField(
            model_name='permitactortype',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Autres'), (2, 'Propriétaire'), (3, 'Entreprise'), (4, "Maître d'ouvrage"), (1, "Requérant si différent de l'auteur de la demande"), (5, 'Sécurité'), (6, 'Association')], default=0, verbose_name='type de contact'),
        ),
        migrations.AlterField(
            model_name='permitrequest',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Analyse du service pilote'),
        ),
        migrations.AlterField(
            model_name='permitrequest',
            name='creditor_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Autres'), (2, 'Propriétaire'), (3, 'Entreprise'), (4, "Maître d'ouvrage"), (1, "Requérant si différent de l'auteur de la demande"), (5, 'Sécurité'), (6, 'Association')], null=True, verbose_name='Destinaire de la facture'),
        ),
        migrations.AlterField(
            model_name='permitrequest',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Émolument'),
        ),
        migrations.AlterField(
            model_name='permitrequest',
            name='validation_pdf',
            field=permits.fields.PermitRequestFileField(storage=permits.fields.PrivateFileSystemStorage(), upload_to='validations', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='pdf de validation'),
        ),
        migrations.AlterField(
            model_name='permitrequestactor',
            name='actor_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Autres'), (2, 'Propriétaire'), (3, 'Entreprise'), (4, "Maître d'ouvrage"), (1, "Requérant si différent de l'auteur de la demande"), (5, 'Sécurité'), (6, 'Association')], default=0, verbose_name='type de contact'),
        ),
        migrations.AlterField(
            model_name='permitrequestgeotime',
            name='ends_at',
            field=models.DateTimeField(verbose_name='Date planifiée de fin'),
        ),
        migrations.AlterField(
            model_name='permitrequestgeotime',
            name='starts_at',
            field=models.DateTimeField(verbose_name='Date planifiée de début'),
        ),
    ]
