# Generated by Django 2.2.6 on 2020-01-31 09:17

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0004_auto_20200129_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitrequest',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(default=('Point(2539853 1182169)'), srid=2056, verbose_name='geom'),
            preserve_default=False,
        ),
    ]
