# Generated by Django 2.2.6 on 2020-04-05 13:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0004_add_actors_through'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermitRequestGeoTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_start', models.DateTimeField(verbose_name='Date de début')),
                ('datetime_end', models.DateTimeField(verbose_name='Date de fin')),
                ('description', models.CharField(max_length=1024, verbose_name='Description')),
                ('external_link', models.URLField(verbose_name='Lien externe')),
                ('geom', django.contrib.gis.db.models.fields.GeometryCollectionField(null=True, srid=2056, verbose_name='geom')),
                ('permit_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permits.PermitRequest')),
            ],
        ),
    ]
