# Generated by Django 2.2.6 on 2020-02-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0005_permitrequest_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitrequest',
            name='city_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='npa',
            field=models.PositiveIntegerField(null=True, verbose_name='NPA'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='street_name',
            field=models.CharField(max_length=512, null=True, verbose_name='Rue'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='street_number',
            field=models.CharField(max_length=32, null=True, verbose_name='Rue'),
        ),
    ]
