# Generated by Django 2.2.13 on 2020-11-09 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0005_historicalpermitactor_historicalpermitauthor_historicalpermitrequest_historicalpermitrequestgeotime_'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permitrequest',
            options={'permissions': [('amend_permit_request', 'Traiter les demandes de permis'), ('validate_permit_request', 'Valider les demandes de permis'), ('classify_permit_request', 'Classer les demandes de permis'), ('edit_permit_request', 'Éditer les demandes de permis')], 'verbose_name': '3.1 Consultation de la demande', 'verbose_name_plural': '3.1 Consultation des demandes'},
        ),
    ]
