# Generated by Django 2.2.6 on 2020-03-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0005_add_contact_related_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitrequestactor',
            name='actor_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Autres'), (2, 'Popriétaire'), (3, 'Entreprise'), (4, "Maître d'ouvrage"), (1, "Requérant si différent de l'auteur de la demande"), (5, 'Sécurité'), (6, 'Association')], default=0, verbose_name='type de contact'),
        ),
    ]
