# Generated by Django 2.2.13 on 2020-11-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permits", "0006_auto_20201109_0743"),
    ]

    operations = [
        migrations.AddField(
            model_name="worksobject",
            name="wms_layers",
            field=models.URLField(
                blank=True, max_length=1024, verbose_name="Couche(s) WMS"
            ),
        ),
    ]
