# Generated by Django 2.2.6 on 2020-03-27 10:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0006_permitrequestactor_actor_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermitActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('firstname', models.CharField(blank=True, max_length=100, verbose_name='firstname')),
                ('company_name', models.CharField(blank=True, max_length=100, verbose_name='company_name')),
                ('vat_number', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message="Le code d'entreprise doit être de type CHE-123.456.789 et vous pouvez le trouver sur                 le registe fédéral des entreprises                 https://www.uid.admin.ch/search.aspx", regex='([CHE-])+\\d{3}[.]+\\d{3}[.]+\\d{3}')], verbose_name='vat_number')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='address')),
                ('zipcode', models.PositiveIntegerField(null=True, verbose_name='zipcode')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('phone_fixed', models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Seuls les chiffres et les espaces sont autorisés', regex='^(\\s*[0-9]+\\s*)+$')], verbose_name='phone_fixed')),
                ('phone_mobile', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Seuls les chiffres et les espaces sont autorisés', regex='^(\\s*[0-9]+\\s*)+$')], verbose_name='phone_mobile')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
            ],
            options={
                'verbose_name': 'permitactor',
            },
        ),
        migrations.AlterField(
            model_name='permitrequest',
            name='actors',
            field=models.ManyToManyField(related_name='_permitrequest_actors_+', through='permits.PermitRequestActor', to='permits.PermitActor'),
        ),
        migrations.AlterField(
            model_name='permitrequestactor',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permits.PermitActor'),
        ),
    ]
