# Generated by Django 2.2.6 on 2020-02-14 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpf', '0029_auto_20191115_0801'),
        ('permits', '0006_auto_20200202_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermitRequestActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gpf.Actor')),
                ('permit_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='permits.PermitRequest')),
            ],
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='actors',
            field=models.ManyToManyField(related_name='_permitrequest_actors_+', through='permits.PermitRequestActor', to='gpf.Actor'),
        ),
    ]
