# Generated by Django 2.2.6 on 2020-03-31 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0007_auto_20200327_1021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permitactor',
            options={'verbose_name': 'Demandeur'},
        ),
        migrations.RemoveField(
            model_name='permitactor',
            name='phone_fixed',
        ),
        migrations.RemoveField(
            model_name='permitactor',
            name='phone_mobile',
        ),
        migrations.RemoveField(
            model_name='permitrequestactor',
            name='description',
        ),
        migrations.AddField(
            model_name='permitactor',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Seuls les chiffres et les espaces sont autorisés', regex='^(\\s*[0-9]+\\s*)+$')], verbose_name='Téléphone'),
        ),
    ]
