# Generated by Django 2.2.6 on 2020-02-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0007_auto_20200214_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstype',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Permis de construire avec dispense'), (1, 'Utilisation du domaine public'), (2, 'Événements')], default=0, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='permitrequest',
            name='street_number',
            field=models.CharField(max_length=32, null=True, verbose_name='Numero'),
        ),
    ]
