# Generated by Django 2.2.6 on 2020-02-17 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0008_auto_20200217_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermitActorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Propriétaire', 'Propriétaire'), ('Entreprise', 'Entreprise'), ("Maître d'ouvrage", "Maître d'ouvrage"), ('Requérant', 'Requérant'), ('Responsable sécurité', 'Responsable sécurité'), ('Responsable association', 'Responsable association')], max_length=30, verbose_name='type de contact')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='obligatoire')),
                ('works_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works_actor_types', to='permits.WorksType', verbose_name='type de travaux')),
            ],
            options={
                'verbose_name': 'contact à saisir',
                'verbose_name_plural': 'contacts à saisir',
            },
        ),
    ]
