# Generated by Django 2.2.6 on 2020-05-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0008_auto_20200331_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitrequest',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='exemption',
            field=models.TextField(blank=True, verbose_name='Dérogation'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='opposition',
            field=models.TextField(blank=True, verbose_name='Opposition'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='permitrequest',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Brouillon'), (1, 'Envoyée, en attente de traitement'), (3, 'En traitement'), (2, 'Validée'), (4, 'Demande de compléments')], default=0, verbose_name='état'),
        ),
    ]
