# Generated by Django 2.2.6 on 2020-02-17 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0009_permitactortype'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitrequestactor',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='permits.PermitActorType'),
        ),
        migrations.AlterField(
            model_name='permitactortype',
            name='works_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works_contact_types', to='permits.WorksType', verbose_name='type de travaux'),
        ),
    ]
