# Generated by Django 3.1.4 on 2021-01-24 20:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0010_auto_20201127_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpermitrequest',
            name='archeology_status',
        ),
        migrations.RemoveField(
            model_name='historicalpermitrequest',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='historicalpermitrequest',
            name='exemption',
        ),
        migrations.RemoveField(
            model_name='historicalpermitrequest',
            name='opposition',
        ),
        migrations.RemoveField(
            model_name='historicalpermitrequest',
            name='price',
        ),
        migrations.RemoveField(
            model_name='permitrequest',
            name='archeology_status',
        ),
        migrations.RemoveField(
            model_name='permitrequest',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='permitrequest',
            name='exemption',
        ),
        migrations.RemoveField(
            model_name='permitrequest',
            name='opposition',
        ),
        migrations.RemoveField(
            model_name='permitrequest',
            name='price',
        ),
        migrations.AddField(
            model_name='historicalpermitrequest',
            name='amend_custom_properties',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='amend_custom_properties',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='PermitRequestAmendProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='obligatoire')),
                ('works_object_types', models.ManyToManyField(related_name='permitrequestamendproperty_properties', to='permits.WorksObjectType', verbose_name='objets des travaux')),
            ],
            options={
                'verbose_name': '2.2 Configuration de champ de traitement de demande',
                'verbose_name_plural': '2.2 Configuration des champs de traitement des demandes',
            },
        ),
    ]
