# Generated by Django 3.1.4 on 2021-01-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0010_auto_20201127_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitactortype',
            name='is_mandatory',
            field=models.BooleanField(default=True, verbose_name='obligatoire'),
        ),
        migrations.AlterField(
            model_name='historicalpermitactor',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='historicalpermitactor',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='historicalpermitactor',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Entreprise'),
        ),
        migrations.AlterField(
            model_name='historicalpermitactor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='historicalpermitactor',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='historicalpermitactor',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='historicalpermitactor',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='historicalpermitactor',
            name='zipcode',
            field=models.PositiveIntegerField(blank=True, verbose_name='NPA'),
        ),
        migrations.AlterField(
            model_name='permitactor',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='permitactor',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='permitactor',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Entreprise'),
        ),
        migrations.AlterField(
            model_name='permitactor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='permitactor',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='permitactor',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='permitactor',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='permitactor',
            name='zipcode',
            field=models.PositiveIntegerField(blank=True, verbose_name='NPA'),
        ),
        migrations.AlterUniqueTogether(
            name='permitactortype',
            unique_together={('type', 'works_type')},
        ),
    ]
