# Generated by Django 2.2.6 on 2020-02-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0010_auto_20200217_0919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permitrequestactor',
            options={'verbose_name': 'permis-acteur', 'verbose_name_plural': 'permis-acteurs'},
        ),
        migrations.RenameField(
            model_name='permitrequestactor',
            old_name='type',
            new_name='actor_type',
        ),
        migrations.AlterField(
            model_name='permitactortype',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Autres'), (2, 'Popriétaire'), (3, 'Entreprise'), (4, "Maître d'ouvrage"), (1, "Requérant si différent de l'auteur de la demande"), (5, 'Sécurité'), (6, 'Association')], default=0, verbose_name='type de contact'),
        ),
    ]
