# Generated by Django 3.1.4 on 2021-01-28 09:58

from django.db import migrations, models


def reorder(apps, schema_editor):
    WorksObjectProperty = apps.get_model("permits", "worksobjectproperty")
    order = 0
    for item in WorksObjectProperty.objects.all():
        print(item)
        order += 1
        item.order = order
        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0011_works_object_properties_date_input'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worksobjectproperty',
            options={'ordering': ['order'], 'verbose_name': '1.5 Configuration du champ', 'verbose_name_plural': '1.5 Configuration des champs'},
        ),
        migrations.AddField(
            model_name='worksobjectproperty',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ordre'),
        ),
        migrations.RunPython(reorder),
    ]
