# Generated by Django 2.2.6 on 2020-05-12 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpf', '0031_default_validator'),
        ('permits', '0011_permits_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermitRequestValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_status', models.IntegerField(choices=[(0, 'En attente'), (1, 'Approuvé'), (2, 'Refusé')], default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permit_request_validations', to='gpf.Department')),
                ('permit_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='permits.PermitRequest')),
            ],
            options={
                'unique_together': {('permit_request', 'department')},
            },
        ),
    ]
