# Generated by Django 3.1.4 on 2021-01-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0012_auto_20210121_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worksobjectproperty',
            options={'ordering': ['order'], 'verbose_name': '1.5 Configuration du champ', 'verbose_name_plural': '1.5 Configuration des champs'},
        ),
        migrations.AlterField(
            model_name='worksobjectproperty',
            name='order',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Position'),
        ),
    ]
