# Generated by Django 2.2.6 on 2020-05-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0012_permitrequestvalidation'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitrequestvalidation',
            name='comment_after',
            field=models.TextField(default='', verbose_name='Commentaires (après)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permitrequestvalidation',
            name='comment_before',
            field=models.TextField(default='', verbose_name='Commentaires (avant)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permitrequestvalidation',
            name='comment_during',
            field=models.TextField(default='', verbose_name='Commentaires (pendant)'),
            preserve_default=False,
        ),
    ]
