# Generated by Django 2.2.6 on 2020-05-28 07:51

import django.core.validators
from django.db import migrations, models
import permits.fields


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0013_validation_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permitrequest',
            options={'permissions': [('amend_permit_request', 'Amender les demandes de permis'), ('validate_permit_request', 'Valider les demandes de permis'), ('classify_permit_request', 'Classer les demandes de permis')], 'verbose_name': 'demande de permis', 'verbose_name_plural': 'demandes de permis'},
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='validation_pdf',
            field=permits.fields.PermitRequestFileField(blank=True, storage=permits.fields.PrivateFileSystemStorage(), upload_to='validations', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='pdf de validation'),
        ),
        migrations.AlterField(
            model_name='permitrequest',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Brouillon'), (1, 'Envoyée, en attente de traitement'), (3, 'En traitement'), (2, 'Approuvée'), (6, 'Refusée'), (4, 'Demande de compléments'), (5, 'En validation')], default=0, verbose_name='état'),
        ),
        migrations.AlterField(
            model_name='permitrequestvalidation',
            name='comment_after',
            field=models.TextField(blank=True, verbose_name='Commentaires (après)'),
        ),
        migrations.AlterField(
            model_name='permitrequestvalidation',
            name='comment_before',
            field=models.TextField(blank=True, verbose_name='Commentaires (avant)'),
        ),
        migrations.AlterField(
            model_name='permitrequestvalidation',
            name='comment_during',
            field=models.TextField(blank=True, verbose_name='Commentaires (pendant)'),
        ),
        migrations.AlterField(
            model_name='permitrequestvalidation',
            name='validation_status',
            field=models.IntegerField(choices=[(0, 'En attente'), (1, 'Approuvé'), (2, 'Refusé')], default=0, verbose_name='Statut de validation'),
        ),
    ]
