# Generated by Django 3.1.4 on 2021-01-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0013_auto_20210121_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksobjectproperty',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ordre'),
        ),
    ]
