# Generated by Django 2.2.6 on 2020-05-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0014_validation_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permitrequest',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Brouillon'), (1, 'Envoyée, en attente de traitement'), (4, 'Demande de compléments'), (3, 'En traitement'), (5, 'En validation'), (2, 'Approuvée'), (6, 'Refusée')], default=0, verbose_name='état'),
        ),
    ]
