# Generated by Django 3.1.4 on 2021-03-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0017_permit_request_amend_custom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksobjectproperty',
            name='placeholder',
            field=models.CharField(blank=True, max_length=255, verbose_name='placeholder'),
        ),
    ]
