# Generated by Django 3.1.4 on 2021-03-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0017_permit_request_amend_custom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitadministrativeentity',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Public'),
        ),
        migrations.AddField(
            model_name='worksobject',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Public'),
        ),
        migrations.AddField(
            model_name='worksobjecttype',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Public'),
        ),
    ]
