# Generated by Django 3.1.4 on 2021-03-11 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0018_auto_20210311_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permitadministrativeentity',
            options={'permissions': [('see_private_demands', 'Voir les demandes restreintes')], 'verbose_name': "1.1 Configuration de l'entité administrative (commune, organisation)", 'verbose_name_plural': "1.1 Configuration de l'entité administrative (commune, organisation)"},
        ),
    ]
