# Generated by Django 3.1.4 on 2021-04-22 06:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0019_add_field_placeholder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permitadministrativeentity',
            name='general_informations',
        ),
        migrations.RemoveField(
            model_name='permitadministrativeentity',
            name='legal_document',
        ),
        migrations.AddField(
            model_name='worksobjectproperty',
            name='help_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='information complémentaire'),
        ),
        migrations.AddField(
            model_name='worksobjecttype',
            name='additional_information',
            field=models.TextField(blank=True, verbose_name='autre information'),
        ),
        migrations.AddField(
            model_name='worksobjecttype',
            name='directive',
            field=models.FileField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='directive'),
        ),
        migrations.AddField(
            model_name='worksobjecttype',
            name='directive_description',
            field=models.CharField(blank=True, max_length=200, verbose_name='description de la directive'),
        ),
        migrations.AddField(
            model_name='worksobjecttype',
            name='has_geometry_line',
            field=models.BooleanField(default=True, verbose_name='Ligne'),
        ),
        migrations.AddField(
            model_name='worksobjecttype',
            name='has_geometry_point',
            field=models.BooleanField(default=True, verbose_name='Point'),
        ),
        migrations.AddField(
            model_name='worksobjecttype',
            name='has_geometry_polygon',
            field=models.BooleanField(default=True, verbose_name='Surface'),
        ),
    ]
