# Generated by Django 3.1.4 on 2021-03-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0019_add_field_placeholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksobjectproperty',
            name='help_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='information complémentaire'),
        ),
    ]
