# Generated by Django 3.1.4 on 2021-03-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0019_auto_20210311_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksobjecttype',
            name='is_public',
        ),
        migrations.AddField(
            model_name='workstype',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Public'),
        ),
    ]
