# Generated by Django 3.1.4 on 2021-04-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0020_add_field_help_text_add_geometry_types_in_WorksObjectType_model_delete_needs_geometry_directives_remove_admin_gral_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksobjecttype',
            name='requires_payment',
            field=models.BooleanField(default=True, verbose_name='Demande soumise à des frais'),
        ),
    ]
