# Generated by Django 3.1.4 on 2021-04-13 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0020_add_field_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksobjecttype',
            name='additional_information',
            field=models.TextField(blank=True, verbose_name='autre information'),
        ),
        migrations.AddField(
            model_name='worksobjecttype',
            name='directive',
            field=models.FileField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='directive'),
        ),
        migrations.AddField(
            model_name='worksobjecttype',
            name='directive_description',
            field=models.CharField(blank=True, max_length=200, verbose_name='description de la directive'),
        ),
    ]
