# Generated by Django 3.1.4 on 2021-04-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0020_add_field_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeometryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
            ],
            options={
                'verbose_name': '1.7 Configuration du type de géometrie',
                'verbose_name_plural': '1.7 Configuration des types de géometrie',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='worksobjecttype',
            name='geometry_types',
            field=models.ManyToManyField(blank=True, related_name='works_object_types', to='permits.GeometryType', verbose_name='types de géométrie'),
        ),
    ]
