# Generated by Django 3.1.4 on 2021-04-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0020_add_field_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksobjecttype',
            name='has_geometry_point',
            field=models.BooleanField(default=True, verbose_name='Point'),
        ),
        migrations.AddField(
            model_name='worksobjecttype',
            name='has_geometry_line',
            field=models.BooleanField(default=True, verbose_name='Ligne'),
        ),
        migrations.AddField(
            model_name='worksobjecttype',
            name='has_geometry_polygon',
            field=models.BooleanField(default=True, verbose_name='Surface'),
        ),
    ]
