# Generated by Django 3.1.4 on 2021-04-13 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0020_add_field_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeometryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dot', models.BooleanField(default=True, verbose_name='point')),
                ('line', models.BooleanField(default=True, verbose_name='ligne')),
                ('surface', models.BooleanField(default=True, verbose_name='surface')),
            ],
        ),
        migrations.AddField(
            model_name='worksobjecttype',
            name='geometry_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='works_object_types', to='permits.geometrytype', verbose_name='type de géometrie'),
            preserve_default=False,
        ),
    ]
