# Generated by Django 3.1.4 on 2021-04-20 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0020_add_field_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='QgisTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qgis_file', models.FileField(upload_to='qgis_templates')),
                ('qgis_name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('works_object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permits.worksobjecttype')),
            ],
        ),
    ]
