# Generated by Django 3.1.4 on 2021-06-02 09:21

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('permits', '0021_add_field_help_text_add_geometry_types_in_WorksObjectType_model_delete_needs_geometry_directives_remove_admin_gral_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitadministrativeentity',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Mots-clés'),
        ),
        migrations.AddField(
            model_name='worksobjecttype',
            name='requires_payment',
            field=models.BooleanField(default=True, verbose_name='Demande soumise à des frais'),
        ),
    ]
