# Generated by Django 3.1.4 on 2021-05-03 15:12

from django.db import migrations, models
import django.db.models.deletion
import permits.fields


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0021_add_requires_payment_field_to_works_object_type_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitadministrativeentity',
            name='general_informations',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Informations'),
        ),
        migrations.AddField(
            model_name='permitadministrativeentity',
            name='legal_document',
            field=permits.fields.AdministrativeEntityFileField(blank=True, storage=permits.fields.PrivateFileSystemStorage(), upload_to='administrative_entity_files/', verbose_name='Directive'),
        ),
        migrations.CreateModel(
            name='QgisProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qgis_project_file', permits.fields.AdministrativeEntityFileField(storage=permits.fields.PrivateFileSystemStorage(), upload_to='qgis_templates', verbose_name="Fichier QGIS '*.qgs'")),
                ('qgis_print_template_name', models.CharField(max_length=150, verbose_name="Nom du template d'impression QGIS")),
                ('qgis_layers', models.CharField(max_length=500, verbose_name="Liste des couches QGIS à afficher séparées par les virgules ','")),
                ('description', models.CharField(max_length=150)),
                ('works_object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permits.worksobjecttype')),
            ],
        ),
    ]
