# Generated by Django 3.1.4 on 2021-06-02 09:21

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('permits', '0021_add_field_help_text_add_geometry_types_in_WorksObjectType_model_delete_needs_geometry_directives_remove_admin_gral_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitadministrativeentity',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text="Mots clefs sans espaces, séparés par des virgules permettant ensuite de filtrer les entités par l'url: https://geocity.ch&filter=yverdon&filter=permis-de-fouille", through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Mots-clés'),
        ),
        migrations.AddField(
            model_name='worksobjecttype',
            name='requires_payment',
            field=models.BooleanField(default=True, verbose_name='Demande soumise à des frais'),
        ),
        migrations.RemoveField(
            model_name='permitdepartment',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='permitactortype',
            name='integrator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Groupe des administrateurs'),
        ),
        migrations.AddField(
            model_name='permitadministrativeentity',
            name='integrator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Groupe des administrateurs'),
        ),
        migrations.AddField(
            model_name='permitdepartment',
            name='integrator',
            field=models.IntegerField(default=0, verbose_name='Intégrateur responsable'),
        ),
        migrations.AddField(
            model_name='permitdepartment',
            name='is_integrator_admin',
            field=models.BooleanField(default=False, verbose_name="Intégrateur (accès à l'admin de django)"),
        ),
        migrations.AddField(
            model_name='permitrequestamendproperty',
            name='integrator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Groupe des administrateurs'),
        ),
        migrations.AddField(
            model_name='worksobject',
            name='integrator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Groupe des administrateurs'),
        ),
        migrations.AddField(
            model_name='worksobjectproperty',
            name='integrator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Groupe des administrateurs'),
        ),
        migrations.AddField(
            model_name='worksobjecttype',
            name='integrator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Groupe des administrateurs'),
        ),
        migrations.AddField(
            model_name='workstype',
            name='integrator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Groupe des administrateurs'),
        ),
        migrations.AlterField(
            model_name='permitadministrativeentity',
            name='ofs_id',
            field=models.PositiveIntegerField(verbose_name='Numéro OFS'),
        ),
        migrations.AlterField(
            model_name='permitdepartment',
            name='administrative_entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='permits.permitadministrativeentity', verbose_name='entité administrative'),
        ),
        migrations.AlterField(
            model_name='permitdepartment',
            name='is_archeologist',
            field=models.BooleanField(verbose_name='archéologue'),
        ),
        migrations.AlterField(
            model_name='permitdepartment',
            name='is_validator',
            field=models.BooleanField(verbose_name='validateur'),
        ),
    ]
