# Generated by Django 3.1.4 on 2021-04-15 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0021_directives'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permitadministrativeentity',
            name='general_informations',
        ),
        migrations.RemoveField(
            model_name='permitadministrativeentity',
            name='legal_document',
        ),
    ]
