# Generated by Django 3.1.4 on 2021-04-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0021_integrator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permitdepartment',
            name='is_intgrator_admin',
        ),
        migrations.AlterField(
            model_name='permitdepartment',
            name='is_integrator_admin',
            field=models.BooleanField(default=False, verbose_name="Intégrateur (accès à l'admin de django)"),
        ),
    ]
