# Generated by Django 3.1.4 on 2021-05-03 21:57

from django.db import migrations, models
import django.db.models.deletion
import permits.fields
import permits.models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0022_QgisProject_model_and_printed_file_field_on_PermitRequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpermitrequest',
            name='printed_at',
        ),
        migrations.RemoveField(
            model_name='historicalpermitrequest',
            name='printed_by',
        ),
        migrations.RemoveField(
            model_name='historicalpermitrequest',
            name='printed_file',
        ),
        migrations.RemoveField(
            model_name='permitrequest',
            name='printed_at',
        ),
        migrations.RemoveField(
            model_name='permitrequest',
            name='printed_by',
        ),
        migrations.RemoveField(
            model_name='permitrequest',
            name='printed_file',
        ),
        migrations.CreateModel(
            name='QgisGeneratedDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printed_at', models.DateTimeField(null=True, verbose_name="date d'impression")),
                ('printed_by', models.CharField(blank=True, max_length=255, verbose_name='imprimé par')),
                ('printed_file', permits.fields.AdministrativeEntityFileField(blank=True, null=True, storage=permits.fields.PrivateFileSystemStorage(), upload_to=permits.models.printed_permit_request_storage, verbose_name='Permis imprimé')),
                ('permit_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qgis_permit', to='permits.permitrequest')),
                ('qgis_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qgis_project', to='permits.qgisproject')),
            ],
        ),
    ]
