# Generated by Django 3.2.4 on 2021-06-09 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0023_qgis_template_jsonfield_model'),
    ]

    operations = [
    ]
