# Generated by Django 3.1.4 on 2021-05-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0023_qgis_template_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpermitauthor',
            name='do_not_notify',
            field=models.BooleanField(default=False, verbose_name='ne pas me notifier'),
        ),
        migrations.AddField(
            model_name='permitauthor',
            name='do_not_notify',
            field=models.BooleanField(default=False, verbose_name='ne pas me notifier'),
        ),
    ]
