# Generated by Django 3.2.4 on 2021-06-18 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0024_integrator_data_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permitdepartment',
            name='administrative_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='permits.permitadministrativeentity', verbose_name='entité administrative'),
        ),
    ]
