# Generated by Django 3.2.4 on 2021-06-23 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0026_rename_status_received'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permitadministrativeentity',
            name='image_signature_1',
        ),
        migrations.RemoveField(
            model_name='permitadministrativeentity',
            name='image_signature_2',
        ),
    ]
