# Generated by Django 3.2.4 on 2021-06-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permits", "0028_use_custom_file_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="permitrequestamendproperty",
            name="is_visible_by_author",
            field=models.BooleanField(
                default=True, verbose_name="Visible par l'auteur de la demande"
            ),
        ),
    ]
