# Generated by Django 3.2.4 on 2021-07-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0029_visibility_of_secreatariat_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitdepartment',
            name='mandatory_2fa',
            field=models.BooleanField(default=False, verbose_name='2FA obligatoire'),
        ),
    ]
