# Generated by Django 3.2.4 on 2021-07-08 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0030_add_mandatory_2fa_to_permitdepartment'),
        ('permits', '0030_add_requires_validation_document_field_to_wot'),
    ]

    operations = [
    ]
