# Generated by Django 3.2.4 on 2021-07-15 18:41

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('permits', '0032_add_notification_for_services_in_wot'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstype',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text="Mots clefs sans espaces, séparés par des virgules permettant ensuite de filtrer les entités par l'url: https://geocity.ch&filter=yverdon&filter=permis-de-fouille", through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Mots-clés'),
        ),
    ]
