# Generated by Django 3.2.4 on 2021-08-02 04:49

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('permits', '0035_add_tag_to_works_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstype',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text="Mots clefs sans espaces, séparés par des virgules permettant ensuite de filtrer les entités par l'url: https://geocity.ch&typefilter=permisdefouille&typefilter=stationnement", through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Mots-clés'),
        ),
    ]
