# Generated by Django 3.2.4 on 2021-08-18 05:58

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('permits', '0036_alter_workstype_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permitadministrativeentity',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text="Mots clefs sans espaces, séparés par des virgules permettant de filtrer les entités par l'url: https://geocity.ch/?entityfilter=yverdon", through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Mots-clés'),
        ),
        migrations.AlterField(
            model_name='workstype',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text="Mots clefs sans espaces, séparés par des virgules permettant de filtrer les types par l'url: https://geocity.ch/?typefilter=stationnement", through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Mots-clés'),
        ),
    ]
