# Generated by monodo on 2020-09-24 15:28
from django.db import migrations
from permits import models as permitsModels


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0002_auto_20200928_1114'),
    ]

    def insertData(apps, schema_editor):

        for status_value in permitsModels.PermitRequest.STATUS_CHOICES:
            statusChoice = permitsModels.PermitWorkFlowStatus(status=status_value[0])
            statusChoice.save()

    operations = [
        migrations.RunPython(insertData),
    ]
