# Generated by Django 3.2.4 on 2021-09-02 08:47

from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("permits", "0039_list_property"),
    ]

    operations = [TrigramExtension(), UnaccentExtension()]
