# Generated by Django 3.2.7 on 2021-10-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0041_permit_request_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksobjectproperty',
            name='input_type',
            field=models.CharField(choices=[('text', 'Texte'), ('checkbox', 'Case à cocher'), ('number', 'Nombre'), ('file', 'Fichier'), ('address', 'Adresse'), ('date', 'Date'), ('list_single', 'Choix simple'), ('list_multiple', 'Choix multiple'), ('title', 'Titre')], max_length=30, verbose_name='type de caractéristique'),
        ),
    ]
