# Generated by Django 3.2.4 on 2021-10-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0041_permit_request_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksobjecttype',
            name='days_before_reminder',
            field=models.IntegerField(blank=True, default=10, verbose_name='Delai de rappel (jours)'),
        ),
        migrations.AddField(
            model_name='worksobjecttype',
            name='expiration_reminder',
            field=models.BooleanField(default=True, verbose_name='Activer la fonctionde rappel'),
        ),
        migrations.AddField(
            model_name='worksobjecttype',
            name='permit_duration',
            field=models.IntegerField(blank=True, default=365, verbose_name='Durée de validité de la demande (jours)'),
        ),
    ]
