# Generated by Django 3.2.4 on 2021-10-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0042_add_permit_duration_expiration_reminder_to_wot'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpermitrequest',
            name='is_prolonged',
            field=models.BooleanField(default=False, verbose_name='Prolongation acceptée'),
        ),
        migrations.AddField(
            model_name='historicalpermitrequest',
            name='prolongation_comment',
            field=models.TextField(blank=True, verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='historicalpermitrequest',
            name='prolongation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Nouvelle date de fin'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='is_prolonged',
            field=models.BooleanField(default=False, verbose_name='Prolongation acceptée'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='prolongation_comment',
            field=models.TextField(blank=True, verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='prolongation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Nouvelle date de fin'),
        ),
    ]
