# Generated by Django 3.2.7 on 2021-10-14 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0042_add_regex_to_worksobjectproperty'),
        ('permits', '0042_alter_worksobjectproperty_input_type'),
        ('permits', '0042_worksobjecttype_start_delay'),
    ]

    operations = [
    ]
