# Generated by Django 3.2.4 on 2021-10-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0042_add_permit_duration_expiration_reminder_to_wot'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpermitrequest',
            name='prolongation_comment',
            field=models.TextField(blank=True, verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='historicalpermitrequest',
            name='prolongation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Nouvelle date de fin'),
        ),
        migrations.AddField(
            model_name='historicalpermitrequest',
            name='prolongation_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'En attente'), (1, 'Approuvée'), (2, 'Refusée')], null=True, verbose_name='Décision'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='prolongation_comment',
            field=models.TextField(blank=True, verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='prolongation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Nouvelle date de fin'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='prolongation_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'En attente'), (1, 'Approuvée'), (2, 'Refusée')], null=True, verbose_name='Décision'),
        ),
    ]
