# Generated by Django 3.2.7 on 2021-11-12 07:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permits", "0049_add_fields_to_wot_and_permit_request_for_prolongation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permitadministrativeentity",
            name="expeditor_email",
            field=models.CharField(
                blank=True,
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Le format de l'adresse email n'est pas valable.",
                        regex="^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,63}$",
                    )
                ],
                verbose_name="Adresse email de l'expéditeur des notifications",
            ),
        ),
    ]
