# Generated by Django 3.2.7 on 2021-10-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0049_add_fields_to_wot_and_permit_request_for_prolongation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksobjecttype',
            name='permit_duration',
            field=models.IntegerField(blank=True, help_text="Le permis pour l'objet sera renouvelable uniquement si cette valeur est fournie.", null=True, verbose_name='Durée de validité de la demande (jours)'),
        ),
    ]
