# Generated by Django 3.2.7 on 2021-12-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0051_remove_unused_print_model_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitdepartment',
            name='integrator_email_domains',
            field=models.CharField(blank=True, help_text="Liste de domaines (ex: yverdon-les-bains.ch) séparés par des virgules ',' de domaines correspondant à des administrations publiques", max_length=254, verbose_name="Domaines d'emails visibles pour l'intégrateur"),
        ),
        migrations.AddField(
            model_name='permitdepartment',
            name='integrator_emails_exceptions',
            field=models.CharField(blank=True, help_text="Liste d'emails (ex: greffe@nowhere.com)séparés par des virgules ',' de domaines correspondant à des employés d'administrations publiques", max_length=254, verbose_name="Emails complets visibles pour l'intégrateur"),
        ),
    ]
