# Generated by Django 3.2.7 on 2021-12-15 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0052_add_email_domains_list_for_admin_filtering'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksobjectproperty',
            name='line_number_for_textarea',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Nombre de lignes de la zone de texte'),
        ),
    ]
