# Generated by Django 3.2.7 on 2021-12-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0053_line_number_textarea_custom_signature_additional_decision_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpermitrequestvalidation',
            name='comment_after',
            field=models.TextField(blank=True, help_text='Facultatif, sera transmis uniquement au service pilote', verbose_name='Commentaire (après)'),
        ),
        migrations.AlterField(
            model_name='historicalpermitrequestvalidation',
            name='comment_before',
            field=models.TextField(blank=True, help_text='Facultatif, sera transmis uniquement au service pilote', verbose_name='Commentaire (avant)'),
        ),
        migrations.AlterField(
            model_name='historicalpermitrequestvalidation',
            name='comment_during',
            field=models.TextField(blank=True, help_text='Facultatif, sera transmis uniquement au service pilote', verbose_name='Commentaire (pendant)'),
        ),
        migrations.AlterField(
            model_name='permitrequestvalidation',
            name='comment_after',
            field=models.TextField(blank=True, help_text='Facultatif, sera transmis uniquement au service pilote', verbose_name='Commentaire (après)'),
        ),
        migrations.AlterField(
            model_name='permitrequestvalidation',
            name='comment_before',
            field=models.TextField(blank=True, help_text='Facultatif, sera transmis uniquement au service pilote', verbose_name='Commentaire (avant)'),
        ),
        migrations.AlterField(
            model_name='permitrequestvalidation',
            name='comment_during',
            field=models.TextField(blank=True, help_text='Facultatif, sera transmis uniquement au service pilote', verbose_name='Commentaire (pendant)'),
        ),
    ]
