# Generated by Django 3.2.7 on 2021-12-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0053_line_number_for_textarea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permitadministrativeentity',
            name='logo_main',
        ),
        migrations.RemoveField(
            model_name='permitadministrativeentity',
            name='logo_secondary',
        ),
        migrations.RemoveField(
            model_name='permitadministrativeentity',
            name='title_signature_1',
        ),
        migrations.RemoveField(
            model_name='permitadministrativeentity',
            name='title_signature_2',
        ),
        migrations.AddField(
            model_name='permitadministrativeentity',
            name='custom_signature',
            field=models.TextField(blank=True, max_length=1024, verbose_name="Signature des emails, si vide, le nom de l'entité sera utilisé"),
        ),
    ]
