# Generated by Django 3.2.7 on 2021-12-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0054_custom_signature_for_administrative_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpermitrequest',
            name='additional_decision_information',
            field=models.TextField(blank=True, max_length=2048, verbose_name="Information complémentaire à ajouter à l'email de la décision"),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='additional_decision_information',
            field=models.TextField(blank=True, max_length=2048, verbose_name="Information complémentaire à ajouter à l'email de la décision"),
        ),
    ]
