# Generated by Django 3.2.7 on 2021-12-21 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0055_sort_contact_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpermitrequestamendpropertyvalue',
            name='works_object_type_choice',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='permits.worksobjecttypechoice', verbose_name='objet'),
        ),
        migrations.AlterField(
            model_name='historicalworksobjectpropertyvalue',
            name='works_object_type_choice',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='permits.worksobjecttypechoice', verbose_name='objet'),
        ),
        migrations.AlterField(
            model_name='permitactortype',
            name='works_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works_contact_types', to='permits.workstype', verbose_name='type de demande'),
        ),
        migrations.AlterField(
            model_name='permitrequest',
            name='works_object_types',
            field=models.ManyToManyField(related_name='permit_requests', through='permits.WorksObjectTypeChoice', to='permits.WorksObjectType', verbose_name='Objets et types de demandes'),
        ),
        migrations.AlterField(
            model_name='permitrequestamendproperty',
            name='works_object_types',
            field=models.ManyToManyField(related_name='amend_properties', to='permits.WorksObjectType', verbose_name='objets'),
        ),
        migrations.AlterField(
            model_name='permitrequestamendpropertyvalue',
            name='works_object_type_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amend_properties', to='permits.worksobjecttypechoice', verbose_name='objet'),
        ),
        migrations.AlterField(
            model_name='worksobjectproperty',
            name='works_object_types',
            field=models.ManyToManyField(related_name='properties', to='permits.WorksObjectType', verbose_name='objets'),
        ),
        migrations.AlterField(
            model_name='worksobjectpropertyvalue',
            name='works_object_type_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='permits.worksobjecttypechoice', verbose_name='objet'),
        ),
        migrations.AlterField(
            model_name='worksobjecttype',
            name='works_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works_object_types', to='permits.worksobject', verbose_name='objet'),
        ),
        migrations.AlterField(
            model_name='worksobjecttype',
            name='works_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works_object_types', to='permits.workstype', verbose_name='type'),
        ),
    ]
