# Generated by Django 3.2.7 on 2021-12-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0056_get_rid_of_term_travaux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpermitrequestvalidation',
            name='comment_after',
            field=models.TextField(blank=True, help_text='Information supplémentaire facultative transmise au requérant', verbose_name='Commentaire (après)'),
        ),
        migrations.AlterField(
            model_name='historicalpermitrequestvalidation',
            name='comment_before',
            field=models.TextField(blank=True, help_text='Information supplémentaire facultative transmise au requérant', verbose_name='Commentaire (avant)'),
        ),
        migrations.AlterField(
            model_name='historicalpermitrequestvalidation',
            name='comment_during',
            field=models.TextField(blank=True, help_text='Information supplémentaire facultative transmise au requérant', verbose_name='Commentaire (pendant)'),
        ),
        migrations.AlterField(
            model_name='permitrequestvalidation',
            name='comment_after',
            field=models.TextField(blank=True, help_text='Information supplémentaire facultative transmise au requérant', verbose_name='Commentaire (après)'),
        ),
        migrations.AlterField(
            model_name='permitrequestvalidation',
            name='comment_before',
            field=models.TextField(blank=True, help_text='Information supplémentaire facultative transmise au requérant', verbose_name='Commentaire (avant)'),
        ),
        migrations.AlterField(
            model_name='permitrequestvalidation',
            name='comment_during',
            field=models.TextField(blank=True, help_text='Information supplémentaire facultative transmise au requérant', verbose_name='Commentaire (pendant)'),
        ),
    ]
