# Generated by Django 3.2.7 on 2022-02-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0056_notify_user_per_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpermitrequest',
            name='shortname',
            field=models.CharField(blank=True, help_text='Sera affiché dans le calendrier si la demande est rendue tout publique, ex: Brandons (max. 32 caractères)', max_length=32, verbose_name='nom de la demande'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='shortname',
            field=models.CharField(blank=True, help_text='Sera affiché dans le calendrier si la demande est rendue tout publique, ex: Brandons (max. 32 caractères)', max_length=32, verbose_name='nom de la demande'),
        ),
    ]
