# Generated by Django 3.2.7 on 2021-12-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('permits', '0056_notify_user_per_email.py'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitadministrativeentity',
            name='sites',
            field=models.ManyToManyField(to='sites.Site'),
        ),
    ]
