# Generated by Django 3.2.7 on 2022-02-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0057_add_shortname_to_permitrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksobject',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='ordre'),
        ),
    ]
