# Generated by Django 3.2.12 on 2022-03-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0059_add_order_field_to_works_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksobjectproperty',
            name='input_type',
            field=models.CharField(choices=[('address', 'Adresse'), ('parcel', 'Parcelle'), ('checkbox', 'Case à cocher'), ('list_multiple', 'Choix multiple'), ('list_single', 'Choix simple'), ('date', 'Date'), ('file', 'Fichier'), ('number', 'Nombre'), ('text', 'Texte'), ('regex', 'Texte (regex)'), ('title', 'Titre')], max_length=30, verbose_name='type de caractéristique'),
        ),
    ]
