# Generated by Django 3.2.12 on 2022-03-18 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('permits', '0059_add_order_field_to_works_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermitRequestComplementaryDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255, verbose_name='Nom du document')),
                ('description', models.TextField(blank=True, verbose_name='Description du document')),
                ('integrator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Groupe des administrateurs')),
                ('permit_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permits.permitrequest', verbose_name='Something')),
            ],
        ),
    ]
