# Generated by Django 3.2.12 on 2022-02-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0059_add_order_field_to_works_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpermitauthor',
            name='is_anonymous_user',
            field=models.BooleanField(default=False, verbose_name='Utilisateur anonyme pour utilisation de liens django-sesame'),
        ),
        migrations.AddField(
            model_name='permitauthor',
            name='is_anonymous_user',
            field=models.BooleanField(default=False, verbose_name='Utilisateur anonyme pour utilisation de liens django-sesame'),
        ),
    ]
