# Generated by Django 3.2.7 on 2022-02-22 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0059_add_order_field_to_works_object'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worksobject',
            options={'ordering': ['order'], 'verbose_name': "1.3 Configuration de l'objet", 'verbose_name_plural': '1.3 Configuration des objets'},
        ),
    ]
