# Generated by Django 3.2.12 on 2022-03-29 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permits', '0059_add_order_field_to_works_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermitRequestComplementaryDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='', verbose_name='Document')),
                ('description', models.TextField(blank=True, verbose_name='Description du document')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Provisoire'), (1, 'Final'), (2, 'Autre'), (3, 'Annulé')], verbose_name='Statut du document')),
                ('is_public', models.BooleanField(default=False, verbose_name='Public')),
                ('authorised_departments', models.ManyToManyField(to='permits.PermitDepartment', verbose_name='Département autorisé à visualiser le document')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire du document')),
                ('permit_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permits.permitrequest', verbose_name='Demande de permis')),
            ],
        ),
    ]
