# Generated by Django 3.2.12 on 2022-04-07 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0060_add_services_to_notify_in_WorksObjectProperty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatecustomization',
            name='templatename',
            field=models.CharField(blank=True, help_text="Permettant d'afficher la page de login par l'url: https://geocity.ch/?template=vevey", max_length=64, validators=[django.core.validators.RegexValidator(message='Seuls les caractères sans accents et les chiffres sont autorisés. Les espaces et autres caractères spéciaux ne sont pas autorisés', regex='^[a-zA-Z0-9_]*$')], verbose_name='Identifiant'),
        ),
    ]
