# Generated by Django 3.2.12 on 2022-04-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0060_add_services_to_notify_in_WorksObjectProperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitdepartment',
            name='duo_2fa',
            field=models.BooleanField(default=False, verbose_name='2FA mode duo MFA'),
        ),
    ]
