# Generated by Django 3.2.12 on 2022-04-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0060_add_services_to_notify_in_WorksObjectProperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitrequestamendproperty',
            name='can_always_update',
            field=models.BooleanField(default=False, verbose_name='Editable même après classement de la demande'),
        ),
    ]