# Generated by Django 3.2.12 on 2022-04-05 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0060_add_services_to_notify_in_WorksObjectProperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpermitauthor',
            name='administrative_entity',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='permits.permitadministrativeentity', verbose_name='entité administrative'),
        ),
        migrations.AddField(
            model_name='permitauthor',
            name='administrative_entity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anonymous_user', to='permits.permitadministrativeentity', verbose_name='entité administrative'),
        ),
    ]
