# Generated by Django 3.2.12 on 2022-04-05 22:15

import django.core.validators
from django.db import migrations, models
import permits.fields


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0060_add_services_to_notify_in_WorksObjectProperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksobjectproperty',
            name='file_download',
            field=permits.fields.WorkObjectTypeFileField(null=True, storage=permits.fields.PrivateFileSystemStorage(), upload_to='wot_files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Fichier'),
        ),
        migrations.AddField(
            model_name='worksobjectproperty',
            name='file_download_description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Fichier (à télécharger)'),
        ),
        migrations.AlterField(
            model_name='worksobjectproperty',
            name='input_type',
            field=models.CharField(choices=[('address', 'Adresse'), ('checkbox', 'Case à cocher'), ('list_multiple', 'Choix multiple'), ('list_single', 'Choix simple'), ('date', 'Date'), ('file', 'Fichier'), ('number', 'Nombre'), ('text', 'Texte'), ('regex', 'Texte (regex)'), ('title', 'Titre'), ('file_download', 'Fichier (à télécharger)')], max_length=30, verbose_name='type de caractéristique'),
        ),
    ]
