# Generated by Django 3.2.12 on 2022-04-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0061_add_helptext_for_custom_login_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permitdepartment',
            name='integrator',
            field=models.IntegerField(default=0, verbose_name='Groupe des administrateurs'),
        ),
    ]
