# Generated by Django 3.2.12 on 2022-04-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0061_anonymous_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksobjecttype',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='Demandes anonymes uniquement'),
        ),
    ]
