# Generated by Django 3.2.12 on 2022-04-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0061_add_works_object_property_file_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitrequestamendproperty',
            name='can_always_update',
            field=models.BooleanField(default=False, verbose_name='Editable même après classement de la demande'),
        ),
    ]
