# Generated by Django 3.2.12 on 2022-04-11 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0061_add_works_object_property_file_download'),
        ('permits', '0062_anonymous_wot'),
    ]

    operations = [
    ]
