# Generated by Django 3.2.12 on 2022-04-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0062_permitrequestcomplementarydocument_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permitrequestcomplementarydocument',
            name='authorised_departments',
            field=models.ManyToManyField(db_table='permits_authorised_departments', to='permits.PermitDepartment', verbose_name='Département autorisé à visualiser le document'),
        ),
    ]
