# Generated by Django 3.2.12 on 2022-04-13 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0062_add_field_can_always_update_in_PermitRequestAmendProperty'),
        ('permits', '0063_merge_20220411_1953'),
    ]

    operations = [
    ]
