# Generated by Django 3.2.12 on 2022-03-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0063_anonymous_requests_users_and_wots'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksobjecttype',
            name='can_always_update',
            field=models.BooleanField(default=False, verbose_name='Demande modifiable en tous temps par le secrétariat'),
        ),
    ]
