# Generated by Django 3.2.12 on 2022-04-05 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permits', '0063_alter_permitrequestcomplementarydocument_authorised_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermitRequestInquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('documents', models.ManyToManyField(to='permits.PermitRequestComplementaryDocument', verbose_name='Documents complémentaire')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Demandeur de l'enquête")),
            ],
        ),
    ]
