# Generated by Django 3.2.13 on 2022-04-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0065_add_filter_and_geometry_storage_for_address_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksobjectproperty',
            name='input_type',
            field=models.CharField(choices=[('address', 'Adresse'), ('checkbox', 'Case à cocher'), ('list_multiple', 'Choix multiple'), ('list_single', 'Choix simple'), ('date', 'Date'), ('file', 'Fichier'), ('file_download', 'Fichier (à télécharger)'), ('number', 'Nombre'), ('parcel', 'Parcelle'), ('text', 'Texte'), ('regex', 'Texte (regex)'), ('title', 'Titre')], max_length=30, verbose_name='type de caractéristique'),
        ),
    ]
