# Generated by Django 3.2.13 on 2022-05-06 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0066_adapt_admin_texts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permitadministrativeentity',
            options={'permissions': [('see_private_requests', 'Voir les demandes restreintes')], 'verbose_name': "1.1 Configuration de l'entité administrative (commune, organisation)", 'verbose_name_plural': '1.1 Configuration des entités administratives (commune, organisation)'},
        ),
        migrations.AlterModelOptions(
            name='permitrequestamendproperty',
            options={'verbose_name': '2.2 Configuration du champ de traitement des demandes', 'verbose_name_plural': '2.2 Configuration des champs de traitement des demandes'},
        ),
        migrations.AlterModelOptions(
            name='worksobjecttype',
            options={'verbose_name': '1.4 Configuration du type-objet-entité', 'verbose_name_plural': '1.4 Configuration des type-objet-entité'},
        ),
        migrations.AlterField(
            model_name='historicalpermitrequest',
            name='administrative_entity',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='permits.permitadministrativeentity', verbose_name='entité administrative'),
        ),
        migrations.AlterField(
            model_name='permitrequest',
            name='administrative_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permit_requests', to='permits.permitadministrativeentity', verbose_name='entité administrative'),
        ),
    ]
