# Generated by Django 3.2.12 on 2022-03-29 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0066_auto_20220329_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitrequestcomplementarydocument',
            name='document_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='permits.complementarydocumenttype', verbose_name='Type du document'),
        ),
    ]
