# Generated by Django 3.2.13 on 2022-05-30 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('permits', '0069_rename_short_name_and_is_public_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_permits.printblock_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='PrintSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PrintBlockContacts',
            fields=[
                ('printblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permits.printblock')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('permits.printblock',),
        ),
        migrations.CreateModel(
            name='PrintBlockMap',
            fields=[
                ('printblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permits.printblock')),
                ('url', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('permits.printblock',),
        ),
        migrations.CreateModel(
            name='PrintBlockParagraph',
            fields=[
                ('printblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permits.printblock')),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('permits.printblock',),
        ),
        migrations.CreateModel(
            name='PrintBlockValidation',
            fields=[
                ('printblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permits.printblock')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('permits.printblock',),
        ),
        migrations.AddField(
            model_name='printblock',
            name='print_setup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permits.printsetup'),
        ),
        migrations.AddField(
            model_name='worksobjecttype',
            name='print_setups',
            field=models.ManyToManyField(to='permits.PrintSetup'),
        ),
    ]
