# Generated by Django 3.2.13 on 2022-05-30 12:14

from django.db import migrations, models
import streamfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0069_rename_short_name_and_is_public_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintBlockContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PrintBlockMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PrintBlockParagraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PrintBlockValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PrintSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('stream', streamfield.fields.StreamField(blank=True, default='[]')),
            ],
            options={
                'verbose_name': "5.1 Configuration de l'impression",
                'verbose_name_plural': '5.1 Configuration des impressions',
            },
        ),
        migrations.AddField(
            model_name='worksobjecttype',
            name='print_setups',
            field=models.ManyToManyField(to='permits.PrintSetup'),
        ),
    ]
