# Generated by Django 3.2.13 on 2022-06-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0070_publish_fields_for_public_permitrequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksobjecttype',
            name='can_have_multiple_ranges',
            field=models.BooleanField(default=False, verbose_name='Peut avoir plusieurs plages'),
        ),
    ]
