# Generated by Django 3.2.13 on 2022-05-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0070_auto_20220530_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='printblockcontacts',
            name='content',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='printblockvalidation',
            name='content',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
    ]
