# Generated by Django 3.2.13 on 2022-05-30 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0070_auto_20220530_1414'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrintBlockContacts',
        ),
        migrations.DeleteModel(
            name='PrintBlockMap',
        ),
        migrations.DeleteModel(
            name='PrintBlockParagraph',
        ),
        migrations.DeleteModel(
            name='PrintBlockValidation',
        ),
    ]
