# Generated by Django 3.2.13 on 2022-06-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0071_add_complementary_documents_inquiry_and_archived_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksobjecttype',
            name='document_enabled',
            field=models.BooleanField(default=False, verbose_name='Activer le module gestion des documents'),
        ),
        migrations.AddField(
            model_name='worksobjecttype',
            name='publication_enabled',
            field=models.BooleanField(default=False, verbose_name='Activer le module de publication'),
        ),
    ]
