# Generated by Django 3.2.13 on 2022-05-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0071_auto_20220530_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='printsetup',
            name='background',
            field=models.ImageField(blank=True, help_text='Arrière-plan', null=True, upload_to=''),
        ),
    ]
