# Generated by Django 3.2.13 on 2022-06-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
        ("permits", "0071_add_complementary_documents_inquiry_and_archived_requests"),
    ]

    operations = [
        migrations.AddField(
            model_name="worksobjecttype",
            name="reports",
            field=models.ManyToManyField(
                related_name="worksobjecttypes", to="reports.Report"
            ),
        ),
    ]
