# Generated by Django 3.2.13 on 2022-05-02 09:36

from django.db import migrations
import permits.fields


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0071_delete_historicalpermitrequestinquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permitrequestcomplementarydocument',
            name='document',
            field=permits.fields.ComplementaryDocumentFileField(storage=permits.fields.PrivateFileSystemStorage(), upload_to='', verbose_name='Document'),
        ),
    ]
