# Generated by Django 3.2.13 on 2022-05-30 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0071_auto_20220530_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='printblockparagraph',
            name='title',
            field=models.CharField(default='untitled', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='printblock',
            name='print_setup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='permits.printsetup'),
        ),
    ]
