# Generated by Django 3.2.13 on 2022-06-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0071_add_complementary_documents_inquiry_and_archived_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksobjecttype',
            name='document_enabled',
            field=models.BooleanField(default=False, verbose_name='Activer la gestion des documents'),
        ),
        migrations.AddField(
            model_name='worksobjecttype',
            name='publication_enabled',
            field=models.BooleanField(default=False, verbose_name='Activer la gestion de la publication'),
        ),
        migrations.AlterField(
            model_name='historicalpermitrequest',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Brouillon'), (1, 'Envoyée, en attente de traitement'), (4, 'Demande de compléments'), (3, 'En traitement'), (5, 'En validation'), (2, 'Approuvée'), (6, 'Refusée'), (7, 'Réceptionnée'), (8, 'Consultation publique en cours'), (9, 'Archivée')], default=0, verbose_name='état'),
        ),
        migrations.AlterField(
            model_name='permitrequest',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Brouillon'), (1, 'Envoyée, en attente de traitement'), (4, 'Demande de compléments'), (3, 'En traitement'), (5, 'En validation'), (2, 'Approuvée'), (6, 'Refusée'), (7, 'Réceptionnée'), (8, 'Consultation publique en cours'), (9, 'Archivée')], default=0, verbose_name='état'),
        ),
        migrations.AlterField(
            model_name='permitworkflowstatus',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Brouillon'), (1, 'Envoyée, en attente de traitement'), (4, 'Demande de compléments'), (3, 'En traitement'), (5, 'En validation'), (2, 'Approuvée'), (6, 'Refusée'), (7, 'Réceptionnée'), (8, 'Consultation publique en cours'), (9, 'Archivée')], verbose_name='statut'),
        ),
    ]
