# Generated by Django 3.2.13 on 2022-05-30 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0072_printsetup_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('page_size', models.CharField(choices=[('297,210', 'A4 portrait'), ('210,297', 'A4 paysage')], default='297,210', max_length=255)),
                ('margin_top', models.PositiveIntegerField(default=10)),
                ('margin_right', models.PositiveIntegerField(default=10)),
                ('margin_bottom', models.PositiveIntegerField(default=10)),
                ('margin_left', models.PositiveIntegerField(default=10)),
                ('background', models.ImageField(blank=True, help_text='Arrière-plan', null=True, upload_to='')),
            ],
            options={
                'verbose_name': "5.1 Configuration du modèle d'impression",
                'verbose_name_plural': "5.1 Configuration des modèles d'impressions",
            },
        ),
        migrations.AlterModelOptions(
            name='printsetup',
            options={'verbose_name': "5.2 Configuration de l'impression", 'verbose_name_plural': '5.2 Configuration des impressions'},
        ),
        migrations.RemoveField(
            model_name='printsetup',
            name='background',
        ),
        migrations.AddField(
            model_name='printsetup',
            name='layout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='permits.printlayout'),
            preserve_default=False,
        ),
    ]
