# Generated by Django 3.2.13 on 2022-05-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0072_auto_20220530_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printblock',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='printblock',
            name='position',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Position'),
        ),
    ]
