# Generated by Django 3.2.13 on 2022-06-09 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0072_worksobjecttype_reports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksobjecttype',
            name='reports',
        ),
    ]
