# Generated by Django 3.2.13 on 2022-05-30 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0073_auto_20220530_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printblock',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RemoveField(
            model_name='printblock',
            name='position',
        ),
    ]
