# Generated by Django 3.2.13 on 2022-05-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0073_auto_20220530_1628'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrintSetup',
            new_name='Report',
        ),
        migrations.RenameModel(
            old_name='PrintLayout',
            new_name='ReportLayout',
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': '5.2 Configuration du rapport', 'verbose_name_plural': '5.2 Configuration des rapports'},
        ),
        migrations.AlterModelOptions(
            name='reportlayout',
            options={'verbose_name': "5.1 Configuration du modèle d'impression de rapport", 'verbose_name_plural': "5.1 Configuration des modèles d'impression de rapport"},
        ),
        migrations.RemoveField(
            model_name='worksobjecttype',
            name='print_setups',
        ),
        migrations.AddField(
            model_name='worksobjecttype',
            name='reports',
            field=models.ManyToManyField(related_name='worksobjecttypes', to='permits.Report'),
        ),
    ]
