# Generated by Django 3.2.13 on 2022-06-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
        ("permits", "0073_filter_documenttype_for_integrator"),
    ]

    operations = [
        migrations.AddField(
            model_name="worksobjecttype",
            name="reports",
            field=models.ManyToManyField(
                blank=True,
                related_name="_permits_worksobjecttype_reports_+",
                to="reports.Report",
            ),
        ),
    ]
