# Generated by Django 3.2.13 on 2022-06-15 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("permits", "0074_worksobjecttype_reports"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="qgisproject",
            name="works_object_type",
        ),
        migrations.DeleteModel(
            name="QgisGeneratedDocument",
        ),
        migrations.DeleteModel(
            name="QgisProject",
        ),
    ]
