# Generated by Django 3.2.13 on 2022-05-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0074_auto_20220530_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportlayout',
            name='page_size',
        ),
        migrations.AddField(
            model_name='reportlayout',
            name='height',
            field=models.PositiveIntegerField(default=297),
        ),
        migrations.AddField(
            model_name='reportlayout',
            name='width',
            field=models.PositiveIntegerField(default=210),
        ),
    ]
