# Generated by Django 3.2.13 on 2022-04-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0074_auto_20220427_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedpermitrequest',
            name='archived_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
