# Generated by Django 3.2.13 on 2022-06-22 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("permits", "0075_auto_20220615_1555"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="worksobjecttype",
            name="reports",
        ),
    ]
