# Generated by Django 3.2.13 on 2022-06-23 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("permits", "0075_add_can_have_multiple_ranges_in_wot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="qgisgenerateddocument",
            name="permit_request",
        ),
        migrations.RemoveField(
            model_name="qgisgenerateddocument",
            name="qgis_project",
        ),
        migrations.RemoveField(
            model_name="qgisproject",
            name="works_object_type",
        ),
    ]
