# Generated by Django 3.2.13 on 2022-06-29 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permits", "0075_add_can_have_multiple_ranges_in_wot"),
    ]

    operations = [
        migrations.CreateModel(
            name="PermitSite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "templatename",
                    models.CharField(
                        blank=True,
                        help_text="Permettant d'afficher la page de login par l'url: https://geocity.ch/?template=vevey",
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Seuls les caractères sans accents et les chiffres sont autorisés. Les espaces et autres caractères spéciaux ne sont pas autorisés",
                                regex="^[a-zA-Z0-9_]*$",
                            )
                        ],
                        verbose_name="Identifiant",
                    ),
                ),
                (
                    "application_title",
                    models.CharField(blank=True, max_length=255, verbose_name="Titre"),
                ),
                (
                    "application_subtitle",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Sous-titre"
                    ),
                ),
                (
                    "application_description",
                    models.TextField(
                        blank=True, max_length=2048, verbose_name="Description"
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(
                        blank=True,
                        upload_to="background_images/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["svg", "png", "jpg", "jpeg"]
                            )
                        ],
                        verbose_name="Image de fond",
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        default="#FFFFFF",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Ce code de couleur n'est pas valide. Il doit s'agir d'un code couleur HTML, par exemple #000000.",
                                regex="^\\#([a-fA-F0-9]{6}|[a-fA-F0-9]{3})$",
                            )
                        ],
                        verbose_name="Couleur unie du fond",
                    ),
                ),
                (
                    "login_background_color",
                    models.CharField(
                        default="#FFFFFF",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Ce code de couleur n'est pas valide. Il doit s'agir d'un code couleur HTML, par exemple #000000.",
                                regex="^\\#([a-fA-F0-9]{6}|[a-fA-F0-9]{3})$",
                            )
                        ],
                        verbose_name="Couleur unie du fond login",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#008c6f",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Ce code de couleur n'est pas valide. Il doit s'agir d'un code couleur HTML, par exemple #000000.",
                                regex="^\\#([a-fA-F0-9]{6}|[a-fA-F0-9]{3})$",
                            )
                        ],
                        verbose_name="Couleur de thème principale",
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#01755d",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Ce code de couleur n'est pas valide. Il doit s'agir d'un code couleur HTML, par exemple #000000.",
                                regex="^\\#([a-fA-F0-9]{6}|[a-fA-F0-9]{3})$",
                            )
                        ],
                        verbose_name="Couleur de thème secondaire",
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        default="#000000",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Ce code de couleur n'est pas valide. Il doit s'agir d'un code couleur HTML, par exemple #000000.",
                                regex="^\\#([a-fA-F0-9]{6}|[a-fA-F0-9]{3})$",
                            )
                        ],
                        verbose_name="Couleur du texte",
                    ),
                ),
                (
                    "title_color",
                    models.CharField(
                        default="#000000",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Ce code de couleur n'est pas valide. Il doit s'agir d'un code couleur HTML, par exemple #000000.",
                                regex="^\\#([a-fA-F0-9]{6}|[a-fA-F0-9]{3})$",
                            )
                        ],
                        verbose_name="Couleur du titre",
                    ),
                ),
                (
                    "table_color",
                    models.CharField(
                        default="#212529",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Ce code de couleur n'est pas valide. Il doit s'agir d'un code couleur HTML, par exemple #000000.",
                                regex="^\\#([a-fA-F0-9]{6}|[a-fA-F0-9]{3})$",
                            )
                        ],
                        verbose_name="Couleur du texte dans les tableaux",
                    ),
                ),
            ],
            options={
                "verbose_name": "4.1 Configuration de la page de login",
                "verbose_name_plural": "4.1 Configuration des pages de login",
            },
        ),
        migrations.DeleteModel(
            name="TemplateCustomization",
        ),
        migrations.AddConstraint(
            model_name="permitsite",
            constraint=models.UniqueConstraint(
                fields=("templatename",), name="unique_templatename"
            ),
        ),
    ]
