# Generated by Django 3.2.13 on 2022-06-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0076_reportlayout_font'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportlayout',
            name='background',
            field=models.ImageField(blank=True, help_text='Image d\'arrière plan ("papier à en-tête")', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='reportlayout',
            name='font',
            field=models.CharField(blank=True, help_text='La liste des polices disponbiles est visible sur <a href="https://fonts.google.com/" target="_blank">Goole Fonts</a>', max_length=1024, null=True),
        ),
    ]
