# Generated by Django 3.2.13 on 2022-06-23 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permits", "0076_remove_print_v1_models"),
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="complementarydocumenttype",
            name="reports",
            field=models.ManyToManyField(
                blank=True,
                related_name="_permits_complementarydocumenttype_reports_+",
                to="reports.Report",
            ),
        ),
        migrations.AlterField(
            model_name="complementarydocumenttype",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="permits.complementarydocumenttype",
                verbose_name="Type parent",
            ),
        ),
        migrations.AlterField(
            model_name="complementarydocumenttype",
            name="work_object_types",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_types",
                to="permits.worksobjecttype",
                verbose_name="Objets",
            ),
        ),
        migrations.DeleteModel(
            name="QgisGeneratedDocument",
        ),
        migrations.DeleteModel(
            name="QgisProject",
        ),
    ]
