# Generated by Django 3.2.13 on 2022-06-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_auto_20220622_1511"),
        ("permits", "0076_remove_worksobjecttype_reports"),
    ]

    operations = [
        migrations.AddField(
            model_name="complementarydocumenttype",
            name="reports",
            field=models.ManyToManyField(
                blank=True,
                related_name="_permits_complementarydocumenttype_reports_+",
                to="reports.Report",
            ),
        ),
    ]
