# Generated by Django 3.2.13 on 2022-06-22 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permits", "0077_complementarydocumenttype_reports"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complementarydocumenttype",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="permits.complementarydocumenttype",
                verbose_name="Type parent",
            ),
        ),
        migrations.AlterField(
            model_name="complementarydocumenttype",
            name="work_object_types",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_types",
                to="permits.worksobjecttype",
                verbose_name="Objets",
            ),
        ),
    ]
