# Generated by Django 3.2.15 on 2022-08-19 14:39

import django.core.validators
from django.db import migrations, models

import permits.fields


class Migration(migrations.Migration):

    dependencies = [
        ("permits", "0078_create_web_site"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TemplateCustomization",
        ),
        migrations.AddField(
            model_name="site",
            name="application_description",
            field=models.TextField(
                blank=True, max_length=2048, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="application_subtitle",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Sous-titre"
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="application_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="Titre"),
        ),
        migrations.AddField(
            model_name="site",
            name="background_color",
            field=permits.fields.ColorField(
                default="#FFFFFF",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Ce code de couleur n'est pas valide. Il doit s'agir d'un code couleur HTML, par exemple #000000.",
                        regex="^\\#([a-fA-F0-9]{6}|[a-fA-F0-9]{3})$",
                    )
                ],
                verbose_name="Couleur unie du fond",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="background_image",
            field=models.ImageField(
                blank=True,
                upload_to="background_images/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["svg", "png", "jpg", "jpeg"]
                    )
                ],
                verbose_name="Image de fond",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="login_background_color",
            field=permits.fields.ColorField(
                default="#FFFFFF",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Ce code de couleur n'est pas valide. Il doit s'agir d'un code couleur HTML, par exemple #000000.",
                        regex="^\\#([a-fA-F0-9]{6}|[a-fA-F0-9]{3})$",
                    )
                ],
                verbose_name="Couleur unie du fond login",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="primary_color",
            field=permits.fields.ColorField(
                default="#008c6f",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Ce code de couleur n'est pas valide. Il doit s'agir d'un code couleur HTML, par exemple #000000.",
                        regex="^\\#([a-fA-F0-9]{6}|[a-fA-F0-9]{3})$",
                    )
                ],
                verbose_name="Couleur de thème principale",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="secondary_color",
            field=permits.fields.ColorField(
                default="#01755d",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Ce code de couleur n'est pas valide. Il doit s'agir d'un code couleur HTML, par exemple #000000.",
                        regex="^\\#([a-fA-F0-9]{6}|[a-fA-F0-9]{3})$",
                    )
                ],
                verbose_name="Couleur de thème secondaire",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="table_color",
            field=permits.fields.ColorField(
                default="#212529",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Ce code de couleur n'est pas valide. Il doit s'agir d'un code couleur HTML, par exemple #000000.",
                        regex="^\\#([a-fA-F0-9]{6}|[a-fA-F0-9]{3})$",
                    )
                ],
                verbose_name="Couleur du texte dans les tableaux",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="text_color",
            field=permits.fields.ColorField(
                default="#000000",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Ce code de couleur n'est pas valide. Il doit s'agir d'un code couleur HTML, par exemple #000000.",
                        regex="^\\#([a-fA-F0-9]{6}|[a-fA-F0-9]{3})$",
                    )
                ],
                verbose_name="Couleur du texte",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="title_color",
            field=permits.fields.ColorField(
                default="#000000",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Ce code de couleur n'est pas valide. Il doit s'agir d'un code couleur HTML, par exemple #000000.",
                        regex="^\\#([a-fA-F0-9]{6}|[a-fA-F0-9]{3})$",
                    )
                ],
                verbose_name="Couleur du titre",
            ),
        ),
    ]
