# Generated by Django 3.2.15 on 2022-09-01 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("socialaccount", "0003_extra_data_default_dict"),
        ("sites", "0002_alter_domain_unique"),
        ("permits", "0079_add_iban_to_permitauthor_and_fix_typo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "integrator",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="auth.group",
                        verbose_name="Groupe des administrateurs",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="sites.site"
                    ),
                ),
            ],
            options={
                "verbose_name": "1.0 Configuration du sous-domaine",
                "verbose_name_plural": "1.0 Configuration des sous-domaines",
            },
        ),
        migrations.DeleteModel(
            name="Site",
        ),
    ]
