# Generated by Django 3.2.13 on 2022-07-04 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0008_change_defaut_atlas_template_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SectionCreditor",
            fields=[
                (
                    "section_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="reports.section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adresse de facturation",
            },
            bases=("reports.section",),
        ),
    ]
