# Generated by Django 3.2.15 on 2022-10-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0003_migrate_permits_data"),
        ("reports", "0009_add_section_creditor"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="submissions_document_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="_reports_report_submissions_document_types_+",
                to="submissions.ComplementaryDocumentType",
            ),
        ),
    ]
