# Generated by Django 3.2.15 on 2022-10-26 12:17

from django.db import migrations

from geocity.migrations import bulk_create


def migrate_permits_data(apps, schema_editor):
    def create_document_type_through():
        Report = apps.get_model("reports", "Report")

        for document_type_through in Report.document_types.through.objects.all():
            yield Report.submissions_document_types.through(
                id=document_type_through.pk,
                report_id=document_type_through.report_id,
                complementarydocumenttype_id=document_type_through.complementarydocumenttype_id,
            )

    bulk_create(create_document_type_through())


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0010_report_submissions_document_types"),
    ]

    operations = [migrations.RunPython(migrate_permits_data)]
