# Generated by Django 3.2.15 on 2022-11-02 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0010_report_submissions_document_types"),
    ]

    operations = [
        migrations.RenameField(
            model_name="report",
            old_name="submissions_document_types",
            new_name="document_types",
        ),
    ]
