# Generated by Django 3.2.15 on 2022-11-07 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_report_document_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'permissions': [('can_generate_pdf', 'Générer des documents pdf')]},
        ),
        migrations.AlterModelOptions(
            name='reportlayout',
            options={},
        ),
    ]
