# Generated by Django 4.1 on 2022-11-22 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0004_new_admin_models_and_metadata"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("reports", "0014_adapt_models_for_new_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="document_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                to="submissions.complementarydocumenttype",
                verbose_name="Types de documents",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
    ]
