# Generated by Django 4.1.4 on 2023-01-19 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("reports", "0018_alter_sectionparagraph_content_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="complementarydocumenttypeforadminsite",
            options={
                "verbose_name": "3.2 Type de document",
                "verbose_name_plural": "3.2 Type de document",
            },
        ),
        migrations.AddField(
            model_name="report",
            name="is_visible",
            field=models.BooleanField(
                default=True,
                help_text="Rendre le modèle visible dans la liste des documents et impressions (décocher pour les modèles de confirmation / remboursement de paiement)",
                verbose_name="Visible",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="integrator",
            field=models.ForeignKey(
                limit_choices_to={"permit_department__is_integrator_admin": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="auth.group",
                verbose_name="Groupe des administrateurs",
            ),
        ),
        migrations.AlterField(
            model_name="reportlayout",
            name="font",
            field=models.CharField(
                blank=True,
                help_text='La liste des polices disponibles est visible sur <a href="https://fonts.google.com/" target="_blank">Google Fonts</a>',
                max_length=1024,
                null=True,
                verbose_name="Police",
            ),
        ),
        migrations.AlterField(
            model_name="reportlayout",
            name="integrator",
            field=models.ForeignKey(
                limit_choices_to={"permit_department__is_integrator_admin": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="auth.group",
                verbose_name="Groupe des administrateurs",
            ),
        ),
    ]
