# Generated by Django 4.1.4 on 2022-12-22 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("reports", "0016_change_admin_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="complementarydocumenttypeforadminsite",
            options={
                "verbose_name": "3.2 Type de document",
                "verbose_name_plural": "3.2 Type de document",
            },
        ),
        migrations.AlterField(
            model_name="report",
            name="integrator",
            field=models.ForeignKey(
                limit_choices_to={"permit_department__is_integrator_admin": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="auth.group",
                verbose_name="Groupe des administrateurs",
            ),
        ),
        migrations.AlterField(
            model_name="reportlayout",
            name="integrator",
            field=models.ForeignKey(
                limit_choices_to={"permit_department__is_integrator_admin": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="auth.group",
                verbose_name="Groupe des administrateurs",
            ),
        ),
    ]
