# Generated by Django 4.1.4 on 2023-01-10 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0018_alter_sectionparagraph_content_and_more"),
        (
            "reports",
            "0019_alter_complementarydocumenttypeforadminsite_options_and_more",
        ),
    ]

    operations = []
