# Generated by Django 4.1.4 on 2023-02-07 10:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import geocity.apps.reports.fields
import geocity.apps.reports.models
import geocity.fields


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        (
            "reports",
            "0019_alter_complementarydocumenttypeforadminsite_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SectionMailing",
            fields=[
                (
                    "section_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="reports.section",
                    ),
                ),
                (
                    "is_recommended",
                    models.BooleanField(
                        default=False,
                        help_text='Ajoute le texte "RECOMMANDEE" en première ligne',
                        verbose_name="Recommandée",
                    ),
                ),
                (
                    "padding_top",
                    models.PositiveIntegerField(
                        default=20,
                        help_text="Espace vide au dessus afin de placer le texte au bon endroit (en pixels). Augmenter la valeur fait descendre le texte",
                        verbose_name="Espace vide au dessus",
                    ),
                ),
            ],
            options={
                "verbose_name": "Publipostage",
            },
            bases=("reports.section",),
        ),
        migrations.CreateModel(
            name="Style",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("@bottom-center", "Pied de page - Centre"),
                            ("@bottom-left", "Pied de page - Gauche"),
                            ("@bottom-left-corner", "Pied de page - Coin gauche"),
                            ("@bottom-right", "Pied de page - Droite"),
                            ("@bottom-right-corner", "Pied de page - Coin Droite"),
                            ("@left-bottom", "Bordure gauche - Bas de page"),
                            ("@left-middle", "Bordure gauche - Milieu de page"),
                            ("@left-top", "Bordure gauche - Haut de page"),
                            ("@right-bottom", "Bordure droite - Bas de page"),
                            ("@right-middle", "Bordure droite - Milieu de page"),
                            ("@right-top", "Bordure droite - Haut de page"),
                            ("@top-center", "En-tête - Centre"),
                            ("@top-left", "En-tête - Gauche"),
                            ("@top-left-corner", "En-tête - Coin gauche"),
                            ("@top-right", "En-tête - Droite"),
                            ("@top-right-corner", "En-tête - Coin Droite"),
                        ],
                        default="@bottom-center",
                        max_length=255,
                        verbose_name="Emplacement",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=geocity.apps.reports.models.NON_POLYMORPHIC_CASCADE,
                        related_name="styles",
                        to="reports.report",
                    ),
                ),
            ],
            options={
                "verbose_name": "Style",
                "verbose_name_plural": "Styles",
            },
        ),
        migrations.RenameField(
            model_name="reportlayout",
            old_name="font",
            new_name="font_family",
        ),
        migrations.AddField(
            model_name="reportlayout",
            name="font_size_section",
            field=models.PositiveIntegerField(
                default=12,
                help_text="Taille de la police (en pixels). S'applique à tous les paragraphes",
                verbose_name="Taille de la police des paragraphes",
            ),
        ),
        migrations.AddField(
            model_name="reportlayout",
            name="font_size_style",
            field=models.PositiveIntegerField(
                default=11,
                help_text="Taille de la police (en pixels). S'applique à tous les style (en-tête, pied de page et bordures)",
                verbose_name="Taille de la police des style",
            ),
        ),
        migrations.AddField(
            model_name="sectionamendproperty",
            name="title",
            field=models.CharField(
                blank=True,
                default="Commentaire·s du secrétariat",
                max_length=2000,
                verbose_name="Titre",
            ),
        ),
        migrations.AddField(
            model_name="sectionamendproperty",
            name="title_size",
            field=models.CharField(
                choices=[
                    ("h1", "h1"),
                    ("h2", "h2"),
                    ("h3", "h3"),
                    ("h4", "h4"),
                    ("h5", "h5"),
                    ("h6", "h6"),
                ],
                default="h2",
                help_text="S'applique au titre des tous les paragraphes. h1 taille la plus grande, h6 la plus petite",
                max_length=255,
                verbose_name="Taille des titres",
            ),
        ),
        migrations.AddField(
            model_name="sectionauthor",
            name="title",
            field=models.CharField(
                blank=True,
                default="Auteur·e de la demande",
                max_length=2000,
                verbose_name="Titre",
            ),
        ),
        migrations.AddField(
            model_name="sectionauthor",
            name="title_size",
            field=models.CharField(
                choices=[
                    ("h1", "h1"),
                    ("h2", "h2"),
                    ("h3", "h3"),
                    ("h4", "h4"),
                    ("h5", "h5"),
                    ("h6", "h6"),
                ],
                default="h2",
                help_text="S'applique au titre des tous les paragraphes. h1 taille la plus grande, h6 la plus petite",
                max_length=255,
                verbose_name="Taille des titres",
            ),
        ),
        migrations.AddField(
            model_name="sectioncontact",
            name="title",
            field=models.CharField(
                blank=True, default="Contact·s", max_length=2000, verbose_name="Titre"
            ),
        ),
        migrations.AddField(
            model_name="sectioncontact",
            name="title_size",
            field=models.CharField(
                choices=[
                    ("h1", "h1"),
                    ("h2", "h2"),
                    ("h3", "h3"),
                    ("h4", "h4"),
                    ("h5", "h5"),
                    ("h6", "h6"),
                ],
                default="h2",
                help_text="S'applique au titre des tous les paragraphes. h1 taille la plus grande, h6 la plus petite",
                max_length=255,
                verbose_name="Taille des titres",
            ),
        ),
        migrations.AddField(
            model_name="sectioncreditor",
            name="title",
            field=models.CharField(
                blank=True,
                default="Adresse de facturation",
                max_length=2000,
                verbose_name="Titre",
            ),
        ),
        migrations.AddField(
            model_name="sectioncreditor",
            name="title_size",
            field=models.CharField(
                choices=[
                    ("h1", "h1"),
                    ("h2", "h2"),
                    ("h3", "h3"),
                    ("h4", "h4"),
                    ("h5", "h5"),
                    ("h6", "h6"),
                ],
                default="h2",
                help_text="S'applique au titre des tous les paragraphes. h1 taille la plus grande, h6 la plus petite",
                max_length=255,
                verbose_name="Taille des titres",
            ),
        ),
        migrations.AddField(
            model_name="sectiondetail",
            name="title",
            field=models.CharField(
                blank=True,
                default="Propriété·s de la demande",
                max_length=2000,
                verbose_name="Titre",
            ),
        ),
        migrations.AddField(
            model_name="sectiondetail",
            name="title_size",
            field=models.CharField(
                choices=[
                    ("h1", "h1"),
                    ("h2", "h2"),
                    ("h3", "h3"),
                    ("h4", "h4"),
                    ("h5", "h5"),
                    ("h6", "h6"),
                ],
                default="h2",
                help_text="S'applique au titre des tous les paragraphes. h1 taille la plus grande, h6 la plus petite",
                max_length=255,
                verbose_name="Taille des titres",
            ),
        ),
        migrations.AddField(
            model_name="sectionmap",
            name="title",
            field=models.CharField(
                blank=True,
                default="Localisation·s",
                max_length=2000,
                verbose_name="Titre",
            ),
        ),
        migrations.AddField(
            model_name="sectionmap",
            name="title_size",
            field=models.CharField(
                choices=[
                    ("h1", "h1"),
                    ("h2", "h2"),
                    ("h3", "h3"),
                    ("h4", "h4"),
                    ("h5", "h5"),
                    ("h6", "h6"),
                ],
                default="h2",
                help_text="S'applique au titre des tous les paragraphes. h1 taille la plus grande, h6 la plus petite",
                max_length=255,
                verbose_name="Taille des titres",
            ),
        ),
        migrations.AddField(
            model_name="sectionparagraph",
            name="title_size",
            field=models.CharField(
                choices=[
                    ("h1", "h1"),
                    ("h2", "h2"),
                    ("h3", "h3"),
                    ("h4", "h4"),
                    ("h5", "h5"),
                    ("h6", "h6"),
                ],
                default="h2",
                help_text="S'applique au titre des tous les paragraphes. h1 taille la plus grande, h6 la plus petite",
                max_length=255,
                verbose_name="Taille des titres",
            ),
        ),
        migrations.AddField(
            model_name="sectionparagraphright",
            name="title_size",
            field=models.CharField(
                choices=[
                    ("h1", "h1"),
                    ("h2", "h2"),
                    ("h3", "h3"),
                    ("h4", "h4"),
                    ("h5", "h5"),
                    ("h6", "h6"),
                ],
                default="h2",
                help_text="S'applique au titre des tous les paragraphes. h1 taille la plus grande, h6 la plus petite",
                max_length=255,
                verbose_name="Taille des titres",
            ),
        ),
        migrations.AddField(
            model_name="sectionplanning",
            name="title",
            field=models.CharField(
                blank=True, default="Planning", max_length=2000, verbose_name="Titre"
            ),
        ),
        migrations.AddField(
            model_name="sectionplanning",
            name="title_size",
            field=models.CharField(
                choices=[
                    ("h1", "h1"),
                    ("h2", "h2"),
                    ("h3", "h3"),
                    ("h4", "h4"),
                    ("h5", "h5"),
                    ("h6", "h6"),
                ],
                default="h2",
                help_text="S'applique au titre des tous les paragraphes. h1 taille la plus grande, h6 la plus petite",
                max_length=255,
                verbose_name="Taille des titres",
            ),
        ),
        migrations.AddField(
            model_name="sectionstatus",
            name="title",
            field=models.CharField(
                blank=True,
                default="Statut de la demande",
                max_length=2000,
                verbose_name="Titre",
            ),
        ),
        migrations.AddField(
            model_name="sectionstatus",
            name="title_size",
            field=models.CharField(
                choices=[
                    ("h1", "h1"),
                    ("h2", "h2"),
                    ("h3", "h3"),
                    ("h4", "h4"),
                    ("h5", "h5"),
                    ("h6", "h6"),
                ],
                default="h2",
                help_text="S'applique au titre des tous les paragraphes. h1 taille la plus grande, h6 la plus petite",
                max_length=255,
                verbose_name="Taille des titres",
            ),
        ),
        migrations.AddField(
            model_name="sectionvalidation",
            name="title",
            field=models.CharField(
                blank=True,
                default="Commentaire·s des services",
                max_length=2000,
                verbose_name="Titre",
            ),
        ),
        migrations.AddField(
            model_name="sectionvalidation",
            name="title_size",
            field=models.CharField(
                choices=[
                    ("h1", "h1"),
                    ("h2", "h2"),
                    ("h3", "h3"),
                    ("h4", "h4"),
                    ("h5", "h5"),
                    ("h6", "h6"),
                ],
                default="h2",
                help_text="S'applique au titre des tous les paragraphes. h1 taille la plus grande, h6 la plus petite",
                max_length=255,
                verbose_name="Taille des titres",
            ),
        ),
        migrations.AlterField(
            model_name="reportlayout",
            name="margin_bottom",
            field=models.PositiveIntegerField(default=15, verbose_name="Marge: bas"),
        ),
        migrations.AlterField(
            model_name="reportlayout",
            name="margin_left",
            field=models.PositiveIntegerField(default=15, verbose_name="Marge: gauche"),
        ),
        migrations.AlterField(
            model_name="reportlayout",
            name="margin_right",
            field=models.PositiveIntegerField(default=15, verbose_name="Marge: droite"),
        ),
        migrations.AlterField(
            model_name="reportlayout",
            name="margin_top",
            field=models.PositiveIntegerField(default=25, verbose_name="Marge: haut"),
        ),
        migrations.CreateModel(
            name="StyleDateTime",
            fields=[
                (
                    "style_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="reports.style",
                    ),
                ),
            ],
            options={
                "verbose_name": "Date et heure",
            },
            bases=("reports.style",),
        ),
        migrations.CreateModel(
            name="StyleLogo",
            fields=[
                (
                    "style_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="reports.style",
                    ),
                ),
                (
                    "logo",
                    geocity.apps.reports.fields.BackgroundFileField(
                        help_text="Image pour logo (PNG).",
                        storage=geocity.fields.PrivateFileSystemStorage(),
                        upload_to="backgound_paper",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png"]
                            )
                        ],
                        verbose_name="Logo",
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Défini la taille de l'image en %. Choisir un nombre compris entre 0 et 100",
                        verbose_name="Hauteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Logo",
            },
            bases=("reports.style",),
        ),
        migrations.CreateModel(
            name="StylePageNumber",
            fields=[
                (
                    "style_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="reports.style",
                    ),
                ),
            ],
            options={
                "verbose_name": "Numéro de page",
            },
            bases=("reports.style",),
        ),
        migrations.CreateModel(
            name="StyleParagraph",
            fields=[
                (
                    "style_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="reports.style",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Texte à afficher",
                        max_length=1024,
                        verbose_name="Contenu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Texte libre",
            },
            bases=("reports.style",),
        ),
    ]
