# Generated by Django 4.1.7 on 2023-03-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0020_headerfooter_sectionrecipient_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="section",
            name="padding_top",
        ),
        migrations.AddField(
            model_name="sectionamendproperty",
            name="padding_top",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Espace vide au dessus afin de placer le texte au bon endroit (en pixels). Augmenter la valeur fait descendre le texte",
                verbose_name="Espace vide au dessus",
            ),
        ),
        migrations.AddField(
            model_name="sectionauthor",
            name="padding_top",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Espace vide au dessus afin de placer le texte au bon endroit (en pixels). Augmenter la valeur fait descendre le texte",
                verbose_name="Espace vide au dessus",
            ),
        ),
        migrations.AddField(
            model_name="sectioncontact",
            name="padding_top",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Espace vide au dessus afin de placer le texte au bon endroit (en pixels). Augmenter la valeur fait descendre le texte",
                verbose_name="Espace vide au dessus",
            ),
        ),
        migrations.AddField(
            model_name="sectioncreditor",
            name="padding_top",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Espace vide au dessus afin de placer le texte au bon endroit (en pixels). Augmenter la valeur fait descendre le texte",
                verbose_name="Espace vide au dessus",
            ),
        ),
        migrations.AddField(
            model_name="sectiondetail",
            name="padding_top",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Espace vide au dessus afin de placer le texte au bon endroit (en pixels). Augmenter la valeur fait descendre le texte",
                verbose_name="Espace vide au dessus",
            ),
        ),
        migrations.AddField(
            model_name="sectionmap",
            name="padding_top",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Espace vide au dessus afin de placer le texte au bon endroit (en pixels). Augmenter la valeur fait descendre le texte",
                verbose_name="Espace vide au dessus",
            ),
        ),
        migrations.AddField(
            model_name="sectionparagraph",
            name="padding_top",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Espace vide au dessus afin de placer le texte au bon endroit (en pixels). Augmenter la valeur fait descendre le texte",
                verbose_name="Espace vide au dessus",
            ),
        ),
        migrations.AddField(
            model_name="sectionplanning",
            name="padding_top",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Espace vide au dessus afin de placer le texte au bon endroit (en pixels). Augmenter la valeur fait descendre le texte",
                verbose_name="Espace vide au dessus",
            ),
        ),
        migrations.AddField(
            model_name="sectionrecipient",
            name="padding_top",
            field=models.PositiveIntegerField(
                default=40,
                help_text="Espace vide au dessus afin de placer le texte au bon endroit (en pixels). Augmenter la valeur fait descendre le texte",
                verbose_name="Espace vide au dessus",
            ),
        ),
        migrations.AddField(
            model_name="sectionrecipient",
            name="uses_dynamic_recipient",
            field=models.BooleanField(
                default=True,
                help_text="Si le demande est saisie au nom d'une autre personne (requérant) celui-ci sera utilisé",
                verbose_name="Destinataire dynamique",
            ),
        ),
        migrations.AddField(
            model_name="sectionstatus",
            name="padding_top",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Espace vide au dessus afin de placer le texte au bon endroit (en pixels). Augmenter la valeur fait descendre le texte",
                verbose_name="Espace vide au dessus",
            ),
        ),
        migrations.AddField(
            model_name="sectionvalidation",
            name="padding_top",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Espace vide au dessus afin de placer le texte au bon endroit (en pixels). Augmenter la valeur fait descendre le texte",
                verbose_name="Espace vide au dessus",
            ),
        ),
    ]
