# Generated by Django 4.1.7 on 2023-03-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0020_headerfooter_sectionrecipient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectionrecipient",
            name="uses_dynamic_recipient",
            field=models.BooleanField(
                default=True,
                help_text="Si le demande est saisie au nom d'une autre personne (requérant) celui-ci sera utilisé",
                verbose_name="Destinataire dynamique",
            ),
        ),
    ]
