# Generated by Django 4.1.4 on 2023-02-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0020_headerfooter_sectionrecipient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="headerfooterparagraph",
            name="text_align",
            field=models.CharField(
                choices=[
                    ("left", "Gauche"),
                    ("right", "Droite"),
                    ("center", "Centre"),
                    ("justify", "Justifié"),
                ],
                default="left",
                max_length=255,
                verbose_name="Alignement du texte",
            ),
        ),
    ]
