# Generated by Django 4.1.4 on 2023-02-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0021_headerfooterparagraph_text_align"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectiondetail",
            name="line_height",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=12,
                help_text="Espace (en pixels) entre deux détails",
                null=True,
                verbose_name="Interligne",
            ),
        ),
    ]
