# Generated by Django 4.1.4 on 2023-02-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0021_alter_reportlayout_background_alter_stylelogo_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="style",
            name="page",
            field=models.PositiveSmallIntegerField(
                choices=[
                    ("0", "Toutes les pages"),
                    ("1", "Première page"),
                    ("2", "Toutes sauf la première page"),
                ],
                default="0",
                help_text="Choix des pages auxquelles doit s'appliquer le style",
                verbose_name="Page",
            ),
        ),
    ]
