# Generated by Django 4.1.7 on 2023-03-28 12:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0022_sectionhorizontalrule_padding_top"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectionparagraph",
            name="content",
            field=ckeditor.fields.RichTextField(
                help_text='Il est possible d\'inclure des variables et de la logique avec la <a href="https://jinja.palletsprojects.com/en/3.1.x/templates/" target="_blank">syntaxe Jinja</a>. Les variables de la demande sont accessible dans `{{request_data}}`, celles du formulaire dans `{{form_data}}`, celles des transactions dans `{{transaction_data}}`.',
                verbose_name="Contenu",
            ),
        ),
    ]
