# Generated by Django 4.1.4 on 2023-02-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0023_alter_style_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="is_new_page",
            field=models.BooleanField(
                default=False,
                help_text="Commencer cette section sur une nouvelle page ?",
                verbose_name="Nouvelle page",
            ),
        ),
    ]
