# Generated by Django 4.1.4 on 2023-02-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0024_section_is_new_page"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sectionmailing",
            old_name="padding_top",
            new_name="padding_top_mailing",
        ),
        migrations.AddField(
            model_name="section",
            name="padding_top",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Espace vide au dessus afin de placer le texte au bon endroit (en pixels). Augmenter la valeur fait descendre le texte",
                verbose_name="Espace vide au dessus",
            ),
        ),
    ]
