# Generated by Django 4.2.1 on 2023-06-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0025_rename_api_price_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sectiondetail",
            name="show_form_name",
        ),
        migrations.AddField(
            model_name="sectiondetail",
            name="form_name",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Aucun"),
                    (1, "Formulaire"),
                    (2, "Catégorie"),
                    (3, "Formulaire (Catégorie)"),
                ],
                default=3,
                help_text="Choix de la valeur à afficher pour le nom du formulaire",
                verbose_name="Affichage du nom du formulaire",
            ),
        ),
    ]
