# Generated by Django 4.1.4 on 2023-02-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0026_sectiondetail_show_form_name_sectiondetail_style"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectiondetail",
            name="style",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "champ: valeur"), (1, "champ    valeur")],
                default=0,
                help_text="Choisir le style d'affichage",
                verbose_name="Style",
            ),
        ),
    ]
