# Generated by Django 4.2.1 on 2023-06-15 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0027_remove_sectionamendproperty_show_form_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SectionBuildHelper",
            fields=[
                (
                    "section_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="reports.section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aide",
            },
            bases=("reports.section",),
        ),
    ]
