# Generated by Django 4.1.4 on 2023-02-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0027_alter_sectiondetail_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectiondetail",
            name="undesired_properties",
            field=models.CharField(
                blank=True,
                help_text="Liste de champs à masquer, séparés par des points virgules ';' correspondant aux titre des champs (ex: hauteur;largeur)",
                max_length=2000,
                null=True,
                verbose_name="Nom de champs a masquer",
            ),
        ),
    ]
