# Generated by Django 4.2.1 on 2023-06-15 16:21
import re

from django.db import migrations

from geocity.apps.api.services import convert_string_to_api_key

regex_pattern = r"\{\{form_data\.(amend_properties|request_properties)\.([\w.]+)\}\}"


def transform_string(match):
    property_path = match.group()

    string_beginning = property_path.split(".")[:-1]
    string_end = property_path.split(".")[-1]

    transformed = f"{'.'.join(string_beginning)}.fields.{convert_string_to_api_key(string_end)}.value"
    return transformed + "}}"


class Migration(migrations.Migration):
    def update_sectionparagraph(apps, schema_editor):

        SectionParagraph = apps.get_model("reports", "SectionParagraph")

        for section in SectionParagraph.objects.all():
            section.content = re.sub(regex_pattern, transform_string, section.content)
            section.save(update_fields=["content"])

    dependencies = [
        (
            "reports",
            "0027_remove_sectionrecipient_uses_dynamic_recipient_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(update_sectionparagraph),
    ]
