# Generated by Django 4.2.1 on 2023-06-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0028_datamigration_update_sectionparapgraph"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectionvalidation",
            name="service_style",
            field=models.CharField(
                choices=[
                    ("bold", "Gras"),
                    ("italic", "Italique"),
                    ("underline", "Souligné"),
                    ("h1", "Titre 1"),
                    ("h2", "Titre 2"),
                    ("h3", "Titre 3"),
                    ("h4", "Titre 4"),
                    ("h5", "Titre 5"),
                    ("h6", "Titre 6"),
                ],
                default="h3",
                help_text="S'applique au nom du service",
                max_length=255,
                verbose_name="Style du service",
            ),
        ),
        migrations.AddField(
            model_name="sectionvalidation",
            name="show_empty_comment",
            field=models.BooleanField(
                default=False,
                help_text="Afficher/masquer les validations sans commentaires",
                verbose_name="Afficher les commentaires vides",
            ),
        ),
        migrations.AddField(
            model_name="sectionvalidation",
            name="show_status",
            field=models.BooleanField(default=False, verbose_name="Afficher le statut"),
        ),
        migrations.AddField(
            model_name="sectionvalidation",
            name="style",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "champ : valeur"), (1, "valeur")],
                default=0,
                help_text="Choisir le style d'affichage",
                verbose_name="Style",
            ),
        ),
    ]
