# Generated by Django 4.1.4 on 2023-02-20 16:03

import django.core.validators
from django.db import migrations, models

import geocity.apps.reports.fields
import geocity.fields


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0028_sectiondetail_undesired_properties"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectionparagraph",
            name="is_justified",
            field=models.BooleanField(
                default=True,
                help_text="Justifier le texte ?",
                verbose_name="Texte justifié",
            ),
        ),
        migrations.AddField(
            model_name="sectionparagraphright",
            name="is_justified",
            field=models.BooleanField(
                default=True,
                help_text="Justifier le texte ?",
                verbose_name="Texte justifié",
            ),
        ),
        migrations.AlterField(
            model_name="reportlayout",
            name="background",
            field=geocity.apps.reports.fields.BackgroundFileField(
                blank=True,
                help_text="Image d'arrière plan (PNG).",
                null=True,
                storage=geocity.fields.PrivateFileSystemStorage(),
                upload_to="backgound_paper",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png"]
                    )
                ],
                verbose_name="Papier à entête",
            ),
        ),
        migrations.AlterField(
            model_name="stylelogo",
            name="logo",
            field=geocity.apps.reports.fields.BackgroundFileField(
                help_text="Image pour logo (PNG).",
                storage=geocity.fields.PrivateFileSystemStorage(),
                upload_to="backgound_paper",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png"]
                    )
                ],
                verbose_name="Logo",
            ),
        ),
    ]
