# Generated by Django 4.2.1 on 2023-07-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0029_sectionvalidation_service_style_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectionrecipient",
            name="first_recipient",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (7, "Architecte/Ingénieur"),
                    (6, "Association"),
                    (0, "Autres"),
                    (8, "Direction des travaux"),
                    (3, "Entreprise"),
                    (4, "Maître d'ouvrage"),
                    (2, "Propriétaire"),
                    (1, "Requérant (si différent de l'auteur de la demande)"),
                    (5, "Sécurité"),
                    (9, "Bénéficiaire"),
                    (999, "Auteur"),
                ],
                default=1,
                help_text='Utilisé par défaut. Si celui-ci n\'existe pas, prend le "destinataire secondaire"',
                verbose_name="Destinataire principal",
            ),
        ),
        migrations.AlterField(
            model_name="sectionrecipient",
            name="second_recipient",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (7, "Architecte/Ingénieur"),
                    (6, "Association"),
                    (0, "Autres"),
                    (8, "Direction des travaux"),
                    (3, "Entreprise"),
                    (4, "Maître d'ouvrage"),
                    (2, "Propriétaire"),
                    (1, "Requérant (si différent de l'auteur de la demande)"),
                    (5, "Sécurité"),
                    (9, "Bénéficiaire"),
                    (999, "Auteur"),
                ],
                default=999,
                help_text='Utilisé lorsque le "destinataire principal" n\'est pas présent dans la liste des contacts saisis',
                verbose_name="Destinataire secondaire",
            ),
        ),
    ]
