# Generated by Django 4.2.4 on 2023-10-02 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0031_alter_sectionrecipient_first_recipient_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SectionImage",
            fields=[
                (
                    "section_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="reports.section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image(s)",
            },
            bases=("reports.section",),
        ),
    ]
