# Generated by Django 3.2.13 on 2022-05-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamblocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printblockparagraph',
            name='content',
            field=models.TextField(help_text='You can access the contents of the data returned by the API with placeholders like `{{data.properties.geotime_aggregated.start_date}}`. Have a look at <a href="http://localhost:9095/wfs3/collections/permits/items/1">the API</a> to see available data.'),
        ),
    ]
