# Generated by Django 3.2.13 on 2022-05-31 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamblocks', '0003_auto_20220531_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printblockmap',
            name='url',
        ),
    ]
