# Generated by Django 3.2.13 on 2022-05-31 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamblocks', '0004_remove_printblockmap_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printblockparagraph',
            name='title',
        ),
        migrations.RenameModel(
            old_name='printblockparagraph',
            new_name='printblockcustom',
        ),
    ]
