# Generated by Django 3.2.13 on 2022-06-01 06:58

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('streamblocks', '0005_clean_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintBlockRichText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(help_text='You can access the contents of the data returned by the API with placeholders like `{{data.properties.geotime_aggregated.start_date}}`. Have a look at <a href="http://localhost:9095/wfs3/collections/permits/items/1">the API</a> to see available data.')),
            ],
        ),
    ]
