# Generated by Django 3.2.15 on 2022-10-26 12:02

from django.db import migrations, models
import geocity.apps.submissions.fields


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsubmissiongeotime",
            name="ends_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de fin"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubmissiongeotime",
            name="starts_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de début"
            ),
        ),
        migrations.AlterField(
            model_name="submissiongeotime",
            name="ends_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de fin"
            ),
        ),
        migrations.AlterField(
            model_name="submissiongeotime",
            name="starts_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de début"
            ),
        ),
    ]
