# Generated by Django 3.2.15 on 2022-11-16 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0003_migrate_permits_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="complementarydocumenttype",
            options={
                "verbose_name": "2.2 Type de document",
                "verbose_name_plural": "2.2 Types de document",
            },
        ),
        migrations.AlterModelOptions(
            name="submissionamendfield",
            options={
                "verbose_name": "2.1 Champ de traitement des demandes",
                "verbose_name_plural": "2.1 Champs de traitement des demandes",
            },
        ),
        migrations.AlterModelOptions(
            name="contacttype",
            options={
                "verbose_name": "1.5 Contact",
                "verbose_name_plural": "1.5 Contacts",
            },
        ),
        migrations.AlterModelOptions(
            name="submissioninquiry",
            options={
                "verbose_name": "2.4 Enquête publique",
                "verbose_name_plural": "2.4 Enquêtes publiques",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalsubmission",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical 2.3 Consultation de la demande",
            },
        ),
        migrations.AlterModelOptions(
            name="submission",
            options={
                "permissions": [
                    ("amend_submission", "Traiter les demandes de permis"),
                    ("validate_submission", "Valider les demandes de permis"),
                    ("classify_submission", "Classer les demandes de permis"),
                    ("edit_submission", "Éditer les demandes de permis"),
                    ("view_private_submission", "Voir les demandes restreintes"),
                ],
                "verbose_name": "2.3 Consultation de la demande",
                "verbose_name_plural": "2.3 Consultation des demandes",
            },
        ),
    ]
