# Generated by Django 3.2.15 on 2022-11-16 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_migrate_permits_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complementarydocumenttype',
            options={'verbose_name': '2.2 Type de document', 'verbose_name_plural': '2.2 Types de document'},
        ),
        migrations.AlterModelOptions(
            name='submissionamendfield',
            options={'verbose_name': '2.1 Champ de traitement des demandes', 'verbose_name_plural': '2.1 Champs de traitement des demandes'},
        ),
        migrations.DeleteModel(
            name='ContactType',
        ),
    ]
