# Generated by Django 3.2.15 on 2022-11-16 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0004_admin_reorder_for_phoenix"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="submission",
            options={
                "permissions": [
                    ("amend_submission", "Traiter les demandes de permis"),
                    ("validate_submission", "Valider les demandes de permis"),
                    ("classify_submission", "Classer les demandes de permis"),
                    ("edit_submission", "Éditer les demandes de permis"),
                    ("view_private_submission", "Voir les demandes restreintes"),
                ],
                "verbose_name": "3.1 Consultation de la demande",
                "verbose_name_plural": "3.1 Consultation des demandes",
            },
        ),
    ]
