# Generated by Django 3.2.15 on 2022-11-07 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_makeproxymodels'),
        ('submissions', '0004_makeproxymodels'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxySection',
            fields=[
            ],
            options={
                'verbose_name': '2.6 Section du rapport',
                'verbose_name_plural': '2.6 Sections du rapport',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reports.section',),
        ),
    ]
