# Generated by Django 4.1 on 2022-12-05 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_alter_complementarydocumenttype_reports_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeomLayer',
        ),
    ]
