# Generated by Django 3.2.15 on 2022-11-17 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0005_alter_submission_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalsubmission",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical 2.3 Consultation de la demande",
            },
        ),
        migrations.AlterModelOptions(
            name="submission",
            options={
                "permissions": [
                    ("amend_submission", "Traiter les demandes de permis"),
                    ("validate_submission", "Valider les demandes de permis"),
                    ("classify_submission", "Classer les demandes de permis"),
                    ("edit_submission", "Éditer les demandes de permis"),
                    ("view_private_submission", "Voir les demandes restreintes"),
                ],
                "verbose_name": "2.3 Consultation de la demande",
                "verbose_name_plural": "2.3 Consultation des demandes",
            },
        ),
        migrations.AlterModelOptions(
            name="submissionamendfield",
            options={
                "verbose_name": "2.1 Configuration du champ de traitement des demandes",
                "verbose_name_plural": "2.1 Configuration des champs de traitement des demandes",
            },
        ),
        migrations.AlterModelOptions(
            name="submissioninquiry",
            options={
                "verbose_name": "2.4 Enquête publique",
                "verbose_name_plural": "2.4 Enquêtes publiques",
            },
        ),
    ]
