# Generated by Django 4.1 on 2022-12-06 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0005_alter_complementarydocumenttype_reports_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="complementarydocumenttype",
            options={
                "verbose_name": "3.2 Catégorie de document",
                "verbose_name_plural": "3.2 Catégories de document",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalsubmission",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical 2.2 Consultation de la demande",
            },
        ),
        migrations.AlterModelOptions(
            name="submission",
            options={
                "permissions": [
                    ("amend_submission", "Traiter les demandes de permis"),
                    ("validate_submission", "Valider les demandes de permis"),
                    ("classify_submission", "Classer les demandes de permis"),
                    ("edit_submission", "Éditer les demandes de permis"),
                    ("view_private_submission", "Voir les demandes restreintes"),
                ],
                "verbose_name": "2.2 Consultation de la demande",
                "verbose_name_plural": "2.2 Consultation des demandes",
            },
        ),
        migrations.AlterModelOptions(
            name="submissioninquiry",
            options={
                "verbose_name": "2.3 Enquête publique",
                "verbose_name_plural": "2.3 Enquêtes publiques",
            },
        ),
    ]
