# Generated by Django 4.1 on 2022-12-01 23:49

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forms", "0006_paymentsettings_price_form_requires_online_payment_and_more"),
        ("submissions", "0005_alter_complementarydocumenttype_reports_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionPrice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255, verbose_name="Texte")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Montant"
                    ),
                ),
                ("currency", models.CharField(max_length=20, verbose_name="Devise")),
                (
                    "original_price",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="forms.price",
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price",
                        to="submissions.submission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostFinanceTransaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Montant"
                    ),
                ),
                ("currency", models.CharField(max_length=20, verbose_name="Devise")),
                (
                    "merchant_reference",
                    models.CharField(
                        max_length=255, verbose_name="Référence marchande"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Pas payé"),
                            ("paid", "Payé"),
                            ("to_refund", "À rembourser"),
                            ("refunded", "Remboursé"),
                        ],
                        default="unpaid",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "submission_price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="submissions.submissionprice",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricalSubmissionPrice",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("text", models.CharField(max_length=255, verbose_name="Texte")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Montant"
                    ),
                ),
                ("currency", models.CharField(max_length=20, verbose_name="Devise")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "original_price",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="forms.price",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical submission price",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPostFinanceTransaction",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Montant"
                    ),
                ),
                ("currency", models.CharField(max_length=20, verbose_name="Devise")),
                (
                    "merchant_reference",
                    models.CharField(
                        max_length=255, verbose_name="Référence marchande"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Pas payé"),
                            ("paid", "Payé"),
                            ("to_refund", "À rembourser"),
                            ("refunded", "Remboursé"),
                        ],
                        default="unpaid",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Date de modification"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission_price",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="submissions.submissionprice",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical post finance transaction",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
