# Generated by Django 3.2.15 on 2022-11-09 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0006_admin_models_names"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProxyReport",
        ),
        migrations.DeleteModel(
            name="ProxyReportLayout",
        ),
        migrations.DeleteModel(
            name="ProxySection",
        ),
    ]
