# Generated by Django 4.1 on 2022-12-05 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0006_change_admin_order"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GeomLayer",
        ),
    ]
