# Generated by Django 4.1 on 2022-12-07 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0007_alter_submission_options"),
        ("submissions", "0007_remove_geom_layer"),
    ]

    operations = []
