# Generated by Django 4.1.4 on 2022-12-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0008_django_simple_history_update"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalcontact",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Contact",
                "verbose_name_plural": "historical Contacts",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalfieldvalue",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical field value",
                "verbose_name_plural": "historical field values",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalsubmission",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical 2.2 Consultation de la demande",
                "verbose_name_plural": "historical 2.2 Consultation des demandes",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalsubmissionamendfieldvalue",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical submission amend field value",
                "verbose_name_plural": "historical submission amend field values",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalsubmissiongeotime",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical 3.3 Consultation de l'agenda et de la géométrie",
                "verbose_name_plural": "historical 3.3 Consultation des agenda et géométries",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalsubmissionvalidation",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical 3.5 Consultation de la validation par le service",
                "verbose_name_plural": "historical 3.5 Consultation des validations par les services",
            },
        ),
        migrations.AlterField(
            model_name="historicalcontact",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalfieldvalue",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalsubmission",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalsubmissionamendfieldvalue",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalsubmissiongeotime",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalsubmissionvalidation",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
