# Generated by Django 4.1 on 2022-12-12 10:44

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0011_paymentsettings_integrator_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("submissions", "0009_alter_historicalcontact_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalcontact",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Contact",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalfieldvalue",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical field value",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalsubmission",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical 2.2 Consultation de la demande",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalsubmissionamendfieldvalue",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical submission amend field value",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalsubmissiongeotime",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical 3.3 Consultation de l'agenda et de la géométrie",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalsubmissionvalidation",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical 3.5 Consultation de la validation par le service",
            },
        ),
        migrations.AlterModelOptions(
            name="submission",
            options={
                "permissions": [
                    ("amend_submission", "Traiter les demandes de permis"),
                    ("validate_submission", "Valider les demandes de permis"),
                    ("classify_submission", "Classer les demandes de permis"),
                    ("edit_submission", "Éditer les demandes de permis"),
                    ("view_private_submission", "Voir les demandes restreintes"),
                    ("can_refund_transactions", "Rembourser une transaction"),
                    ("can_revert_refund_transactions", "Revenir sur un remboursement"),
                ],
                "verbose_name": "2.2 Consultation de la demande",
                "verbose_name_plural": "2.2 Consultation des demandes",
            },
        ),
        migrations.AlterField(
            model_name="historicalcontact",
            name="history_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="historicalfieldvalue",
            name="history_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="historicalsubmission",
            name="history_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="historicalsubmissionamendfieldvalue",
            name="history_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="historicalsubmissiongeotime",
            name="history_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="historicalsubmissionvalidation",
            name="history_date",
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name="SubmissionPrice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255, verbose_name="Texte")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Montant"
                    ),
                ),
                ("currency", models.CharField(max_length=20, verbose_name="Devise")),
                (
                    "original_price",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="forms.price",
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price",
                        to="submissions.submission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostFinanceTransaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Montant"
                    ),
                ),
                ("currency", models.CharField(max_length=20, verbose_name="Devise")),
                (
                    "merchant_reference",
                    models.CharField(
                        max_length=255, verbose_name="Référence marchande"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Pas payée"),
                            ("paid", "Payée"),
                            ("to_refund", "À rembourser"),
                            ("refunded", "Remboursée"),
                            ("failed", "Échouée"),
                        ],
                        default="unpaid",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "authorization_timeout_on",
                    models.DateTimeField(
                        null=True, verbose_name="Date de fin d'authorisation"
                    ),
                ),
                (
                    "payment_url",
                    models.CharField(
                        max_length=255, null=True, verbose_name="URL de paiement"
                    ),
                ),
                (
                    "submission_price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="submissions.submissionprice",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricalSubmissionPrice",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("text", models.CharField(max_length=255, verbose_name="Texte")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Montant"
                    ),
                ),
                ("currency", models.CharField(max_length=20, verbose_name="Devise")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "original_price",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="forms.price",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical submission price",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPostFinanceTransaction",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Montant"
                    ),
                ),
                ("currency", models.CharField(max_length=20, verbose_name="Devise")),
                (
                    "merchant_reference",
                    models.CharField(
                        max_length=255, verbose_name="Référence marchande"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Pas payée"),
                            ("paid", "Payée"),
                            ("to_refund", "À rembourser"),
                            ("refunded", "Remboursée"),
                            ("failed", "Échouée"),
                        ],
                        default="unpaid",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Date de modification"
                    ),
                ),
                (
                    "authorization_timeout_on",
                    models.DateTimeField(
                        null=True, verbose_name="Date de fin d'authorisation"
                    ),
                ),
                (
                    "payment_url",
                    models.CharField(
                        max_length=255, null=True, verbose_name="URL de paiement"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission_price",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="submissions.submissionprice",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical post finance transaction",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
