# Generated by Django 4.1 on 2022-12-08 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0009_alter_submission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postfinancetransaction",
            name="submission_price",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="submissions.submissionprice",
            ),
        ),
    ]
