# Generated by Django 4.1 on 2022-12-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0010_set_related_name_postfinancetransactions"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpostfinancetransaction",
            name="authorization_timeout_on",
            field=models.DateTimeField(
                null=True, verbose_name="Date de fin d'authorisation"
            ),
        ),
        migrations.AddField(
            model_name="historicalpostfinancetransaction",
            name="payment_url",
            field=models.CharField(
                max_length=255, null=True, verbose_name="URL de paiement"
            ),
        ),
        migrations.AddField(
            model_name="postfinancetransaction",
            name="authorization_timeout_on",
            field=models.DateTimeField(
                null=True, verbose_name="Date de fin d'authorisation"
            ),
        ),
        migrations.AddField(
            model_name="postfinancetransaction",
            name="payment_url",
            field=models.CharField(
                max_length=255, null=True, verbose_name="URL de paiement"
            ),
        ),
    ]
