# Generated by Django 4.1 on 2022-12-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "submissions",
            "0011_historicalpostfinancetransaction_authorization_timeout_on_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpostfinancetransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Pas payé"),
                    ("paid", "Payé"),
                    ("to_refund", "À rembourser"),
                    ("refunded", "Remboursé"),
                    ("failed", "Échoué"),
                ],
                default="unpaid",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="postfinancetransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Pas payé"),
                    ("paid", "Payé"),
                    ("to_refund", "À rembourser"),
                    ("refunded", "Remboursé"),
                    ("failed", "Échoué"),
                ],
                default="unpaid",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
