# Generated by Django 4.1.4 on 2022-12-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0011_alter_historicalcontact_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postfinancetransaction",
            options={"ordering": ("-creation_date",)},
        ),
    ]
