# Generated by Django 4.1.7 on 2023-03-22 10:49

from django.db import migrations, models


def migrate_comments(apps, schema_editor):
    """
    Put comment_before, comment_during and comment_after in 1 comment
    """
    SubmissionValidation = apps.get_model("submission", "SubmissionValidation")

    SubmissionValidation.objects.all()

    # For each SubmissionValidation, squash comment_before comment_during comment_after in 1 comment
    for validation in SubmissionValidation:
        comment = f"""{validation.comment_before}
        {validation.comment_during}
        {validation.comment_after}"""

        # save it in SubmissionValidation.comment
        validation.comment = comment
        validation.save()


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0015_alter_submission_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsubmissionvalidation",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Information supplémentaire facultative transmise au requérant",
                verbose_name="Commentaire",
            ),
        ),
        migrations.AddField(
            model_name="submissionvalidation",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Information supplémentaire facultative transmise au requérant",
                verbose_name="Commentaire",
            ),
        ),
        migrations.RunPython(migrate_comments),
    ]
