# Generated by Django 4.1.7 on 2023-03-23 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0015_alter_submission_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'permissions': [('read_submission', 'Consulter les demandes'), ('amend_submission', 'Traiter les demandes'), ('edit_submission_validations', 'Modifier les validations'), ('validate_submission', 'Valider les demandes'), ('classify_submission', 'Classer les demandes'), ('edit_submission', 'Éditer les demandes'), ('view_private_form', 'Voir les demandes restreintes'), ('can_refund_transactions', 'Rembourser une transaction'), ('can_revert_refund_transactions', 'Revenir sur un remboursement')], 'verbose_name': '2.2 Consultation de la demande', 'verbose_name_plural': '2.2 Consultation des demandes'},
        ),
    ]
