# Generated by Django 4.1.7 on 2023-03-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0015_alter_submission_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsubmissionvalidation",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Information supplémentaire facultative transmise au requérant",
                verbose_name="Commentaire",
            ),
        ),
        migrations.AddField(
            model_name="submissionvalidation",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Information supplémentaire facultative transmise au requérant",
                verbose_name="Commentaire",
            ),
        ),
    ]
