# Generated by Django 4.1.7 on 2023-03-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0016_historicalsubmissionvalidation_comment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalsubmissionvalidation",
            name="comment_after",
        ),
        migrations.RemoveField(
            model_name="historicalsubmissionvalidation",
            name="comment_before",
        ),
        migrations.RemoveField(
            model_name="historicalsubmissionvalidation",
            name="comment_during",
        ),
        migrations.RemoveField(
            model_name="submissionvalidation",
            name="comment_after",
        ),
        migrations.RemoveField(
            model_name="submissionvalidation",
            name="comment_before",
        ),
        migrations.RemoveField(
            model_name="submissionvalidation",
            name="comment_during",
        ),
        migrations.AddField(
            model_name="historicalsubmissionvalidation",
            name="is_visible_by_author",
            field=models.BooleanField(
                default=True, verbose_name="Visible par l'auteur de la demande"
            ),
        ),
        migrations.AddField(
            model_name="submissionvalidation",
            name="is_visible_by_author",
            field=models.BooleanField(
                default=True, verbose_name="Visible par l'auteur de la demande"
            ),
        ),
    ]
