# Generated by Django 4.1.7 on 2023-03-22 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0016_historicalsubmissionvalidation_comment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalsubmissionvalidation",
            name="comment_after",
        ),
        migrations.RemoveField(
            model_name="historicalsubmissionvalidation",
            name="comment_before",
        ),
        migrations.RemoveField(
            model_name="historicalsubmissionvalidation",
            name="comment_during",
        ),
        migrations.RemoveField(
            model_name="submissionvalidation",
            name="comment_after",
        ),
        migrations.RemoveField(
            model_name="submissionvalidation",
            name="comment_before",
        ),
        migrations.RemoveField(
            model_name="submissionvalidation",
            name="comment_during",
        ),
    ]
