# Generated by Django 4.1.7 on 2023-03-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0017_alter_submission_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalsubmissionvalidation",
            name="is_visible_by_author",
        ),
        migrations.RemoveField(
            model_name="submissionvalidation",
            name="is_visible_by_author",
        ),
        migrations.AddField(
            model_name="historicalsubmissionvalidation",
            name="comment_is_visible_by_author",
            field=models.BooleanField(
                default=True,
                verbose_name="Commentaire visible par l'auteur de la demande",
            ),
        ),
        migrations.AddField(
            model_name="submissionvalidation",
            name="comment_is_visible_by_author",
            field=models.BooleanField(
                default=True,
                verbose_name="Commentaire visible par l'auteur de la demande",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubmissionvalidation",
            name="comment",
            field=models.TextField(blank=True, verbose_name="Commentaire"),
        ),
        migrations.AlterField(
            model_name="submissionvalidation",
            name="comment",
            field=models.TextField(blank=True, verbose_name="Commentaire"),
        ),
    ]
