# Generated by Django 4.2.1 on 2023-06-05 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0017_alter_submission_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissioninquiry',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry', to='submissions.submission', verbose_name='Demande'),
        ),
    ]
