# Generated by Django 4.2.1 on 2023-06-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0018_add_missing_related_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsubmission",
            name="sent_date",
            field=models.DateTimeField(null=True, verbose_name="date du dernier envoi"),
        ),
        migrations.AddField(
            model_name="submission",
            name="sent_date",
            field=models.DateTimeField(null=True, verbose_name="date du dernier envoi"),
        ),
    ]
