# Generated by Django 4.2.1 on 2023-06-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0019_datamigration_sent_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionamendfield",
            name="api_name",
            field=models.CharField(
                blank=True,
                help_text="Se génère automatiquement lorsque celui-ci est vide.",
                max_length=255,
                verbose_name="Nom dans l'API",
            ),
        ),
    ]
