# Generated by Django 4.2.1 on 2023-06-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0019_datamigration_sent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionamendfield',
            name='help_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='information complémentaire'),
        ),
        migrations.AddField(
            model_name='submissionamendfield',
            name='placeholder',
            field=models.CharField(blank=True, max_length=255, verbose_name='exemple de donnée à saisir'),
        ),
        migrations.AddField(
            model_name='submissionamendfield',
            name='regex_pattern',
            field=models.CharField(blank=True, help_text='Exemple: ^[0-9]{4}$', max_length=255, verbose_name='regex pattern'),
        ),
    ]
