# Generated by Django 4.2.1 on 2023-06-15 16:21
from django.db import migrations

from geocity.apps.api.services import convert_string_to_api_key


class Migration(migrations.Migration):
    def api_name_from_name(apps, schema_editor):

        SubmissionAmendField = apps.get_model("submissions", "SubmissionAmendField")

        for submissionamendfield in SubmissionAmendField.objects.all():
            submissionamendfield.api_name = convert_string_to_api_key(
                submissionamendfield.name
            )
            submissionamendfield.save(update_fields=["api_name"])

    dependencies = [
        (
            "submissions",
            "0020_submissionamendfield_api_name",
        ),
    ]

    operations = [
        migrations.RunPython(api_name_from_name),
    ]
