# Generated by Django 4.2.1 on 2023-07-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0020_helptext_placeholder_and_regex_for_amend_fields_and_api_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacttype',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(7, 'Architecte/Ingénieur'), (6, 'Association'), (0, 'Autres'), (8, 'Direction des travaux'), (3, 'Entreprise'), (4, "Maître d'ouvrage"), (2, 'Propriétaire'), (1, "Requérant (si différent de l'auteur de la demande)"), (5, 'Sécurité'), (9, 'Bénéficiaire')], default=0, verbose_name='type de contact'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='creditor_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(7, 'Architecte/Ingénieur'), (6, 'Association'), (0, 'Autres'), (8, 'Direction des travaux'), (3, 'Entreprise'), (4, "Maître d'ouvrage"), (2, 'Propriétaire'), (1, "Requérant (si différent de l'auteur de la demande)"), (5, 'Sécurité'), (9, 'Bénéficiaire')], null=True, verbose_name='Destinataire de la facture'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='creditor_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(7, 'Architecte/Ingénieur'), (6, 'Association'), (0, 'Autres'), (8, 'Direction des travaux'), (3, 'Entreprise'), (4, "Maître d'ouvrage"), (2, 'Propriétaire'), (1, "Requérant (si différent de l'auteur de la demande)"), (5, 'Sécurité'), (9, 'Bénéficiaire')], null=True, verbose_name='Destinataire de la facture'),
        ),
        migrations.AlterField(
            model_name='submissioncontact',
            name='contact_type',
            field=models.PositiveSmallIntegerField(choices=[(7, 'Architecte/Ingénieur'), (6, 'Association'), (0, 'Autres'), (8, 'Direction des travaux'), (3, 'Entreprise'), (4, "Maître d'ouvrage"), (2, 'Propriétaire'), (1, "Requérant (si différent de l'auteur de la demande)"), (5, 'Sécurité'), (9, 'Bénéficiaire')], default=0, verbose_name='type de contact'),
        ),
    ]
