# Generated by Django 4.2.1 on 2023-08-15 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0022_contactform_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalpostfinancetransaction",
            old_name="merchant_reference",
            new_name="transaction_id",
        ),
        migrations.RenameField(
            model_name="postfinancetransaction",
            old_name="merchant_reference",
            new_name="transaction_id",
        ),
    ]
