# Generated by Django 4.2.4 on 2023-11-02 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0022_contactform_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionamendfield",
            name="api_light",
            field=models.BooleanField(
                default=False,
                help_text="Lorsque cette case est cochée, ce champ est affichée dans la version light de l'api (/rest/RESSOURCE).<br>\n            Afin de ne pas afficher trop d'informations, le champ est masqué pour améliorer la rapidité de l'API.<br>\n            Pour afficher la version normale de l'api, il faut se rendre sur une seule ressource (/rest/RESSOURCE/:ID).",
                verbose_name="Visible dans l'API light",
            ),
        ),
        migrations.AlterField(
            model_name="submissionamendfieldvalue",
            name="field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="amend_field_value",
                to="submissions.submissionamendfield",
                verbose_name="caractéristique",
            ),
        ),
    ]
