# Generated by Django 4.2.7 on 2023-12-07 13:02

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submissions', '0022_contactform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestationsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Prestation')),
                ('is_visible_by_validator', models.BooleanField(help_text='Est visible par le validateur', verbose_name='visible by validator')),
                ('integrator', models.ForeignKey(limit_choices_to={'permit_department__is_integrator_admin': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Groupe des administrateurs')),
            ],
        ),
        migrations.CreateModel(
            name='Prestations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('created_by', models.CharField(max_length=255, verbose_name='Créé par')),
                ('updated_by', models.CharField(max_length=255, verbose_name='Mis à jour par')),
                ('time_spent_on_task', models.DurationField(default=0, help_text="Temps passé pour effectuer la prestation (arrondi au quart d'heure)", verbose_name='Temps passé pour réaliser la prestation [h]')),
                ('pricing_currency', djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF .-'), ('EUR', 'EUR €'), ('USD', 'USD $')], default='CHF', editable=False, max_length=3)),
                ('pricing', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('140'), default_currency='CHF', max_digits=12)),
                ('monetary_amount_currency', djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF .-'), ('EUR', 'EUR €'), ('USD', 'USD $')], default='CHF', editable=False, max_length=3)),
                ('monetary_amount', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='CHF', max_digits=12)),
                ('name', models.ForeignKey(help_text='Choix de la prestation effectuée dans une liste prédéfinie', on_delete=django.db.models.deletion.CASCADE, to='submissions.prestationslist')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestations', to=settings.AUTH_USER_MODEL, verbose_name='Saisi par')),
            ],
        ),
    ]
