# Generated by Django 4.2.4 on 2023-09-12 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0025_geom_and_timerange_field'),
        ('submissions', '0022_contactform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubmissiongeotime',
            name='form',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='forms.form'),
        ),
        migrations.AddField(
            model_name='submissiongeotime',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geo_time', to='forms.form'),
        ),
    ]
