# Generated by Django 4.2.4 on 2023-10-05 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0023_submissionamendfield_api_light"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissionamendfieldvalue",
            name="field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="amend_field_value",
                to="submissions.submissionamendfield",
                verbose_name="caractéristique",
            ),
        ),
    ]
