# Generated by Django 4.2.4 on 2023-11-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0023_submissionamendfield_api_light_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissionamendfield",
            name="api_light",
            field=models.BooleanField(
                default=False,
                help_text="Lorsque cette case est cochée, ce champ est affichée dans la version light de l'api (/rest/RESSOURCE) si la demande est rendue publique par le pilote.<br>\n            Afin de ne pas afficher trop d'informations, le champ est masqué pour améliorer la rapidité de l'API.<br>\n            Pour afficher la version normale de l'api, il faut se rendre sur une seule ressource (/rest/RESSOURCE/:ID).",
                verbose_name="Visible dans l'API light",
            ),
        ),
    ]
