# Generated by Django 4.2.1 on 2023-08-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0023_alter_contacttype_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactform",
            name="is_used_dynamically",
        ),
        migrations.AddField(
            model_name="contactform",
            name="is_dynamic",
            field=models.BooleanField(
                default=False,
                help_text="Permet à l'utilisateur d'ajouter ce type de contact lors de la saisie, autant de fois que souhaité.",
                verbose_name="Dynamique",
            ),
        ),
    ]
