# Generated by Django 4.2.1 on 2023-08-17 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0024_remove_contactform_is_used_dynamically_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="creditor_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="submissions.contacttype",
                verbose_name="Destinataire de la facture",
            ),
        ),
    ]
