# Generated by Django 4.2.9 on 2024-02-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0024_geom_field_input_type_for_form"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpostfinancetransaction",
            name="authorization_timeout_on",
            field=models.DateTimeField(
                null=True, verbose_name="Date de fin d'autorisation"
            ),
        ),
        migrations.AlterField(
            model_name="postfinancetransaction",
            name="authorization_timeout_on",
            field=models.DateTimeField(
                null=True, verbose_name="Date de fin d'autorisation"
            ),
        ),
    ]
