# Generated by Django 4.2.4 on 2023-11-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0024_alter_submissionamendfield_api_light"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsubmission",
            name="featured_agenda",
            field=models.BooleanField(default=False, verbose_name="Mise en vedette"),
        ),
        migrations.AddField(
            model_name="historicalsubmission",
            name="is_public_agenda",
            field=models.BooleanField(default=False, verbose_name="Publication agenda"),
        ),
        migrations.AddField(
            model_name="submission",
            name="featured_agenda",
            field=models.BooleanField(default=False, verbose_name="Mise en vedette"),
        ),
        migrations.AddField(
            model_name="submission",
            name="is_public_agenda",
            field=models.BooleanField(default=False, verbose_name="Publication agenda"),
        ),
    ]
