# Generated by Django 4.2.9 on 2024-02-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "submissions",
            "0025_alter_historicalpostfinancetransaction_authorization_timeout_on_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpostfinancetransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("submission", "Soumission"),
                    ("prolongation", "Prolongation"),
                ],
                default="submission",
                max_length=20,
                verbose_name="Type de transaction",
            ),
        ),
        migrations.AddField(
            model_name="postfinancetransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("submission", "Soumission"),
                    ("prolongation", "Prolongation"),
                ],
                default="submission",
                max_length=20,
                verbose_name="Type de transaction",
            ),
        ),
    ]
