# Generated by Django 4.2.10 on 2024-03-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0026_service_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsubmission",
            name="status_agenda",
            field=models.CharField(
                choices=[
                    ("null", "Aucun"),
                    ("CANCELLED", "Annulé"),
                    ("SOLDOUT", "Complet"),
                ],
                default="null",
                max_length=255,
                verbose_name="Statut de l'évènement",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="status_agenda",
            field=models.CharField(
                choices=[
                    ("null", "Aucun"),
                    ("CANCELLED", "Annulé"),
                    ("SOLDOUT", "Complet"),
                ],
                default="null",
                max_length=255,
                verbose_name="Statut de l'évènement",
            ),
        ),
    ]
