# Generated by Django 3.2.13 on 2022-06-15 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sectionmap",
            old_name="layout_name",
            new_name="qgis_print_template_name",
        ),
    ]
