# Generated by Django 3.2.13 on 2022-06-10 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectionparagraph",
            name="title",
            field=models.CharField(blank=True, default="", max_length=2000),
        ),
    ]
