# Generated by Django 3.2.13 on 2022-06-09 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blockparagraph',
            name='content',
            field=models.TextField(help_text='Il est possible d\'accéder aux données de l\'API avec la syntaxe suivante: `{{data.properties.geotime_aggregated.start_date}}`. Consultez les résults de <a href="http://localhost:9095/wfs3/collections/permits/items/1">l\'API</a> pour voir les données disponibles.'),
        ),
    ]
