# Generated by Django 3.2.13 on 2022-06-01 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0072_worksobjecttype_reports'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='permits.complementarydocumenttype'),
            preserve_default=False,
        ),
    ]
