# Generated by Django 3.2.13 on 2022-06-23 16:07

from django.db import migrations, transaction

from ..signals import create_default_report_for_integrator


def create_default_report_for_existing_integrators(apps, schema_editor):
    """This creates a default report for existing integrators, since a signal is in place to automatically
    create reports for new integrators."""

    try:
        # This could fail if the code has diverged from old migrations because we cannot use
        # historical models. Since this data migration is not critical, we swallow exceptions,
        # to avoid breaking migrations down the line.
        from django.contrib.auth.models import Group

        with transaction.atomic():
            for integrator in Group.objects.all():
                create_default_report_for_integrator(Group, integrator, True)
    except Exception as e:
        print(
            f"Warning: automatic creation of default report for existing integrators failed with exception:\n{e}"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_default_report_for_existing_integrators)]
