# Generated by Django 3.2.13 on 2022-06-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permits", "0073_worksobjecttype_reports"),
        ("reports", "0002_sectionparagraph_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="work_object_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="_reports_report_work_object_types_+",
                to="permits.WorksObjectType",
            ),
        ),
    ]
