# Generated by Django 3.2.13 on 2022-06-08 06:46

from django.db import migrations
import streamfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='stream',
            field=streamfield.fields.StreamField(blank=True, default='[]', help_text="ATTENTION: l'implementation actuelle exige que seuls des utilisateurs approuvés puissent utiliser cette fonction, puisqu'elle permet l'accès à certaines données internes."),
        ),
    ]
