# Generated by Django 3.2.13 on 2022-06-15 10:26

from django.db import migrations, models

import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_alter_report_work_object_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="report",
            field=models.ForeignKey(
                on_delete=reports.models.Section.NON_POLYMORPHIC_CASCADE,
                related_name="sections",
                to="reports.report",
            ),
        ),
    ]
