# Generated by Django 3.2.13 on 2022-06-08 08:14

from django.db import migrations
import streamfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='stream',
            field=streamfield.fields.StreamField(blank=True, default='[]'),
        ),
    ]
