# Generated by Django 3.2.13 on 2022-06-08 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0072_worksobjecttype_reports'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('reports', '0004_alter_report_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='integrator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Groupe des administrateurs'),
        ),
        migrations.AddField(
            model_name='report',
            name='work_object_types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='available_reports', to='permits.worksobjecttype', verbose_name='Objets'),
        ),
        migrations.AddField(
            model_name='reportlayout',
            name='integrator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Groupe des administrateurs'),
        ),
    ]
