# Generated by Django 3.2.13 on 2022-06-24 00:36

import django.core.validators
from django.db import migrations, models

import permits.fields


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0005_alter_sectionparagraph_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectionmap",
            name="qgis_print_template_name",
            field=models.CharField(blank=True, default="a4", max_length=30),
        ),
        migrations.AlterField(
            model_name="sectionmap",
            name="qgis_project_file",
            field=permits.fields.AdministrativeEntityFileField(
                blank=True,
                storage=permits.fields.PrivateFileSystemStorage(),
                upload_to="qgis_templates",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["qgs"]
                    )
                ],
                verbose_name="Projet QGIS '*.qgs'",
            ),
        ),
    ]
