# Generated by Django 3.2.13 on 2022-06-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0073_move_m2m_relation_to_wot_into_reports_model_definition'),
        ('reports', '0005_filter_report_models_for_integrator_and_wot'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='work_object_types',
            field=models.ManyToManyField(related_name='reports', to='permits.WorksObjectType'),
        ),
    ]
