# Generated by Django 3.2.13 on 2022-06-29 17:15

from django.db import migrations

import permits.fields
import reports.fields


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0006_set_background_file_public_and_switch_blocks_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportlayout",
            name="background",
            field=reports.fields.BackgroundFileField(
                blank=True,
                help_text='Image d\'arrière plan ("papier à en-tête").',
                null=True,
                storage=permits.fields.PrivateFileSystemStorage(),
                upload_to="backgound_paper",
            ),
        ),
    ]
