# Generated by Django 2.2.13 on 2020-09-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workstype",
            name="meta_type",
            field=models.IntegerField(
                choices=[
                    (0, "Autres"),
                    (1, "Chantier"),
                    (2, "Construction"),
                    (3, "Événement sportif"),
                    (4, "Événement culturel"),
                    (5, "Événement commercial"),
                    (6, "Dispositif de police"),
                ],
                default=0,
                verbose_name="Type générique",
            ),
        ),
        migrations.AddField(
            model_name="permitrequest",
            name="is_public",
            field=models.BooleanField(default=False, verbose_name="Publier"),
        ),
        migrations.AlterField(
            model_name="permitrequest",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Brouillon"),
                    (1, "Envoyée, en attente de traitement"),
                    (4, "Demande de compléments"),
                    (3, "En traitement"),
                    (5, "En validation"),
                    (2, "Approuvée"),
                    (6, "Refusée"),
                    (7, "Annonce réceptionnée"),
                ],
                default=0,
                verbose_name="état",
            ),
        ),
    ]
