# Generated by Django 2.2.13 on 2020-11-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permits", "0007_worksobject_wms_layers"),
    ]

    operations = [
        migrations.AddField(
            model_name="worksobject",
            name="wms_layers_order",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Ordre de(s) couche(s)"
            ),
        ),
    ]
