# Generated by Django 3.2.4 on 2021-08-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permits", "0038_is_backoffice"),
    ]

    operations = [
        migrations.AddField(
            model_name="worksobjectproperty",
            name="choices",
            field=models.TextField(
                blank=True,
                help_text="Entrez un choix par ligne",
                verbose_name="valeurs à choix",
            ),
        ),
        migrations.AlterField(
            model_name="worksobjectproperty",
            name="input_type",
            field=models.CharField(
                choices=[
                    ("text", "Texte"),
                    ("checkbox", "Case à cocher"),
                    ("number", "Nombre"),
                    ("file", "Fichier"),
                    ("address", "Adresse"),
                    ("date", "Date"),
                    ("list_single", "Choix simple"),
                    ("list_multiple", "Choix multiple"),
                ],
                max_length=30,
                verbose_name="type de caractéristique",
            ),
        ),
        migrations.AddConstraint(
            model_name="worksobjectproperty",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("input_type__in", ["list_single", "list_multiple"]),
                    ("choices", ""),
                    _negated=True,
                ),
                name="choices_not_empty_for_lists",
            ),
        ),
    ]
