# Generated by Django 3.2.7 on 2021-10-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permits", "0046_worksobjectproperty_types_order_helptext"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worksobjecttype",
            name="start_delay",
            field=models.IntegerField(
                blank=True,
                help_text="Délai minimum en jours avant la date de début (nombre entier positif ou négatif).",
                null=True,
                verbose_name="délai de commencement",
            ),
        ),
    ]
