# Generated by Django 3.2.7 on 2021-12-22 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "permits",
            "0053_line_number_textarea_custom_signature_additional_decision_information",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpermitrequest",
            name="creditor_type",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (7, "Architecte/Ingénieur"),
                    (6, "Association"),
                    (0, "Autres"),
                    (8, "Direction des travaux"),
                    (3, "Entreprise"),
                    (4, "Maître d'ouvrage"),
                    (2, "Propriétaire"),
                    (1, "Requérant (si différent de l'auteur de la demande)"),
                    (5, "Sécurité"),
                ],
                null=True,
                verbose_name="Destinaire de la facture",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpermitrequestamendpropertyvalue",
            name="works_object_type_choice",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="permits.worksobjecttypechoice",
                verbose_name="objet",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpermitrequestvalidation",
            name="comment_after",
            field=models.TextField(
                blank=True,
                help_text="Information supplémentaire facultative transmise au requérant",
                verbose_name="Commentaire (après)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpermitrequestvalidation",
            name="comment_before",
            field=models.TextField(
                blank=True,
                help_text="Information supplémentaire facultative transmise au requérant",
                verbose_name="Commentaire (avant)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpermitrequestvalidation",
            name="comment_during",
            field=models.TextField(
                blank=True,
                help_text="Information supplémentaire facultative transmise au requérant",
                verbose_name="Commentaire (pendant)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalworksobjectpropertyvalue",
            name="works_object_type_choice",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="permits.worksobjecttypechoice",
                verbose_name="objet",
            ),
        ),
        migrations.AlterField(
            model_name="permitactortype",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (7, "Architecte/Ingénieur"),
                    (6, "Association"),
                    (0, "Autres"),
                    (8, "Direction des travaux"),
                    (3, "Entreprise"),
                    (4, "Maître d'ouvrage"),
                    (2, "Propriétaire"),
                    (1, "Requérant (si différent de l'auteur de la demande)"),
                    (5, "Sécurité"),
                ],
                default=0,
                verbose_name="type de contact",
            ),
        ),
        migrations.AlterField(
            model_name="permitactortype",
            name="works_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="works_contact_types",
                to="permits.workstype",
                verbose_name="type de demande",
            ),
        ),
        migrations.AlterField(
            model_name="permitrequest",
            name="creditor_type",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (7, "Architecte/Ingénieur"),
                    (6, "Association"),
                    (0, "Autres"),
                    (8, "Direction des travaux"),
                    (3, "Entreprise"),
                    (4, "Maître d'ouvrage"),
                    (2, "Propriétaire"),
                    (1, "Requérant (si différent de l'auteur de la demande)"),
                    (5, "Sécurité"),
                ],
                null=True,
                verbose_name="Destinaire de la facture",
            ),
        ),
        migrations.AlterField(
            model_name="permitrequest",
            name="works_object_types",
            field=models.ManyToManyField(
                related_name="permit_requests",
                through="permits.WorksObjectTypeChoice",
                to="permits.WorksObjectType",
                verbose_name="Objets et types de demandes",
            ),
        ),
        migrations.AlterField(
            model_name="permitrequestactor",
            name="actor_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (7, "Architecte/Ingénieur"),
                    (6, "Association"),
                    (0, "Autres"),
                    (8, "Direction des travaux"),
                    (3, "Entreprise"),
                    (4, "Maître d'ouvrage"),
                    (2, "Propriétaire"),
                    (1, "Requérant (si différent de l'auteur de la demande)"),
                    (5, "Sécurité"),
                ],
                default=0,
                verbose_name="type de contact",
            ),
        ),
        migrations.AlterField(
            model_name="permitrequestamendproperty",
            name="works_object_types",
            field=models.ManyToManyField(
                related_name="amend_properties",
                to="permits.WorksObjectType",
                verbose_name="objets",
            ),
        ),
        migrations.AlterField(
            model_name="permitrequestamendpropertyvalue",
            name="works_object_type_choice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="amend_properties",
                to="permits.worksobjecttypechoice",
                verbose_name="objet",
            ),
        ),
        migrations.AlterField(
            model_name="permitrequestvalidation",
            name="comment_after",
            field=models.TextField(
                blank=True,
                help_text="Information supplémentaire facultative transmise au requérant",
                verbose_name="Commentaire (après)",
            ),
        ),
        migrations.AlterField(
            model_name="permitrequestvalidation",
            name="comment_before",
            field=models.TextField(
                blank=True,
                help_text="Information supplémentaire facultative transmise au requérant",
                verbose_name="Commentaire (avant)",
            ),
        ),
        migrations.AlterField(
            model_name="permitrequestvalidation",
            name="comment_during",
            field=models.TextField(
                blank=True,
                help_text="Information supplémentaire facultative transmise au requérant",
                verbose_name="Commentaire (pendant)",
            ),
        ),
        migrations.AlterField(
            model_name="worksobjectproperty",
            name="works_object_types",
            field=models.ManyToManyField(
                related_name="properties",
                to="permits.WorksObjectType",
                verbose_name="objets",
            ),
        ),
        migrations.AlterField(
            model_name="worksobjectpropertyvalue",
            name="works_object_type_choice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="properties",
                to="permits.worksobjecttypechoice",
                verbose_name="objet",
            ),
        ),
        migrations.AlterField(
            model_name="worksobjecttype",
            name="works_object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="works_object_types",
                to="permits.worksobject",
                verbose_name="objet",
            ),
        ),
        migrations.AlterField(
            model_name="worksobjecttype",
            name="works_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="works_object_types",
                to="permits.workstype",
                verbose_name="type",
            ),
        ),
    ]
