# Generated by Django 3.2.12 on 2022-03-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permits", "0059_add_order_field_to_works_object"),
    ]

    operations = [
        migrations.AddField(
            model_name="worksobjectproperty",
            name="services_to_notify",
            field=models.TextField(
                blank=True,
                help_text='Veuillez séparer les emails par une virgule ","',
                verbose_name="Emails des services à notifier",
            ),
        ),
    ]
