# Generated by Django 3.2.13 on 2022-08-19 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permits", "0078_create_web_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpermitauthor",
            name="iban",
            field=models.CharField(
                blank=True,
                help_text="A remplir uniquement pour les prestations liées à un remboursement (le titulaire du compte doit correspondre aux informations indiquées ci-dessus).",
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        message="L'IBAN doit être de type CH12 3456 7890 1234 5678 9",
                        regex="^[A-Z]{2}[0-9]{2}(?:[ ]?[0-9A-Z]{4}){4}(?:[ ]?[0-9]{1,2})?$",
                    )
                ],
                verbose_name="IBAN",
            ),
        ),
        migrations.AddField(
            model_name="permitauthor",
            name="iban",
            field=models.CharField(
                blank=True,
                help_text="A remplir uniquement pour les prestations liées à un remboursement (le titulaire du compte doit correspondre aux informations indiquées ci-dessus).",
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        message="L'IBAN doit être de type CH12 3456 7890 1234 5678 9",
                        regex="^[A-Z]{2}[0-9]{2}(?:[ ]?[0-9A-Z]{4}){4}(?:[ ]?[0-9]{1,2})?$",
                    )
                ],
                verbose_name="IBAN",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpermitauthor",
            name="vat_number",
            field=models.CharField(
                blank=True,
                max_length=19,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Le code d'entreprise doit être de type                          CHE-123.456.789 (TVA)                          et vous pouvez le trouver sur                          le registre fédéral des entreprises                          https://www.uid.admin.ch/search.aspx",
                        regex="^(CHE-)+\\d{3}\\.\\d{3}\\.\\d{3}(\\sTVA)?$",
                    )
                ],
                verbose_name="Numéro TVA",
            ),
        ),
        migrations.AlterField(
            model_name="permitauthor",
            name="vat_number",
            field=models.CharField(
                blank=True,
                max_length=19,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Le code d'entreprise doit être de type                          CHE-123.456.789 (TVA)                          et vous pouvez le trouver sur                          le registre fédéral des entreprises                          https://www.uid.admin.ch/search.aspx",
                        regex="^(CHE-)+\\d{3}\\.\\d{3}\\.\\d{3}(\\sTVA)?$",
                    )
                ],
                verbose_name="Numéro TVA",
            ),
        ),
    ]
