# Generated by Django 3.2.15 on 2022-09-06 12:26

from django.db import migrations

from geocity import settings


def create_default_site_and_fill_siteprofile(apps, schema_editor):
    """
    SiteProfile needs to be filled with the data of Site
    """
    Site = apps.get_model("sites", "Site")
    SiteProfile = apps.get_model("permits", "SiteProfile")

    Site.objects.update_or_create(
        domain=settings.DEFAULT_SITE, name=settings.DEFAULT_SITE + "(default site)"
    )

    for site_obj in Site.objects.all():
        SiteProfile.objects.create(
            site=site_obj,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("permits", "0080_change_site_extension_model"),
    ]

    operations = [
        migrations.RunPython(create_default_site_and_fill_siteprofile),
    ]
