# Generated by Django 3.2.15 on 2022-09-06 12:26

from django.db import migrations

from geocity import settings


def update_site_data(apps, schema_editor):
    """
    Create default Site
    Fill SiteProfile data of Site
    Add default site to each PermitAdministrativeEntity
    """
    Site = apps.get_model("sites", "Site")
    SiteProfile = apps.get_model("permits", "SiteProfile")
    PermitAdministrativeEntity = apps.get_model("permits", "PermitAdministrativeEntity")

    default_site = Site.objects.get_or_create(
        domain=settings.DEFAULT_SITE, name="default site"
    )

    for entity in PermitAdministrativeEntity.objects.all():
        entity.sites.add(default_site[0])

    for site_obj in Site.objects.all():
        SiteProfile.objects.get_or_create(
            site=site_obj,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("permits", "0080_change_site_extension_model"),
    ]

    operations = [
        migrations.RunPython(update_site_data),
    ]
