# Generated by Django 3.2.15 on 2022-09-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permits", "0081_update_site_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="permitdepartment",
            name="duo_client_id",
            field=models.CharField(
                blank=True,
                help_text="Double authentification à l'aide de duo, si renseigné",
                max_length=254,
                verbose_name="Client id pour duo",
            ),
        ),
        migrations.AddField(
            model_name="permitdepartment",
            name="duo_client_secret",
            field=models.CharField(
                blank=True,
                help_text="Double authentification à l'aide de duo, si renseigné",
                max_length=254,
                verbose_name="Client secret pour duo",
            ),
        ),
        migrations.AddField(
            model_name="permitdepartment",
            name="duo_host",
            field=models.CharField(
                blank=True,
                help_text="Double authentification à l'aide de duo, si renseigné",
                max_length=254,
                verbose_name="Host pour duo",
            ),
        ),
    ]
