# Generated by Django 3.2.15 on 2022-09-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permits", "0081_update_site_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpermitrequestgeotime",
            name="ends_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de fin"
            ),
        ),
        migrations.AlterField(
            model_name="historicalpermitrequestgeotime",
            name="starts_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de début"
            ),
        ),
        migrations.AlterField(
            model_name="permitrequestgeotime",
            name="ends_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de fin"
            ),
        ),
        migrations.AlterField(
            model_name="permitrequestgeotime",
            name="starts_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de début"
            ),
        ),
    ]
