# Generated by Django 3.2.15 on 2022-09-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permits", "0081_update_site_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="permitrequestamendproperty",
            name="is_visible_by_validators",
            field=models.BooleanField(
                default=False, verbose_name="Visible par les validateurs"
            ),
        ),
    ]
