# Generated by Django 3.2.15 on 2022-09-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permits", "0082_change_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="worksobjecttype",
            name="shortname",
            field=models.CharField(
                blank=True,
                help_text="Nom afficher par defaut (max. 32 caractères)",
                max_length=32,
                verbose_name="nom court",
            ),
        ),
    ]
