# Generated by Django 3.2.15 on 2022-09-27 10:50


from django.db import migrations

import geocity.apps.permits.fields


class Migration(migrations.Migration):

    dependencies = [
        ("permits", "0082_add_visible_by_validators_for_amend_property"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedpermitrequest",
            name="archive",
            field=geocity.apps.permits.fields.ArchiveDocumentFileField(
                default="CHANGEME",
                storage=geocity.apps.permits.fields.PrivateFileSystemStorage(),
                upload_to="",
                verbose_name="Archive",
            ),
            preserve_default=False,
        ),
    ]
