# Generated by Django 3.2.15 on 2022-10-07 12:24

from django.db import migrations, models

import geocity.apps.permits.fields


class Migration(migrations.Migration):

    dependencies = [
        ("permits", "0083_archivedpermitrequest_archive"),
    ]

    operations = [
        migrations.AddField(
            model_name="permitdepartment",
            name="shortname",
            field=models.CharField(
                blank=True,
                help_text="Nom affiché par défaut dans les différentes étapes du formulaire, ne s'affiche pas dans l'admin (max. 32 caractères)",
                max_length=32,
                verbose_name="nom court",
            ),
        ),
        migrations.AddField(
            model_name="worksobjecttype",
            name="has_geom_intersection_enabled",
            field=models.BooleanField(
                default=False, verbose_name="Activer l'intersection de géométries"
            ),
        ),
        migrations.AddField(
            model_name="worksobjecttype",
            name="shortname",
            field=models.CharField(
                blank=True,
                help_text="Nom affiché par défaut dans les différentes étapes du formulaire, ne s'affiche pas dans l'admin (max. 32 caractères)",
                max_length=32,
                verbose_name="nom court",
            ),
        ),
        migrations.AlterField(
            model_name="archivedpermitrequest",
            name="archive",
            field=geocity.apps.permits.fields.ArchiveDocumentFileField(
                storage=geocity.apps.permits.fields.ArchiveFileSystemStorage(),
                upload_to=geocity.apps.permits.fields.ArchiveDocumentFileField._upload_to,
                verbose_name="Archive",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpermitrequestgeotime",
            name="ends_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de fin"
            ),
        ),
        migrations.AlterField(
            model_name="historicalpermitrequestgeotime",
            name="starts_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de début"
            ),
        ),
        migrations.AlterField(
            model_name="permitrequestgeotime",
            name="ends_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de fin"
            ),
        ),
        migrations.AlterField(
            model_name="permitrequestgeotime",
            name="starts_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de début"
            ),
        ),
    ]
