# Generated by Django 3.2.15 on 2022-10-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permits", "0084_change_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="permitdepartment",
            name="shortname",
            field=models.CharField(
                blank=True,
                help_text="Nom affiché par défaut dans les différentes étapes du formulaire, ne s'affiche pas dans l'admin (max. 32 caractères)",
                max_length=32,
                verbose_name="nom court",
            ),
        ),
        migrations.AddField(
            model_name="worksobjecttype",
            name="has_geom_intersection_enabled",
            field=models.BooleanField(
                default=False, verbose_name="Activer l'intersection de géométries"
            ),
        ),
        migrations.AddField(
            model_name="worksobjecttype",
            name="shortname",
            field=models.CharField(
                blank=True,
                help_text="Nom affiché par défaut dans les différentes étapes du formulaire, ne s'affiche pas dans l'admin (max. 32 caractères)",
                max_length=32,
                verbose_name="nom court",
            ),
        ),
    ]
