# Generated by Django 3.2.13 on 2022-06-01 11:44

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import permits.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrintBlockContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PrintBlockCustom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='You can access the contents of the data returned by the API with placeholders like `{{data.properties.geotime_aggregated.start_date}}`. Have a look at <a href="http://localhost:9095/wfs3/collections/permits/items/1">the API</a> to see available data.')),
            ],
        ),
        migrations.CreateModel(
            name='PrintBlockMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qgis_project_file', permits.fields.AdministrativeEntityFileField(storage=permits.fields.PrivateFileSystemStorage(), upload_to='qgis_templates', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['qgs'])], verbose_name="Projet QGIS '*.qgs'")),
                ('qgis_print_template_name', models.CharField(max_length=150, verbose_name="Nom du template d'impression QGIS")),
            ],
        ),
        migrations.CreateModel(
            name='PrintBlockRichText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(help_text='You can access the contents of the data returned by the API with placeholders like `{{data.properties.geotime_aggregated.start_date}}`. Have a look at <a href="http://localhost:9095/wfs3/collections/permits/items/1">the API</a> to see available data.')),
            ],
        ),
        migrations.CreateModel(
            name='PrintBlockValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
    ]
