# Generated by Django 3.2.13 on 2022-06-08 06:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamblocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printblockcustom',
            name='content',
            field=models.TextField(help_text='Il est possible d\'accéder aux données de l\'API avec la syntaxe suivante: `{{data.properties.geotime_aggregated.start_date}}`. Consultez les résults de <a href="http://localhost:9095/wfs3/collections/permits/items/1">l\'API</a> pour voir les données disponibles.\nATTENTION: l\'accès à ce type de bloc doit être réservé aux utilisateurs approuvés puisque l\'implémentation actuelle n\'est pas sécurisée.'),
        ),
        migrations.AlterField(
            model_name='printblockmap',
            name='qgis_print_template_name',
            field=models.CharField(help_text="ATTENTION: l'accès à ce type de bloc doit être réservé aux utilisateurs approuvés puisque l'implémentation actuelle n'est pas sécurisée.", max_length=150, verbose_name="Nom du template d'impression QGIS"),
        ),
        migrations.AlterField(
            model_name='printblockrichtext',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Il est possible d\'accéder aux données de l\'API avec la syntaxe suivante: `{{data.properties.geotime_aggregated.start_date}}`. Consultez les résults de <a href="http://localhost:9095/wfs3/collections/permits/items/1">l\'API</a> pour voir les données disponibles.\nATTENTION: l\'accès à ce type de bloc doit être réservé aux utilisateurs approuvés puisque l\'implémentation actuelle n\'est pas sécurisée.'),
        ),
    ]
